{
  "hash": "d48849754e18858d5385d984c2ced60a",
  "result": {
    "engine": "knitr",
    "markdown": "# Model Selection\n## Formal Justification of Distributional Choice, Model Progression, and Variance Decomposition\n\n---\n\n> **Chapter Context.** This chapter provides the statistical foundation for three claims made implicitly throughout the modelling sequence: that the Zero-Inflated Gamma family is the appropriate distributional choice for this data, that each successive model extension was a genuine improvement rather than an over-fit, and that the final model accounts for a meaningful share of the variance in Australian rainfall. Each claim is addressed through a distinct formal procedure.\n\n---\n\n## Predictive Accuracy and Distributional Calibration\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_final$pred_rainfall <- predict(m6_mixed, type = \"response\")\n\nglobal_rmse <- sqrt(mean((df_final$rainfall - df_final$pred_rainfall)^2))\nglobal_mae <- mean(abs(df_final$rainfall - df_final$pred_rainfall))\n\nprint(paste(\"Global RMSE:\", round(global_rmse, 3), \"mm\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"Global RMSE: 7.539 mm\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Global MAE:\", round(global_mae, 3), \"mm\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] \"Global MAE: 2.736 mm\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nsims <- simulate(m6_mixed, nsim = 1000)\nsubset_sims <- sims[, sample(ncol(sims), 50)]\n\nppc_data <- bind_cols(\n  Observed = re_data$rainfall,\n  subset_sims\n) %>%\n  pivot_longer(\n    cols = -Observed,\n    names_to = \"Simulation\",\n    values_to = \"Simulated_Value\"\n  )\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot() +\n  geom_density(\n    data = ppc_data,\n    aes(x = Simulated_Value, group = Simulation),\n    color = \"gray70\",\n    size = 0.5,\n    alpha = 0.5\n  ) +\n  geom_density(\n    data = re_data,\n    aes(x = rainfall),\n    color = \"#0072B2\",\n    size = 1.2\n  ) +\n  coord_cartesian(xlim = c(-1, 20)) +\n  labs(\n    title = \"Posterior Predictive Check\",\n    subtitle = \"Grey lines: 50 datasets simulated from the fitted model. Blue line: observed data.\",\n    x = \"Rainfall (mm)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Posterior Predictive Check. The observed distribution (blue) lies well within the envelope of 50 model-simulated distributions (grey), confirming that the ZIG model replicates the key structural features of the rainfall distribution.](07-model-selection_files/figure-html/fig-ppc-1.png){#fig-ppc fig-align='center' width=100%}\n:::\n:::\n\n\nThe global error metrics provide a compact summary of predictive accuracy across all observations and all locations. The mean absolute error (MAE) of 2.736 mm indicates that the model's point prediction is within 2.7 mm of the actual recorded value on an average day. The root mean squared error (RMSE) of 7.539 mm is substantially larger, reflecting the asymmetric influence of extreme events in this metric: a small number of days on which a major storm was under-predicted by 50 mm or more exerts a disproportionate upward pull on the squared error average. The gap between MAE and RMSE is therefore informative in itself, confirming that prediction errors are not symmetrically distributed but are concentrated in the tail of the distribution.\n\nPoint error metrics measure accuracy at the mean but cannot assess whether the model is correctly reproducing the entire shape of the rainfall distribution. A posterior predictive check (PPC) addresses this more demanding criterion. We simulate 50 complete datasets from the fitted model and overlay their empirical densities against the observed distribution. If the model is well-specified, the observed density should be indistinguishable from the simulated envelope.\n\nThe result (@fig-ppc) shows close agreement across the full range of the distribution. The peak at 0 mm is reproduced accurately, confirming that the zero-inflation component is generating the correct proportion of dry-day predictions conditional on all covariates. The decay rate of the right tail follows the observed data closely, a property that a Gaussian model structurally cannot achieve given its symmetric support. The model is not merely fitting conditional means: it is correctly representing the probabilistic structure of the underlying climate system.\n\n---\n\n## Justification of the Distributional Family\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_linear <- glmmTMB(\n  rainfall ~ humidity3pm +\n    dewpoint_9am +\n    dewpoint_change +\n    pressure_change +\n    day_cos +\n    day_sin +\n    rainfall_ma7 +\n    days_since_rain +\n    humidity_ma7 +\n    rain_yesterday +\n    sunshine +\n    evaporation +\n    instability_index +\n    sun_humid_interaction +\n    cloud_development +\n    gust_U_EW +\n    gust_V_NS +\n    wind9am_V_NS +\n    wind9am_U_EW +\n    (1 | location),\n  data = re_data,\n  family = gaussian(link = \"identity\")\n)\n\nm_tweedie <- glmmTMB(\n  rainfall ~ humidity3pm +\n    dewpoint_9am +\n    dewpoint_change +\n    pressure_change +\n    day_cos +\n    day_sin +\n    rainfall_ma7 +\n    days_since_rain +\n    humidity_ma7 +\n    rain_yesterday +\n    sunshine +\n    evaporation +\n    instability_index +\n    sun_humid_interaction +\n    cloud_development +\n    gust_U_EW +\n    gust_V_NS +\n    wind9am_V_NS +\n    wind9am_U_EW +\n    (1 | location),\n  data = re_data,\n  family = tweedie(link = \"log\")\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_data %>%\n  select(rainfall, pred_linear, pred_tweedie, pred_zig) %>%\n  pivot_longer(\n    cols = -rainfall,\n    names_to = \"Model\",\n    values_to = \"Prediction\"\n  ) %>%\n  mutate(\n    Model = recode(\n      Model,\n      pred_linear = \"Linear (Gaussian)\",\n      pred_tweedie = \"Tweedie\",\n      pred_zig = \"ZI-Gamma (Final)\"\n    )\n  ) %>%\n  ggplot(aes(x = Prediction, fill = Model)) +\n  geom_density(alpha = 0.5) +\n  geom_density(\n    aes(x = rainfall),\n    data = re_data,\n    fill = NA,\n    color = \"black\",\n    linetype = \"dashed\",\n    size = 1\n  ) +\n  facet_wrap(~Model, scales = \"free\") +\n  coord_cartesian(xlim = c(-5, 20)) +\n  labs(\n    title = \"Why Distribution Matters\",\n    subtitle = \"Black dashed line: observed data. Coloured fill: predicted density from each model family.\",\n    x = \"Predicted Rainfall (mm)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Predictive density comparison across three distributional families. The Gaussian model predicts negative rainfall, a physical impossibility. Both the Tweedie and ZI-Gamma families respect the zero lower bound and approximate the right tail of the observed distribution.](07-model-selection_files/figure-html/fig-distribution-comparison-1.png){#fig-distribution-comparison fig-align='center' width=100%}\n:::\n:::\n\n\nChoosing a distributional family is not a cosmetic decision: it determines the support of the predictions, the variance function, and the structure of the likelihood being optimised. Three families were evaluated against the full predictor set to isolate the contribution of the distributional choice from the contribution of the predictors themselves.\n\n**The Gaussian model.** A standard linear mixed model with Gaussian errors generates predictions that extend into negative values. Because the Gaussian distribution has support over the entire real line, the model has no mechanism to prevent this, and negative rainfall is a physical impossibility. Beyond this qualitative failure, the Gaussian assumption also implies a symmetric and constant variance structure, which is incompatible with the heavy right skew and variance-mean dependence that the EDA (@sec-eda) documented extensively. Fitting a Gaussian model to this data is not merely suboptimal; it produces predictions that are fundamentally inconsistent with the properties of the system being modelled.\n\n**The Tweedie model.** The Tweedie distribution with power parameter $p \\in (1, 2)$ is a compound Poisson-Gamma distribution that naturally accommodates zero values alongside a continuous positive component. It respects the zero lower bound and can represent right-skewed positive data. However, it models zeros and positive values through a single unified process governed by a single mean parameter and the power index. This is a structural constraint: the probability of a zero and the expected positive value are both driven by the same linear predictor, and they cannot be allowed to respond to different sets of covariates.\n\n**The Zero-Inflated Gamma model.** The ZIG framework relaxes this constraint explicitly. The zero-inflation and conditional intensity components have separate linear predictors, which means predictors of occurrence and predictors of intensity are estimated independently. The EDA provides direct empirical motivation for this separation: the Markov analysis showed that `rain_yesterday` operates primarily through the hurdle, determining whether rain occurs at all, while the pressure change analysis showed that the diurnal pressure signal is more relevant to intensity. These two physical processes do not share the same covariates, and a model that constrains them to do so sacrifices interpretability and predictive accuracy. The ZIG framework gives each process its own parameter vector, making it both more flexible and more physically coherent than the Tweedie alternative.\n\n---\n\n## Progressive Model Selection via Likelihood Ratio Tests\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlrt_1v0 <- lmtest::lrtest(m0_null, m1_moisture)\nlrt_2v1 <- lmtest::lrtest(m1_moisture, m2_temporal)\nlrt_3v2 <- lmtest::lrtest(m2_temporal, m3_history)\nlrt_4v3 <- lmtest::lrtest(m3_history, m4_energy)\nlrt_5v4 <- lmtest::lrtest(m4_energy, m5_wind)\nlrt_6v5 <- lmtest::lrtest(m5_wind, m6_mixed)\n\nlrt_results <- tibble(\n  Comparison = c(\n    \"Null vs Moisture\",\n    \"Moisture vs Temporal\",\n    \"Temporal vs History\",\n    \"History vs Energy\",\n    \"Energy vs Wind\",\n    \"Wind vs Mixed Effects\"\n  ),\n  Chi_square = c(\n    lrt_1v0$Chisq[2],\n    lrt_2v1$Chisq[2],\n    lrt_3v2$Chisq[2],\n    lrt_4v3$Chisq[2],\n    lrt_5v4$Chisq[2],\n    lrt_6v5$Chisq[2]\n  ),\n  df = c(\n    lrt_1v0$Df[2],\n    lrt_2v1$Df[2],\n    lrt_3v2$Df[2],\n    lrt_4v3$Df[2],\n    lrt_5v4$Df[2],\n    lrt_6v5$Df[2]\n  ),\n  raw_p = c(\n    lrt_1v0$`Pr(>Chisq)`[2],\n    lrt_2v1$`Pr(>Chisq)`[2],\n    lrt_3v2$`Pr(>Chisq)`[2],\n    lrt_4v3$`Pr(>Chisq)`[2],\n    lrt_5v4$`Pr(>Chisq)`[2],\n    lrt_6v5$`Pr(>Chisq)`[2]\n  )\n) %>%\n  mutate(\n    adj_p_value = p.adjust(raw_p, method = \"holm\"),\n    Significant = ifelse(\n      adj_p_value < 0.001,\n      \"***\",\n      ifelse(adj_p_value < 0.01, \"**\", ifelse(adj_p_value < 0.05, \"*\", \"ns\"))\n    ),\n    AIC_improvement = c(\n      AIC(m0_null) - AIC(m1_moisture),\n      AIC(m1_moisture) - AIC(m2_temporal),\n      AIC(m2_temporal) - AIC(m3_history),\n      AIC(m3_history) - AIC(m4_energy),\n      AIC(m4_energy) - AIC(m5_wind),\n      AIC(m5_wind) - AIC(m6_mixed)\n    )\n  )\n\nlrt_results %>%\n  mutate(\n    Chi_square = round(Chi_square, 2),\n    AIC_improvement = round(AIC_improvement, 1)\n  ) %>%\n  kable(\n    caption = \"Likelihood Ratio Tests: Progressive Model Comparisons (Holm-Corrected)\"\n  ) %>%\n  kable_styling(bootstrap_options = \"striped\", full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Likelihood Ratio Tests: Progressive Model Comparisons (Holm-Corrected)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Comparison </th>\n   <th style=\"text-align:right;\"> Chi_square </th>\n   <th style=\"text-align:right;\"> df </th>\n   <th style=\"text-align:right;\"> raw_p </th>\n   <th style=\"text-align:right;\"> adj_p_value </th>\n   <th style=\"text-align:left;\"> Significant </th>\n   <th style=\"text-align:right;\"> AIC_improvement </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Null vs Moisture </td>\n   <td style=\"text-align:right;\"> 39051.88 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 39039.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Moisture vs Temporal </td>\n   <td style=\"text-align:right;\"> 15813.45 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 15803.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Temporal vs History </td>\n   <td style=\"text-align:right;\"> 1708.85 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 1700.8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> History vs Energy </td>\n   <td style=\"text-align:right;\"> 1393.61 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 1383.6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Energy vs Wind </td>\n   <td style=\"text-align:right;\"> 608.53 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 600.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Wind vs Mixed Effects </td>\n   <td style=\"text-align:right;\"> 6529.12 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:right;\"> 6503.1 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {#tbl-model-selection .cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_selection <- tibble(\n  Model = c(\n    \"M0: Null\",\n    \"M1: Moisture\",\n    \"M2: Temporal\",\n    \"M3: History\",\n    \"M4: Energy\",\n    \"M5: Wind\",\n    \"M6: Mixed Effects\"\n  ),\n  AIC = c(\n    AIC(m0_null),\n    AIC(m1_moisture),\n    AIC(m2_temporal),\n    AIC(m3_history),\n    AIC(m4_energy),\n    AIC(m5_wind),\n    AIC(m6_mixed)\n  ),\n  BIC = c(\n    BIC(m0_null),\n    BIC(m1_moisture),\n    BIC(m2_temporal),\n    BIC(m3_history),\n    BIC(m4_energy),\n    BIC(m5_wind),\n    BIC(m6_mixed)\n  )\n) %>%\n  mutate(\n    Delta_AIC = AIC - min(AIC),\n    AIC_weight = exp(-0.5 * Delta_AIC) / sum(exp(-0.5 * Delta_AIC))\n  ) %>%\n  arrange(AIC)\n\nmodel_selection %>%\n  mutate(across(where(is.numeric), ~ round(., 2))) %>%\n  kable(caption = \"Model Selection Summary: AIC, BIC, and Akaike Weights\") %>%\n  kable_styling(bootstrap_options = \"striped\", full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Model Selection Summary: AIC, BIC, and Akaike Weights</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> AIC </th>\n   <th style=\"text-align:right;\"> BIC </th>\n   <th style=\"text-align:right;\"> Delta_AIC </th>\n   <th style=\"text-align:right;\"> AIC_weight </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> M6: Mixed Effects </td>\n   <td style=\"text-align:right;\"> 396638.2 </td>\n   <td style=\"text-align:right;\"> 397032.7 </td>\n   <td style=\"text-align:right;\"> 0.00 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M5: Wind </td>\n   <td style=\"text-align:right;\"> 403141.3 </td>\n   <td style=\"text-align:right;\"> 403407.6 </td>\n   <td style=\"text-align:right;\"> 6503.12 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M4: Energy </td>\n   <td style=\"text-align:right;\"> 403741.9 </td>\n   <td style=\"text-align:right;\"> 403968.7 </td>\n   <td style=\"text-align:right;\"> 7103.65 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M3: History </td>\n   <td style=\"text-align:right;\"> 405125.5 </td>\n   <td style=\"text-align:right;\"> 405303.0 </td>\n   <td style=\"text-align:right;\"> 8487.27 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M2: Temporal </td>\n   <td style=\"text-align:right;\"> 406826.3 </td>\n   <td style=\"text-align:right;\"> 406964.4 </td>\n   <td style=\"text-align:right;\"> 10188.11 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M1: Moisture </td>\n   <td style=\"text-align:right;\"> 422629.8 </td>\n   <td style=\"text-align:right;\"> 422718.6 </td>\n   <td style=\"text-align:right;\"> 25991.56 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> M0: Null </td>\n   <td style=\"text-align:right;\"> 461669.7 </td>\n   <td style=\"text-align:right;\"> 461699.3 </td>\n   <td style=\"text-align:right;\"> 65031.45 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(\n  model_selection,\n  aes(\n    x = factor(\n      Model,\n      levels = c(\n        \"M6: Mixed Effects\",\n        \"M5: Wind\",\n        \"M4: Energy\",\n        \"M3: History\",\n        \"M2: Temporal\",\n        \"M1: Moisture\",\n        \"M0: Null\"\n      )\n    ),\n    y = AIC\n  )\n) +\n  geom_point(size = 4, color = \"#0072B2\") +\n  geom_line(aes(group = 1), size = 1, color = \"#0072B2\", alpha = 0.5) +\n  geom_hline(\n    yintercept = min(model_selection$AIC),\n    linetype = \"dashed\",\n    color = \"red\"\n  ) +\n  geom_text(\n    aes(label = sprintf(\"Delta = %.0f\", Delta_AIC)),\n    vjust = -1,\n    size = 3.5,\n    fontface = \"bold\"\n  ) +\n  labs(\n    title = \"Model Selection: Progressive AIC Improvement\",\n    subtitle = \"Every extension is confirmed by LRT p < 0.001. Red dashed line marks the best model (M6).\",\n    x = \"Model (ordered by complexity)\",\n    y = \"AIC (lower is better)\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1, face = \"bold\"),\n    plot.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![AIC trajectory across the progressive model sequence. Each extension reduces AIC monotonically, confirming that no step introduced net redundancy. The two largest gains correspond to the initial moisture predictors and the final mixed-effects structure.](07-model-selection_files/figure-html/fig-model-selection-1.png){#fig-model-selection fig-align='center' width=100%}\n:::\n:::\n\n\nAIC quantifies the information lost when a given model is used to approximate the true data-generating process, penalising complexity to discourage over-fitting. A monotonically decreasing AIC sequence across progressively more complex models is not guaranteed: it is possible to add predictors that improve the likelihood by less than the penalty incurred for the additional parameters, which would cause the AIC to rise. That every extension in this sequence produced a net AIC reduction confirms that each added component captures genuine signal rather than noise.\n\nThe likelihood ratio test provides the corresponding inferential framework. For two nested models, the test statistic $-2 \\ln(\\mathcal{L}_\\text{reduced} / \\mathcal{L}_\\text{full})$ follows a chi-squared distribution with degrees of freedom equal to the difference in the number of parameters. The null hypothesis is that the additional parameters are jointly zero, meaning the reduced model is adequate. All six comparisons reject this null at $p < 0.001$ after Holm correction for multiple testing. Even the smallest gain in the sequence (wind vectors, M5, $\\chi^2 = 608.53$, $df = 4$) represents an improvement that is overwhelmingly unlikely under the null, and not merely a consequence of the large sample size: the chi-squared statistic scales with the improvement in log-likelihood, not with $N$ directly.\n\nThe Akaike weights in the selection table provide a further calibration. With a $\\Delta\\text{AIC}$ of 65,031.5 separating the best and worst models, the weight on M6 rounds to 1.0 to any reasonable decimal precision. There is no realistic information-theoretic case for preferring any earlier model in the sequence.\n\n---\n\n## Variance Decomposition\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nre_test <- lmtest::lrtest(m5_wind, m6_mixed)\nprint(re_test)\n#> Likelihood ratio test\n#> \n#> Model 1: rainfall ~ humidity3pm + dewpoint_9am + dewpoint_change + pressure_change + \n#>     day_cos + day_sin + rainfall_ma7 + days_since_rain + humidity_ma7 + \n#>     rain_yesterday + sunshine + evaporation + instability_index + \n#>     sun_humid_interaction + cloud_development + gust_U_EW + gust_V_NS + \n#>     wind9am_V_NS + wind9am_U_EW\n#> Model 2: rainfall ~ humidity3pm + dewpoint_9am + dewpoint_change + pressure_change + \n#>     day_cos + day_sin + rainfall_ma7 + days_since_rain + humidity_ma7 + \n#>     rain_yesterday + sunshine + evaporation + instability_index + \n#>     sun_humid_interaction + cloud_development + gust_U_EW + gust_V_NS + \n#>     wind9am_V_NS + wind9am_U_EW + diag(1 + humidity3pm + rain_yesterday + \n#>     dewpoint_change | location)\n#>   #Df  LogLik Df  Chisq Pr(>Chisq)    \n#> 1  27 -201544                         \n#> 2  40 -198279 13 6529.1  < 2.2e-16 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nr2_vals <- performance::r2_nakagawa(m6_mixed)\n\ncat(sprintf(\n  \"\\nMarginal R2  (Fixed Effects only): %.4f\\n\",\n  r2_vals$R2_marginal\n))\n#> \n#> Marginal R2  (Fixed Effects only): 0.3498\ncat(sprintf(\n  \"Conditional R2 (Fixed + Random Effects):  %.4f\\n\",\n  r2_vals$R2_conditional\n))\n#> Conditional R2 (Fixed + Random Effects):  0.4464\n```\n:::\n\n\nStandard $R^2$ is not directly defined for generalised linear mixed models because the likelihood-based framework does not produce a natural residual sum of squares. Nakagawa's method provides a principled extension by partitioning the total variance in the model into components attributable to fixed effects, random effects, and residual noise, expressed on the latent (link) scale.\n\nThe marginal $R^2$ of 0.3498 quantifies the proportion of variance explained by the fixed effects alone: humidity, pressure, wind vectors, seasonality, persistence, and all derived features. The fixed-effects predictors collectively account for 34.9% of the variance in daily rainfall intensity. This is a realistic figure for a system as inherently stochastic as precipitation: the chaotic dynamics of mesoscale atmospheric processes set a fundamental upper bound on predictability from station-level daily observations, and a third of the total variance is a meaningful share of what is structurally predictable.\n\nThe conditional $R^2$ of 0.4464 incorporates the additional variance explained by the location-specific random effects. The difference between the two values, 0.0966, represents the share of variance attributable purely to geography: the persistent differences between locations that remain after all dynamic weather variables have been controlled for. Approximately 10% of the total variance in Australian daily rainfall is explained not by what the atmosphere is doing today but by where the measurement station sits on the continent. This quantifies, in a single number, the geographic heterogeneity that the random effects structure was designed to capture and that a fixed-effects-only model would leave in the residuals.\n\n---\n\n## Conclusion\n\nThe evidence assembled across this chapter supports the following conclusions. The ZIG distributional family is the appropriate choice for this data: the Gaussian model produces physically impossible predictions and the Tweedie model, while valid, constrains occurrence and intensity to share the same linear predictor in a way that is empirically unjustified. Every step in the progressive model sequence represents a statistically significant improvement, confirmed by likelihood ratio tests at $p < 0.001$ after multiple comparison correction, and the Akaike weight of the final model is effectively 1. The posterior predictive check confirms that the model replicates the distributional shape of Australian rainfall, not only its conditional mean. And the variance decomposition establishes that the final model explains 44.6% of total variance, of which approximately a tenth is attributable to the geographic heterogeneity captured by the random effects.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}