<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An in-depth statistical analysis of rainfall patterns across 49 Australian cities using Zero-Inflated Gamma GLMMs.">

<title>2&nbsp; Data Preparation – Australian Rainfall Dynamics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/03-sensitivity.html" rel="next">
<link href="../chapters/01-intro.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-e66b50aa4120364bfa72329fe8653b98.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-463e05341c278a50bd9d8b9e5c352418.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-data-prep.html">Data</a></li><li class="breadcrumb-item"><a href="../chapters/02-data-prep.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Australian Rainfall Dynamics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting Australian Rainfall</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-data-prep.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputation Sensitivity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature Engineering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#computational-environment" id="toc-computational-environment" class="nav-link active" data-scroll-target="#computational-environment"><span class="header-section-number">2.1</span> Computational Environment</a></li>
  <li><a href="#initial-cleaning-and-standardisation" id="toc-initial-cleaning-and-standardisation" class="nav-link" data-scroll-target="#initial-cleaning-and-standardisation"><span class="header-section-number">2.2</span> Initial Cleaning and Standardisation</a></li>
  <li><a href="#sec-missingness-diagnostics" id="toc-sec-missingness-diagnostics" class="nav-link" data-scroll-target="#sec-missingness-diagnostics"><span class="header-section-number">2.3</span> Missingness Diagnostics</a>
  <ul class="collapse">
  <li><a href="#sec-co-missingness" id="toc-sec-co-missingness" class="nav-link" data-scroll-target="#sec-co-missingness"><span class="header-section-number">2.3.1</span> Co-missingness Structure</a></li>
  <li><a href="#sec-temporal-structure" id="toc-sec-temporal-structure" class="nav-link" data-scroll-target="#sec-temporal-structure"><span class="header-section-number">2.3.2</span> Temporal Structure and Structural Breaks</a></li>
  <li><a href="#sec-ghost-sensor" id="toc-sec-ghost-sensor" class="nav-link" data-scroll-target="#sec-ghost-sensor"><span class="header-section-number">2.3.3</span> Geographic Concentration: Ghost Sensor Identification</a></li>
  <li><a href="#sec-weather-conditionality" id="toc-sec-weather-conditionality" class="nav-link" data-scroll-target="#sec-weather-conditionality"><span class="header-section-number">2.3.4</span> Weather-Conditionality of Sunshine Missingness</a></li>
  <li><a href="#missing-pattern-structure" id="toc-missing-pattern-structure" class="nav-link" data-scroll-target="#missing-pattern-structure"><span class="header-section-number">2.3.5</span> Missing Pattern Structure</a></li>
  </ul></li>
  <li><a href="#sec-imputation-pipeline" id="toc-sec-imputation-pipeline" class="nav-link" data-scroll-target="#sec-imputation-pipeline"><span class="header-section-number">2.4</span> Imputation Pipeline</a>
  <ul class="collapse">
  <li><a href="#stage-1-temporal-interpolation" id="toc-stage-1-temporal-interpolation" class="nav-link" data-scroll-target="#stage-1-temporal-interpolation"><span class="header-section-number">2.4.1</span> Stage 1: Temporal Interpolation</a></li>
  <li><a href="#stage-2-multivariate-imputation-via-predictive-mean-matching-and-random-forest" id="toc-stage-2-multivariate-imputation-via-predictive-mean-matching-and-random-forest" class="nav-link" data-scroll-target="#stage-2-multivariate-imputation-via-predictive-mean-matching-and-random-forest"><span class="header-section-number">2.4.2</span> Stage 2: Multivariate Imputation via Predictive Mean Matching and Random Forest</a></li>
  <li><a href="#ghost-sensor-flagging" id="toc-ghost-sensor-flagging" class="nav-link" data-scroll-target="#ghost-sensor-flagging"><span class="header-section-number">2.4.3</span> Ghost Sensor Flagging</a></li>
  </ul></li>
  <li><a href="#post-imputation-dataset-properties" id="toc-post-imputation-dataset-properties" class="nav-link" data-scroll-target="#post-imputation-dataset-properties"><span class="header-section-number">2.5</span> Post-Imputation Dataset Properties</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/02-data-prep.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/02-data-prep.html">Data</a></li><li class="breadcrumb-item"><a href="../chapters/02-data-prep.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-data" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<blockquote class="blockquote">
<p><strong>Chapter Context.</strong> Before any statistical analysis can proceed, the raw dataset must be transformed into a form that is both analytically tractable and physically credible. This chapter documents three decisions that have downstream consequences throughout the report: the syntactic and temporal standardisation of the raw data, a diagnostic investigation of the structure and mechanism of the missingness, and the design of a two-stage imputation pipeline informed by that investigation. Each decision is motivated by the properties of the data-generating process rather than by computational convenience.</p>
</blockquote>
<hr>
<section id="computational-environment" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="computational-environment"><span class="header-section-number">2.1</span> Computational Environment</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"config.R"</span>))</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"utils.R"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The package selection reflects the specific demands of meteorological data analysis. The core wrangling and visualisation toolkit (<code>tidyverse</code>, <code>janitor</code>, <code>kableExtra</code>) handles routine data manipulation. The modelling stack (<code>glmmTMB</code>, <code>DHARMa</code>, <code>splines</code>, <code>mgcv</code>) is assembled for the zero-inflated mixed-effects framework documented in later chapters. The imputation stack (<code>mice</code>) supports the Random Forest and chained imputation procedures described below. The missingness diagnostic stack (<code>naniar</code>, <code>glue</code>) supports the structural analysis in <a href="#sec-missingness-diagnostics" class="quarto-xref"><span>Section 2.3</span></a>. Libraries are loaded via <code>librarian</code>, which installs missing packages automatically and ensures reproducibility across environments.</p>
<hr>
</section>
<section id="initial-cleaning-and-standardisation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="initial-cleaning-and-standardisation"><span class="header-section-number">2.2</span> Initial Cleaning and Standardisation</h2>
<p>The raw dataset undergoes three transformations before any missingness analysis or imputation.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"cleaning.R"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>Column standardisation.</strong> All variable names are converted to <code>snake_case</code> via <code>janitor::clean_names()</code>, called at ingestion. This eliminates downstream ambiguity in variable references and ensures internal consistency across all chapters.</p>
<p><strong>Temporal feature extraction.</strong> The <code>date</code> column is typed as a <code>Date</code> object and two derived features are extracted: <code>month</code> (as a factor) and <code>day</code> (day of week, labelled). Month captures the seasonal structure of Australian precipitation; day of week is retained as a potential control variable for reporting artefacts in the raw data.</p>
<p><strong>Target filtering.</strong> Observations where <code>rainfall</code> is missing are removed. Records without a ground-truth rainfall measurement have no supervised learning value and cannot contribute to either the hurdle or the intensity component of the ZIG model.</p>
<hr>
</section>
<section id="sec-missingness-diagnostics" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-missingness-diagnostics"><span class="header-section-number">2.3</span> Missingness Diagnostics</h2>
<p>Before designing an imputation strategy, it is necessary to understand the mechanism and structure of the missing data. The choice between imputation methods depends critically on three questions: whether missingness is random with respect to other variables in the dataset, whether missing values cluster at specific locations or time periods, and whether the four most-affected variables fail independently or as a coordinated group. A strategy designed without answering these questions risks either under-imputing (discarding recoverable signal) or over-imputing (fabricating data in regions where recovery is not possible). The five analyses below provide the empirical basis for each design decision in the pipeline that follows.</p>
<section id="sec-co-missingness" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="sec-co-missingness"><span class="header-section-number">2.3.1</span> Co-missingness Structure</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"data_missingness.R"</span>))</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">render_comissingness_table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; High missingness variables: sunshine, evaporation, cloud3pm, cloud9am 
#&gt; 
#&gt;   evaporation -&gt; sunshine: 93.2%  (when evaporation is missing, sunshine is missing) 
#&gt;   cloud9am -&gt; cloud3pm: 92.6%  (when cloud9am is missing, cloud3pm is missing) 
#&gt;   cloud3pm -&gt; cloud9am: 87.2%  (when cloud3pm is missing, cloud9am is missing) 
#&gt;   cloud9am -&gt; sunshine: 84.3%  (when cloud9am is missing, sunshine is missing) 
#&gt;   sunshine -&gt; evaporation: 83.8%  (when sunshine is missing, evaporation is missing) 
#&gt;   cloud3pm -&gt; sunshine: 82.5%  (when cloud3pm is missing, sunshine is missing) 
#&gt;   cloud9am -&gt; evaporation: 81.4%  (when cloud9am is missing, evaporation is missing) 
#&gt;   cloud3pm -&gt; evaporation: 78%  (when cloud3pm is missing, evaporation is missing) 
#&gt;   evaporation -&gt; cloud3pm: 73.7%  (when evaporation is missing, cloud3pm is missing) 
#&gt;   evaporation -&gt; cloud9am: 72.5%  (when evaporation is missing, cloud9am is missing) 
#&gt;   sunshine -&gt; cloud3pm: 70.1%  (when sunshine is missing, cloud3pm is missing) 
#&gt;   sunshine -&gt; cloud9am: 67.5%  (when sunshine is missing, cloud9am is missing)</code></pre>
</div>
<div id="tbl-co-missingness" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-co-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Conditional Co-missingness Matrix
</figcaption>
<div aria-describedby="tbl-co-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small">
<caption>Conditional Co-missingness: when var1 is missing, what percentage of the time is var2 also missing?</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 1 (Missing)</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Co-missing (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">evaporation</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">93.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">cloud9am</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">92.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">87.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">cloud9am</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">84.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sunshine</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">83.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">82.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cloud9am</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">81.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">78.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">evaporation</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">73.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">evaporation</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">72.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sunshine</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">70.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">sunshine</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">67.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The co-missingness matrix (<a href="#tbl-co-missingness" class="quarto-xref">Table&nbsp;<span>2.1</span></a>) confirms that these four variables fail as a systematic cluster rather than independently. The dependencies are strongest between instrumental pairs: if evaporation is missing, there is a 93.2% probability that sunshine is also missing. Even the weakest relationship in the matrix (sunshine to cloud9am) retains a rate of 67.5%, which is nearly double what would be expected under random failure.</p>
<p>Under MCAR, the co-missing rates would be close to the marginal missingness rates of each variable, roughly 40 to 48%. Rates uniformly between 67% and 93% instead indicate a shared upstream cause: the instrumentation profile of each station. Sunshine recorders, evaporation pans, and cloud coverage sensors are deployed as a package, not individually. A station without one is very likely to lack the others. This is MNAR at the station level. The practical consequence for imputation is that treating the four variables as independently missing would be incorrect: their correlations when observed are available precisely because they fail together, and a multivariate imputation method that exploits those cross-variable relationships will outperform four separate univariate models.</p>
</section>
<section id="sec-temporal-structure" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="sec-temporal-structure"><span class="header-section-number">2.3.2</span> Temporal Structure and Structural Breaks</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">plot_temporal_missingness</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-temporal-missingness" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temporal-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-data-prep_files/figure-html/fig-temporal-missingness-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temporal-missingness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Timeline of systematic missingness across the four high-missingness variables. The stepped increases visible particularly in sunshine and evaporation indicate structural breaks in data collection rather than random sensor failures.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The temporal analysis (<a href="#fig-temporal-missingness" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>) confirms that missingness is not randomly distributed over time. The cloud cover variables maintain a roughly stable and high missingness rate across the observation window, consistent with a fixed set of stations never having recorded these measurements. The <code>sunshine</code> and <code>evaporation</code> variables show a distinct stepped pattern: missingness rises at specific breakpoints rather than fluctuating randomly, indicating that certain stations were decommissioned or that recording protocols changed at identifiable calendar dates.</p>
<p>This temporal structure has a direct implication for the interpolation stage of the pipeline. Linear interpolation is appropriate when a smooth trajectory can be inferred from values on either side of a gap. Extended contiguous gaps produced by a structural break have no valid upper boundary from which to interpolate, and filling them with temporal interpolation would create long synthetic sequences with no empirical anchor. The five-day interpolation cap set in Stage 1 of the pipeline is a direct response to this finding.</p>
</section>
<section id="sec-ghost-sensor" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="sec-ghost-sensor"><span class="header-section-number">2.3.3</span> Geographic Concentration: Ghost Sensor Identification</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">render_ghost_sensor_table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 
#&gt; Total ghost sensor instances identified: 60 across 22 locations</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Ghost Sensor Instances: Location-Variable Pairs with &gt;90% Missingness</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Location</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Missing (n)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Missing (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Albury</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albury</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BadgerysCreek</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">BadgerysCreek</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BadgerysCreek</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">BadgerysCreek</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Newcastle</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Newcastle</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NorahHead</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3004</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">NorahHead</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3004</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NorahHead</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3004</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">NorahHead</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3004</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Penrith</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Penrith</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Penrith</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Penrith</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Richmond</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wollongong</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wollongong</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tuggeranong</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuggeranong</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tuggeranong</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuggeranong</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3039</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">MountGinini</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MountGinini</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">MountGinini</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MountGinini</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ballarat</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ballarat</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bendigo</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nhil</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nhil</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nhil</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nhil</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dartmoor</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dartmoor</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GoldCoast</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">GoldCoast</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GoldCoast</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">GoldCoast</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelaide</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3193</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelaide</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3193</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Witchcliffe</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Witchcliffe</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Witchcliffe</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Witchcliffe</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PearceRAAF</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3009</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SalmonGums</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3001</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SalmonGums</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3001</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SalmonGums</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3001</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SalmonGums</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3001</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Walpole</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">3006</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Walpole</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3006</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Walpole</td>
<td style="text-align: left;">cloud9am</td>
<td style="text-align: right;">3006</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Walpole</td>
<td style="text-align: left;">cloud3pm</td>
<td style="text-align: right;">3006</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Launceston</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">3040</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Katherine</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uluru</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uluru</td>
<td style="text-align: left;">sunshine</td>
<td style="text-align: right;">1578</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Launceston</td>
<td style="text-align: left;">evaporation</td>
<td style="text-align: right;">2899</td>
<td style="text-align: right;">95.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The location-level analysis identifies the specific station-variable pairs responsible for the bulk of the aggregate missingness. The top ten instances from the script output, all at exactly 100% missing, are as follows: Albury (<code>evaporation</code>, 3,040 observations; <code>sunshine</code>, 3,040), BadgerysCreek (<code>evaporation</code>, 3,009; <code>sunshine</code>, 3,009; <code>cloud9am</code>, 3,009; <code>cloud3pm</code>, 3,009), Newcastle (<code>evaporation</code>, 3,039; <code>sunshine</code>, 3,039), and NorahHead (<code>evaporation</code>, 3,004; <code>sunshine</code>, 3,004). At these stations, the instrument in question recorded a value on zero days across the entire observation window. These are not sensors experiencing intermittent failure; they are sensors that were never present or that were removed before the data collection period began.</p>
<p>The distinction between ghost sensors and ordinary missingness is consequential for imputation. For a gap of five to fifteen consecutive missing days, a Random Forest model can generate reasonable predictions by drawing on correlated variables at the same station and the same variable at nearby stations. For a gap spanning 3,000 or more consecutive observations, this extrapolation has no empirical support whatsoever: there is no observed value at that station and variable combination to anchor or validate the prediction. Values produced for these pairs would be statistically plausible by construction but would carry no physical information about what the instrument would have actually recorded. Ghost sensor pairs are identified before Stage 2 runs and flagged so that their imputed values can be treated with appropriate scepticism in downstream analysis.</p>
</section>
<section id="sec-weather-conditionality" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="sec-weather-conditionality"><span class="header-section-number">2.3.4</span> Weather-Conditionality of Sunshine Missingness</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">render_sunshine_mcar_table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-sunshine-mcar-test" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sunshine-mcar-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Sunshine Missingness Rate by Daily Rainfall Status
</figcaption>
<div aria-describedby="tbl-sunshine-mcar-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover do-not-create-environment cell caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Day Type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observations (n)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sunshine Missing (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dry (&lt;=1mm)</td>
<td style="text-align: right;">110319</td>
<td style="text-align: right;">47.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rainy (&gt;1mm)</td>
<td style="text-align: right;">31880</td>
<td style="text-align: right;">47.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">plot_sunshine_rainfall_density</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-sunshine-rainfall-density" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sunshine-rainfall-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-data-prep_files/figure-html/fig-sunshine-rainfall-density-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sunshine-rainfall-density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Density of rainfall amounts on days where sunshine data is present versus missing. The near-identical distributions confirm that sunshine missingness is not weather-conditional: the same stations are missing sunshine on both dry and rainy days because the instrument was simply not installed, not because it failed during precipitation events.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A specific concern when imputing a predictor variable is outcome-related missingness: if sunshine sensors failed more often on rainy days, then the imputed values would carry a directional signal about the target variable and could introduce bias into the training data.</p>
<p>The empirical test refutes this concern. The table output (<a href="#tbl-sunshine-mcar-test" class="quarto-xref">Table&nbsp;<span>2.2</span></a>) reports a sunshine missing rate of 47.8% on 110,319 dry days (rainfall at most 1 mm) and 47.2% on 31,880 rainy days (rainfall above 1 mm), a difference of 0.6 percentage points. The density plot (<a href="#fig-sunshine-rainfall-density" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>) makes the same point visually: the distribution of rainfall amounts on days with missing sunshine and on days with present sunshine are indistinguishable across the full range from 0 to 50 mm. The slight visual offset in the figure reflects not a systematic pattern but the difference in the sizes of the two groups.</p>
<p>Sunshine missingness is station-conditional rather than weather-conditional. The same stations record missing sunshine on both dry and rainy days at nearly identical rates, because the instrument is absent from those stations entirely. This finding clears the imputation path: there is no outcome-related confound to correct for.</p>
</section>
<section id="missing-pattern-structure" class="level3" data-number="2.3.5">
<h3 data-number="2.3.5" class="anchored" data-anchor-id="missing-pattern-structure"><span class="header-section-number">2.3.5</span> Missing Pattern Structure</h3>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">render_miss_pattern_table</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<caption>Distribution of Missing Variable Count per Observation</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Variables Missing (of 4)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Observations (n)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Percentage (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">62566</td>
<td style="text-align: right;">43.012512</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">10525</td>
<td style="text-align: right;">7.235666</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">20376</td>
<td style="text-align: right;">14.007975</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">11378</td>
<td style="text-align: right;">7.822082</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">40615</td>
<td style="text-align: right;">27.921765</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The case-level output from the script reveals a strongly bimodal structure across five distinct patterns. Of all observations: 62,566 (43.0%) have none of the four variables missing; 10,525 (7.2%) have exactly one missing; 20,376 (14.0%) have exactly two missing; 11,378 (7.8%) have exactly three missing; and 40,615 (27.9%) have all four missing simultaneously. The two endpoint categories, zero missing and all four missing, together account for 70.9% of all observations.</p>
<p>The 27.9% with complete simultaneous missingness corresponds directly to the ghost sensor stations identified in <a href="#sec-ghost-sensor" class="quarto-xref"><span>Section 2.3.3</span></a>. For these observations, no imputation is supportable and the values remain missing after the pipeline. The 43.0% with no missingness require no intervention. The substantive imputation work is concentrated in the remaining 29.1% across the three intermediate patterns, where partial instrumentation means that correlated predictors are available to inform the Random Forest estimates. The bimodal structure also confirms that the co-missingness finding is not a statistical artifact: observations genuinely tend to be fully instrumented or minimally instrumented, not randomly partially instrumented.</p>
<hr>
</section>
</section>
<section id="sec-imputation-pipeline" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-imputation-pipeline"><span class="header-section-number">2.4</span> Imputation Pipeline</h2>
<p>The diagnostic evidence from <a href="#sec-missingness-diagnostics" class="quarto-xref"><span>Section 2.3</span></a> motivates each design decision in the imputation pipeline. Missingness is station-level rather than weather-conditional (<a href="#sec-weather-conditionality" class="quarto-xref"><span>Section 2.3.4</span></a>), temporally structured with extended contiguous gaps rather than random scatter (<a href="#sec-temporal-structure" class="quarto-xref"><span>Section 2.3.2</span></a>), and co-located across variables at the station level (<a href="#sec-co-missingness" class="quarto-xref"><span>Section 2.3.1</span></a>). These properties rule out simple listwise deletion and mean imputation. They call for a pipeline that respects temporal continuity for smoothly-evolving variables, exploits cross-variable correlations for the structured variables, and declines to impute where the data is genuinely unrecoverable.</p>
<section id="stage-1-temporal-interpolation" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="stage-1-temporal-interpolation"><span class="header-section-number">2.4.1</span> Stage 1: Temporal Interpolation</h3>
<p>The eight variables with smooth day-to-day trajectories minimum and maximum temperature, morning and afternoon temperature, morning and afternoon pressure, and morning and afternoon humidity are imputed via linear interpolation grouped by location, bounded by a five-day maximum gap. The five-day cap is set directly in response to the temporal structural break finding: gaps of up to five days lie within a regime where the values at both boundaries sufficiently constrain the trajectory, while longer gaps are associated with structural collection failures that interpolation cannot safely bridge.</p>
</section>
<section id="stage-2-multivariate-imputation-via-predictive-mean-matching-and-random-forest" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="stage-2-multivariate-imputation-via-predictive-mean-matching-and-random-forest"><span class="header-section-number">2.4.2</span> Stage 2: Multivariate Imputation via Predictive Mean Matching and Random Forest</h3>
<p>Remaining gaps in <code>sunshine</code>, <code>evaporation</code>, <code>cloud9am</code>, <code>cloud3pm</code>, and the three wind direction variables are addressed using <code>mice</code> with method assignments differentiated by variable type.</p>
<p>The four continuous atmospheric variables (<code>sunshine</code>, <code>evaporation</code>, <code>cloud9am</code>, <code>cloud3pm</code>) are imputed using predictive mean matching (PMM). PMM draws imputed values from a pool of observed donor observations whose predicted values are closest to the predicted value of the missing case, rather than using the model prediction directly. This has two practical advantages over a point-prediction method for these variables. First, PMM is constrained to return values that exist in the observed data, which enforces physical bounds without requiring explicit constraints. Second, the stochastic donor draw introduces genuine between-imputation variability, which is necessary for valid Rubin’s Rules variance decomposition downstream. Each variable is imputed from a physically motivated predictor set:</p>
<ul>
<li><strong>Cloud cover</strong> (<code>cloud9am</code>, <code>cloud3pm</code>) from morning and afternoon humidity, morning pressure, location, and month.</li>
<li><strong>Sunshine</strong> from cloud cover at both observation times, maximum temperature, afternoon humidity, location, and month.</li>
<li><strong>Evaporation</strong> from wind gust speed, maximum temperature, afternoon humidity, sunshine, location, and month.</li>
</ul>
<p>The three wind direction variables (<code>wind_gust_dir</code>, <code>wind_dir9am</code>, <code>wind_dir3pm</code>) are imputed using Random Forest. Wind direction is a multi-class unordered categorical variable with sixteen compass-point levels. PMM is not appropriate for unordered factors because it imposes an implicit numeric ordering on the donor matching step. Random Forest handles the multi-class non-ordinal structure natively by splitting on class membership rather than on numeric distance. Each wind direction variable is conditioned on its temporally matched wind speed and pressure readings: gust direction from gust speed and afternoon pressure, morning direction from morning speed and morning pressure, and afternoon direction from afternoon speed and afternoon pressure. This preserves the physical coupling between concurrent wind speed and direction measurements.</p>
<p>The use of targeted predictor sets for all variables is motivated directly by the co-missingness finding in <a href="#sec-co-missingness" class="quarto-xref"><span>Section 2.3.1</span></a>. Because the four atmospheric variables tend to be absent together at the station level, their cross-variable correlations when observed are strong and reliable signals for imputation. Restricting each variable’s predictor set to physically motivated covariates exploits this structure while reducing the risk of imputing on spurious correlations introduced by including variables that carry no physical relationship to the target.</p>
</section>
<section id="ghost-sensor-flagging" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="ghost-sensor-flagging"><span class="header-section-number">2.4.3</span> Ghost Sensor Flagging</h3>
<p>Before Stage 2 runs, all station-variable pairs identified in <a href="#sec-ghost-sensor" class="quarto-xref"><span>Section 2.3.3</span></a> as ghost sensors (more than 90% missing across the full observation window) are catalogued and binary missingness flags are attached to the data (<code>sunshine_imp_flagged</code>, <code>evap_imp_flagged</code>, <code>cloud3pm_imp_flagged</code>, <code>cloud9am_imp_flagged</code>). These flags serve two purposes: they are excluded from the MICE predictor matrix so they cannot contaminate the imputation model, and they remain in the final dataset as explicit markers of which values are extrapolated with no empirical anchor at the station level. The raw date column is also excluded from the predictor matrix to prevent temporal data leakage. Neither PMM nor Random Forest has empirical support for predicting values at a station where an instrument was never present; the flags make this provenance transparent for any downstream analysis that needs to account for it.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"imputation.R"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>imp_mids <span class="ot">&lt;-</span> <span class="fu">clean_and_impute_weather</span>(df)</span>
<span id="cb12-2"><a href="#cb12-2"></a>df_final <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp_mids, <span class="at">action =</span> <span class="dv">1</span>)</span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="fu">write_csv</span>(df_final, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"df_final.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
</section>
<section id="post-imputation-dataset-properties" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="post-imputation-dataset-properties"><span class="header-section-number">2.5</span> Post-Imputation Dataset Properties</h2>
<p>The two-stage pipeline produces a dataset whose properties are each traceable to a specific finding from the diagnostic analysis in <a href="#sec-missingness-diagnostics" class="quarto-xref"><span>Section 2.3</span></a>.</p>
<p><strong>Retention without fabrication.</strong> No observations are discarded on the basis of partial missingness. The 27.9% of observations with all four target variables simultaneously absent are retained with those variables still missing, consistent with the ghost sensor finding that no empirically supportable imputation is possible for them.</p>
<p><strong>Temporal coherence.</strong> The interpolated variables maintain their within-location autocorrelation structure. The five-day cap, set in response to the temporal structural break analysis in <a href="#sec-temporal-structure" class="quarto-xref"><span>Section 2.3.2</span></a>, prevents the interpolation from extending across genuine data voids. The use of <code>rule = 1</code> in <code>na.approx</code> ensures that boundary gaps return <code>NA</code> rather than extrapolated values, which would fall outside the physically credible range of the variable and corrupt the donor pool used by PMM in Stage 2.</p>
<p><strong>Distributional fidelity.</strong> PMM draws imputed values directly from the pool of observed donor observations rather than using a model prediction. This constrains imputed values to the observed empirical range of each variable and preserves the marginal distribution, including multi-modal structure and skew, without requiring distributional assumptions.</p>
<p><strong>Physical bounds enforcement.</strong> Because PMM can only return values that exist in the observed data, imputed values for all continuous variables are guaranteed to fall within the range of the observed training set. This property eliminated the out-of-range predictions that arose when <code>rule = 2</code> extrapolation in Stage 1 produced boundary values below zero for sunshine, which then contaminated the PMM donor matching step.</p>
<p><strong>Outcome independence.</strong> The weather-conditionality test in <a href="#sec-weather-conditionality" class="quarto-xref"><span>Section 2.3.4</span></a> confirmed that sunshine missingness does not covary with rainfall amounts. Imputed sunshine values therefore do not introduce a directional bias into the training labels for the hurdle or intensity components of the downstream model.</p>
<p><strong>Wind direction coherence.</strong> Wind direction variables are imputed as unordered categorical factors using Random Forest, with each direction variable conditioned on its temporally matched speed and pressure readings. This preserves the physical coupling between concurrent wind speed and direction measurements while respecting the non-ordinal structure of compass-point categories, which PMM would handle incorrectly.</p>
<p><strong>Provenance transparency.</strong> Binary imputation flags for the four ghost-prone variables are retained in the final dataset. These flags enable downstream models or diagnostics to condition on or exclude observations where imputed values carry no empirical anchor at the station level, and they are used directly in the sensitivity analysis documented in <a href="03-sensitivity.html" class="quarto-xref"><span>Chapter 3</span></a>.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/01-intro.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/03-sensitivity.html" class="pagination-link" aria-label="Imputation Sensitivity Analysis">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputation Sensitivity Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu"># Data Preparation {#sec-data}</span></span>
<span id="cb13-2"><a href="#cb13-2"></a></span>
<span id="cb13-3"><a href="#cb13-3"></a>---</span>
<span id="cb13-4"><a href="#cb13-4"></a></span>
<span id="cb13-5"><a href="#cb13-5"></a><span class="at">&gt; **Chapter Context.** Before any statistical analysis can proceed, the raw dataset must be transformed into a form that is both analytically tractable and physically credible. This chapter documents three decisions that have downstream consequences throughout the report: the syntactic and temporal standardisation of the raw data, a diagnostic investigation of the structure and mechanism of the missingness, and the design of a two-stage imputation pipeline informed by that investigation. Each decision is motivated by the properties of the data-generating process rather than by computational convenience.</span></span>
<span id="cb13-6"><a href="#cb13-6"></a></span>
<span id="cb13-7"><a href="#cb13-7"></a>---</span>
<span id="cb13-8"><a href="#cb13-8"></a></span>
<span id="cb13-9"><a href="#cb13-9"></a><span class="fu">## Computational Environment</span></span>
<span id="cb13-10"><a href="#cb13-10"></a></span>
<span id="cb13-13"><a href="#cb13-13"></a><span class="in">```{r}</span></span>
<span id="cb13-14"><a href="#cb13-14"></a><span class="co">#| label: setup-libraries-data</span></span>
<span id="cb13-15"><a href="#cb13-15"></a><span class="co">#| echo: true</span></span>
<span id="cb13-16"><a href="#cb13-16"></a><span class="co">#| message: false</span></span>
<span id="cb13-17"><a href="#cb13-17"></a><span class="co">#| warning: false</span></span>
<span id="cb13-18"><a href="#cb13-18"></a><span class="co">#| results: 'hide'</span></span>
<span id="cb13-19"><a href="#cb13-19"></a></span>
<span id="cb13-20"><a href="#cb13-20"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"config.R"</span>))</span>
<span id="cb13-21"><a href="#cb13-21"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"utils.R"</span>))</span>
<span id="cb13-22"><a href="#cb13-22"></a></span>
<span id="cb13-23"><a href="#cb13-23"></a><span class="in">```</span></span>
<span id="cb13-24"><a href="#cb13-24"></a></span>
<span id="cb13-25"><a href="#cb13-25"></a>The package selection reflects the specific demands of meteorological data analysis. The core wrangling and visualisation toolkit (<span class="in">`tidyverse`</span>, <span class="in">`janitor`</span>, <span class="in">`kableExtra`</span>) handles routine data manipulation. The modelling stack (<span class="in">`glmmTMB`</span>, <span class="in">`DHARMa`</span>, <span class="in">`splines`</span>, <span class="in">`mgcv`</span>) is assembled for the zero-inflated mixed-effects framework documented in later chapters. The imputation stack (<span class="in">`mice`</span>) supports the Random Forest and chained imputation procedures described below. The missingness diagnostic stack (<span class="in">`naniar`</span>, <span class="in">`glue`</span>) supports the structural analysis in @sec-missingness-diagnostics. Libraries are loaded via <span class="in">`librarian`</span>, which installs missing packages automatically and ensures reproducibility across environments.</span>
<span id="cb13-26"><a href="#cb13-26"></a></span>
<span id="cb13-27"><a href="#cb13-27"></a>---</span>
<span id="cb13-28"><a href="#cb13-28"></a></span>
<span id="cb13-29"><a href="#cb13-29"></a><span class="fu">## Initial Cleaning and Standardisation</span></span>
<span id="cb13-30"><a href="#cb13-30"></a></span>
<span id="cb13-31"><a href="#cb13-31"></a>The raw dataset undergoes three transformations before any missingness analysis or imputation.</span>
<span id="cb13-32"><a href="#cb13-32"></a></span>
<span id="cb13-35"><a href="#cb13-35"></a><span class="in">```{r}</span></span>
<span id="cb13-36"><a href="#cb13-36"></a><span class="co">#| label: data-cleaning</span></span>
<span id="cb13-37"><a href="#cb13-37"></a><span class="co">#| echo: true</span></span>
<span id="cb13-38"><a href="#cb13-38"></a><span class="co">#| message: false</span></span>
<span id="cb13-39"><a href="#cb13-39"></a><span class="co">#| warning: false</span></span>
<span id="cb13-40"><a href="#cb13-40"></a></span>
<span id="cb13-41"><a href="#cb13-41"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"cleaning.R"</span>))</span>
<span id="cb13-42"><a href="#cb13-42"></a><span class="in">```</span></span>
<span id="cb13-43"><a href="#cb13-43"></a></span>
<span id="cb13-44"><a href="#cb13-44"></a>**Column standardisation.** All variable names are converted to <span class="in">`snake_case`</span> via <span class="in">`janitor::clean_names()`</span>, called at ingestion. This eliminates downstream ambiguity in variable references and ensures internal consistency across all chapters.</span>
<span id="cb13-45"><a href="#cb13-45"></a></span>
<span id="cb13-46"><a href="#cb13-46"></a>**Temporal feature extraction.** The <span class="in">`date`</span> column is typed as a <span class="in">`Date`</span> object and two derived features are extracted: <span class="in">`month`</span> (as a factor) and <span class="in">`day`</span> (day of week, labelled). Month captures the seasonal structure of Australian precipitation; day of week is retained as a potential control variable for reporting artefacts in the raw data.</span>
<span id="cb13-47"><a href="#cb13-47"></a></span>
<span id="cb13-48"><a href="#cb13-48"></a>**Target filtering.** Observations where <span class="in">`rainfall`</span> is missing are removed. Records without a ground-truth rainfall measurement have no supervised learning value and cannot contribute to either the hurdle or the intensity component of the ZIG model.</span>
<span id="cb13-49"><a href="#cb13-49"></a></span>
<span id="cb13-50"><a href="#cb13-50"></a>---</span>
<span id="cb13-51"><a href="#cb13-51"></a></span>
<span id="cb13-52"><a href="#cb13-52"></a><span class="fu">## Missingness Diagnostics {#sec-missingness-diagnostics}</span></span>
<span id="cb13-53"><a href="#cb13-53"></a></span>
<span id="cb13-54"><a href="#cb13-54"></a>Before designing an imputation strategy, it is necessary to understand the mechanism and structure of the missing data. The choice between imputation methods depends critically on three questions: whether missingness is random with respect to other variables in the dataset, whether missing values cluster at specific locations or time periods, and whether the four most-affected variables fail independently or as a coordinated group. A strategy designed without answering these questions risks either under-imputing (discarding recoverable signal) or over-imputing (fabricating data in regions where recovery is not possible). The five analyses below provide the empirical basis for each design decision in the pipeline that follows.</span>
<span id="cb13-55"><a href="#cb13-55"></a></span>
<span id="cb13-56"><a href="#cb13-56"></a><span class="fu">### Co-missingness Structure {#sec-co-missingness}</span></span>
<span id="cb13-57"><a href="#cb13-57"></a></span>
<span id="cb13-60"><a href="#cb13-60"></a><span class="in">```{r}</span></span>
<span id="cb13-61"><a href="#cb13-61"></a><span class="co">#| label: tbl-co-missingness</span></span>
<span id="cb13-62"><a href="#cb13-62"></a><span class="co">#| tbl-cap: "Conditional Co-missingness Matrix"</span></span>
<span id="cb13-63"><a href="#cb13-63"></a><span class="co">#| echo: true</span></span>
<span id="cb13-64"><a href="#cb13-64"></a><span class="co">#| message: false</span></span>
<span id="cb13-65"><a href="#cb13-65"></a><span class="co">#| warning: false</span></span>
<span id="cb13-66"><a href="#cb13-66"></a></span>
<span id="cb13-67"><a href="#cb13-67"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"data_missingness.R"</span>))</span>
<span id="cb13-68"><a href="#cb13-68"></a><span class="fu">render_comissingness_table</span>()</span>
<span id="cb13-69"><a href="#cb13-69"></a><span class="in">```</span></span>
<span id="cb13-70"><a href="#cb13-70"></a></span>
<span id="cb13-71"><a href="#cb13-71"></a>The co-missingness matrix (@tbl-co-missingness) confirms that these four variables fail as a systematic cluster rather than independently. The dependencies are strongest between instrumental pairs: if evaporation is missing, there is a 93.2% probability that sunshine is also missing. Even the weakest relationship in the matrix (sunshine to cloud9am) retains a rate of 67.5%, which is nearly double what would be expected under random failure.</span>
<span id="cb13-72"><a href="#cb13-72"></a></span>
<span id="cb13-73"><a href="#cb13-73"></a>Under MCAR, the co-missing rates would be close to the marginal missingness rates of each variable, roughly 40 to 48%. Rates uniformly between 67% and 93% instead indicate a shared upstream cause: the instrumentation profile of each station. Sunshine recorders, evaporation pans, and cloud coverage sensors are deployed as a package, not individually. A station without one is very likely to lack the others. This is MNAR at the station level. The practical consequence for imputation is that treating the four variables as independently missing would be incorrect: their correlations when observed are available precisely because they fail together, and a multivariate imputation method that exploits those cross-variable relationships will outperform four separate univariate models.</span>
<span id="cb13-74"><a href="#cb13-74"></a></span>
<span id="cb13-75"><a href="#cb13-75"></a><span class="fu">### Temporal Structure and Structural Breaks {#sec-temporal-structure}</span></span>
<span id="cb13-76"><a href="#cb13-76"></a></span>
<span id="cb13-79"><a href="#cb13-79"></a><span class="in">```{r}</span></span>
<span id="cb13-80"><a href="#cb13-80"></a><span class="co">#| label: fig-temporal-missingness</span></span>
<span id="cb13-81"><a href="#cb13-81"></a><span class="co">#| fig-cap: "Timeline of systematic missingness across the four high-missingness variables. The stepped increases visible particularly in sunshine and evaporation indicate structural breaks in data collection rather than random sensor failures."</span></span>
<span id="cb13-82"><a href="#cb13-82"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb13-83"><a href="#cb13-83"></a><span class="co">#| fig-height: 7</span></span>
<span id="cb13-84"><a href="#cb13-84"></a><span class="co">#| echo: true</span></span>
<span id="cb13-85"><a href="#cb13-85"></a><span class="co">#| warning: false</span></span>
<span id="cb13-86"><a href="#cb13-86"></a></span>
<span id="cb13-87"><a href="#cb13-87"></a><span class="fu">plot_temporal_missingness</span>()</span>
<span id="cb13-88"><a href="#cb13-88"></a><span class="in">```</span></span>
<span id="cb13-89"><a href="#cb13-89"></a></span>
<span id="cb13-90"><a href="#cb13-90"></a>The temporal analysis (@fig-temporal-missingness) confirms that missingness is not randomly distributed over time. The cloud cover variables maintain a roughly stable and high missingness rate across the observation window, consistent with a fixed set of stations never having recorded these measurements. The <span class="in">`sunshine`</span> and <span class="in">`evaporation`</span> variables show a distinct stepped pattern: missingness rises at specific breakpoints rather than fluctuating randomly, indicating that certain stations were decommissioned or that recording protocols changed at identifiable calendar dates.</span>
<span id="cb13-91"><a href="#cb13-91"></a></span>
<span id="cb13-92"><a href="#cb13-92"></a>This temporal structure has a direct implication for the interpolation stage of the pipeline. Linear interpolation is appropriate when a smooth trajectory can be inferred from values on either side of a gap. Extended contiguous gaps produced by a structural break have no valid upper boundary from which to interpolate, and filling them with temporal interpolation would create long synthetic sequences with no empirical anchor. The five-day interpolation cap set in Stage 1 of the pipeline is a direct response to this finding.</span>
<span id="cb13-93"><a href="#cb13-93"></a></span>
<span id="cb13-94"><a href="#cb13-94"></a><span class="fu">### Geographic Concentration: Ghost Sensor Identification {#sec-ghost-sensor}</span></span>
<span id="cb13-95"><a href="#cb13-95"></a></span>
<span id="cb13-98"><a href="#cb13-98"></a><span class="in">```{r}</span></span>
<span id="cb13-99"><a href="#cb13-99"></a><span class="co">#| label: ghost-sensors</span></span>
<span id="cb13-100"><a href="#cb13-100"></a><span class="co">#| echo: true</span></span>
<span id="cb13-101"><a href="#cb13-101"></a><span class="co">#| message: false</span></span>
<span id="cb13-102"><a href="#cb13-102"></a><span class="co">#| warning: false</span></span>
<span id="cb13-103"><a href="#cb13-103"></a></span>
<span id="cb13-104"><a href="#cb13-104"></a><span class="fu">render_ghost_sensor_table</span>()</span>
<span id="cb13-105"><a href="#cb13-105"></a><span class="in">```</span></span>
<span id="cb13-106"><a href="#cb13-106"></a></span>
<span id="cb13-107"><a href="#cb13-107"></a>The location-level analysis identifies the specific station-variable pairs responsible for the bulk of the aggregate missingness. The top ten instances from the script output, all at exactly 100% missing, are as follows: Albury (<span class="in">`evaporation`</span>, 3,040 observations; <span class="in">`sunshine`</span>, 3,040), BadgerysCreek (<span class="in">`evaporation`</span>, 3,009; <span class="in">`sunshine`</span>, 3,009; <span class="in">`cloud9am`</span>, 3,009; <span class="in">`cloud3pm`</span>, 3,009), Newcastle (<span class="in">`evaporation`</span>, 3,039; <span class="in">`sunshine`</span>, 3,039), and NorahHead (<span class="in">`evaporation`</span>, 3,004; <span class="in">`sunshine`</span>, 3,004). At these stations, the instrument in question recorded a value on zero days across the entire observation window. These are not sensors experiencing intermittent failure; they are sensors that were never present or that were removed before the data collection period began.</span>
<span id="cb13-108"><a href="#cb13-108"></a></span>
<span id="cb13-109"><a href="#cb13-109"></a>The distinction between ghost sensors and ordinary missingness is consequential for imputation. For a gap of five to fifteen consecutive missing days, a Random Forest model can generate reasonable predictions by drawing on correlated variables at the same station and the same variable at nearby stations. For a gap spanning 3,000 or more consecutive observations, this extrapolation has no empirical support whatsoever: there is no observed value at that station and variable combination to anchor or validate the prediction. Values produced for these pairs would be statistically plausible by construction but would carry no physical information about what the instrument would have actually recorded. Ghost sensor pairs are identified before Stage 2 runs and flagged so that their imputed values can be treated with appropriate scepticism in downstream analysis.</span>
<span id="cb13-110"><a href="#cb13-110"></a></span>
<span id="cb13-111"><a href="#cb13-111"></a><span class="fu">### Weather-Conditionality of Sunshine Missingness {#sec-weather-conditionality}</span></span>
<span id="cb13-112"><a href="#cb13-112"></a></span>
<span id="cb13-115"><a href="#cb13-115"></a><span class="in">```{r}</span></span>
<span id="cb13-116"><a href="#cb13-116"></a><span class="co">#| label: tbl-sunshine-mcar-test</span></span>
<span id="cb13-117"><a href="#cb13-117"></a><span class="co">#| echo: true</span></span>
<span id="cb13-118"><a href="#cb13-118"></a><span class="co">#| message: false</span></span>
<span id="cb13-119"><a href="#cb13-119"></a><span class="co">#| warning: false</span></span>
<span id="cb13-120"><a href="#cb13-120"></a></span>
<span id="cb13-121"><a href="#cb13-121"></a><span class="fu">render_sunshine_mcar_table</span>()</span>
<span id="cb13-122"><a href="#cb13-122"></a><span class="in">```</span></span>
<span id="cb13-123"><a href="#cb13-123"></a></span>
<span id="cb13-126"><a href="#cb13-126"></a><span class="in">```{r}</span></span>
<span id="cb13-127"><a href="#cb13-127"></a><span class="co">#| label: fig-sunshine-rainfall-density</span></span>
<span id="cb13-128"><a href="#cb13-128"></a><span class="co">#| fig-cap: "Density of rainfall amounts on days where sunshine data is present versus missing. The near-identical distributions confirm that sunshine missingness is not weather-conditional: the same stations are missing sunshine on both dry and rainy days because the instrument was simply not installed, not because it failed during precipitation events."</span></span>
<span id="cb13-129"><a href="#cb13-129"></a><span class="co">#| fig-width: 9</span></span>
<span id="cb13-130"><a href="#cb13-130"></a><span class="co">#| fig-height: 6</span></span>
<span id="cb13-131"><a href="#cb13-131"></a><span class="co">#| echo: true</span></span>
<span id="cb13-132"><a href="#cb13-132"></a><span class="co">#| warning: false</span></span>
<span id="cb13-133"><a href="#cb13-133"></a></span>
<span id="cb13-134"><a href="#cb13-134"></a><span class="fu">plot_sunshine_rainfall_density</span>()</span>
<span id="cb13-135"><a href="#cb13-135"></a><span class="in">```</span></span>
<span id="cb13-136"><a href="#cb13-136"></a></span>
<span id="cb13-137"><a href="#cb13-137"></a>A specific concern when imputing a predictor variable is outcome-related missingness: if sunshine sensors failed more often on rainy days, then the imputed values would carry a directional signal about the target variable and could introduce bias into the training data.</span>
<span id="cb13-138"><a href="#cb13-138"></a></span>
<span id="cb13-139"><a href="#cb13-139"></a>The empirical test refutes this concern. The table output (@tbl-sunshine-mcar-test) reports a sunshine missing rate of 47.8% on 110,319 dry days (rainfall at most 1 mm) and 47.2% on 31,880 rainy days (rainfall above 1 mm), a difference of 0.6 percentage points. The density plot (@fig-sunshine-rainfall-density) makes the same point visually: the distribution of rainfall amounts on days with missing sunshine and on days with present sunshine are indistinguishable across the full range from 0 to 50 mm. The slight visual offset in the figure reflects not a systematic pattern but the difference in the sizes of the two groups.</span>
<span id="cb13-140"><a href="#cb13-140"></a></span>
<span id="cb13-141"><a href="#cb13-141"></a>Sunshine missingness is station-conditional rather than weather-conditional. The same stations record missing sunshine on both dry and rainy days at nearly identical rates, because the instrument is absent from those stations entirely. This finding clears the imputation path: there is no outcome-related confound to correct for.</span>
<span id="cb13-142"><a href="#cb13-142"></a></span>
<span id="cb13-143"><a href="#cb13-143"></a><span class="fu">### Missing Pattern Structure</span></span>
<span id="cb13-144"><a href="#cb13-144"></a></span>
<span id="cb13-147"><a href="#cb13-147"></a><span class="in">```{r}</span></span>
<span id="cb13-148"><a href="#cb13-148"></a><span class="co">#| label: miss-pattern-table</span></span>
<span id="cb13-149"><a href="#cb13-149"></a><span class="co">#| echo: true</span></span>
<span id="cb13-150"><a href="#cb13-150"></a><span class="co">#| message: false</span></span>
<span id="cb13-151"><a href="#cb13-151"></a><span class="co">#| warning: false</span></span>
<span id="cb13-152"><a href="#cb13-152"></a></span>
<span id="cb13-153"><a href="#cb13-153"></a><span class="fu">render_miss_pattern_table</span>()</span>
<span id="cb13-154"><a href="#cb13-154"></a><span class="in">```</span></span>
<span id="cb13-155"><a href="#cb13-155"></a></span>
<span id="cb13-156"><a href="#cb13-156"></a>The case-level output from the script reveals a strongly bimodal structure across five distinct patterns. Of all observations: 62,566 (43.0%) have none of the four variables missing; 10,525 (7.2%) have exactly one missing; 20,376 (14.0%) have exactly two missing; 11,378 (7.8%) have exactly three missing; and 40,615 (27.9%) have all four missing simultaneously. The two endpoint categories, zero missing and all four missing, together account for 70.9% of all observations.</span>
<span id="cb13-157"><a href="#cb13-157"></a></span>
<span id="cb13-158"><a href="#cb13-158"></a>The 27.9% with complete simultaneous missingness corresponds directly to the ghost sensor stations identified in @sec-ghost-sensor. For these observations, no imputation is supportable and the values remain missing after the pipeline. The 43.0% with no missingness require no intervention. The substantive imputation work is concentrated in the remaining 29.1% across the three intermediate patterns, where partial instrumentation means that correlated predictors are available to inform the Random Forest estimates. The bimodal structure also confirms that the co-missingness finding is not a statistical artifact: observations genuinely tend to be fully instrumented or minimally instrumented, not randomly partially instrumented.</span>
<span id="cb13-159"><a href="#cb13-159"></a></span>
<span id="cb13-160"><a href="#cb13-160"></a>---</span>
<span id="cb13-161"><a href="#cb13-161"></a></span>
<span id="cb13-162"><a href="#cb13-162"></a><span class="fu">## Imputation Pipeline {#sec-imputation-pipeline}</span></span>
<span id="cb13-163"><a href="#cb13-163"></a></span>
<span id="cb13-164"><a href="#cb13-164"></a>The diagnostic evidence from @sec-missingness-diagnostics motivates each design decision in the imputation pipeline. Missingness is station-level rather than weather-conditional (@sec-weather-conditionality), temporally structured with extended contiguous gaps rather than random scatter (@sec-temporal-structure), and co-located across variables at the station level (@sec-co-missingness). These properties rule out simple listwise deletion and mean imputation. They call for a pipeline that respects temporal continuity for smoothly-evolving variables, exploits cross-variable correlations for the structured variables, and declines to impute where the data is genuinely unrecoverable.</span>
<span id="cb13-165"><a href="#cb13-165"></a></span>
<span id="cb13-166"><a href="#cb13-166"></a><span class="fu">### Stage 1: Temporal Interpolation</span></span>
<span id="cb13-167"><a href="#cb13-167"></a></span>
<span id="cb13-168"><a href="#cb13-168"></a>The eight variables with smooth day-to-day trajectories minimum and maximum temperature, morning and afternoon temperature, morning and afternoon pressure, and morning and afternoon humidity are imputed via linear interpolation grouped by location, bounded by a five-day maximum gap. The five-day cap is set directly in response to the temporal structural break finding: gaps of up to five days lie within a regime where the values at both boundaries sufficiently constrain the trajectory, while longer gaps are associated with structural collection failures that interpolation cannot safely bridge.</span>
<span id="cb13-169"><a href="#cb13-169"></a></span>
<span id="cb13-170"><a href="#cb13-170"></a><span class="fu">### Stage 2: Multivariate Imputation via Predictive Mean Matching and Random Forest</span></span>
<span id="cb13-171"><a href="#cb13-171"></a></span>
<span id="cb13-172"><a href="#cb13-172"></a>Remaining gaps in <span class="in">`sunshine`</span>, <span class="in">`evaporation`</span>, <span class="in">`cloud9am`</span>, <span class="in">`cloud3pm`</span>, and the three wind direction variables are addressed using <span class="in">`mice`</span> with method assignments differentiated by variable type.</span>
<span id="cb13-173"><a href="#cb13-173"></a></span>
<span id="cb13-174"><a href="#cb13-174"></a>The four continuous atmospheric variables (<span class="in">`sunshine`</span>, <span class="in">`evaporation`</span>, <span class="in">`cloud9am`</span>, <span class="in">`cloud3pm`</span>) are imputed using predictive mean matching (PMM). PMM draws imputed values from a pool of observed donor observations whose predicted values are closest to the predicted value of the missing case, rather than using the model prediction directly. This has two practical advantages over a point-prediction method for these variables. First, PMM is constrained to return values that exist in the observed data, which enforces physical bounds without requiring explicit constraints. Second, the stochastic donor draw introduces genuine between-imputation variability, which is necessary for valid Rubin's Rules variance decomposition downstream. Each variable is imputed from a physically motivated predictor set:</span>
<span id="cb13-175"><a href="#cb13-175"></a></span>
<span id="cb13-176"><a href="#cb13-176"></a><span class="ss">- </span>**Cloud cover** (<span class="in">`cloud9am`</span>, <span class="in">`cloud3pm`</span>) from morning and afternoon humidity, morning pressure, location, and month.</span>
<span id="cb13-177"><a href="#cb13-177"></a><span class="ss">- </span>**Sunshine** from cloud cover at both observation times, maximum temperature, afternoon humidity, location, and month.</span>
<span id="cb13-178"><a href="#cb13-178"></a><span class="ss">- </span>**Evaporation** from wind gust speed, maximum temperature, afternoon humidity, sunshine, location, and month.</span>
<span id="cb13-179"><a href="#cb13-179"></a></span>
<span id="cb13-180"><a href="#cb13-180"></a>The three wind direction variables (<span class="in">`wind_gust_dir`</span>, <span class="in">`wind_dir9am`</span>, <span class="in">`wind_dir3pm`</span>) are imputed using Random Forest. Wind direction is a multi-class unordered categorical variable with sixteen compass-point levels. PMM is not appropriate for unordered factors because it imposes an implicit numeric ordering on the donor matching step. Random Forest handles the multi-class non-ordinal structure natively by splitting on class membership rather than on numeric distance. Each wind direction variable is conditioned on its temporally matched wind speed and pressure readings: gust direction from gust speed and afternoon pressure, morning direction from morning speed and morning pressure, and afternoon direction from afternoon speed and afternoon pressure. This preserves the physical coupling between concurrent wind speed and direction measurements.</span>
<span id="cb13-181"><a href="#cb13-181"></a></span>
<span id="cb13-182"><a href="#cb13-182"></a>The use of targeted predictor sets for all variables is motivated directly by the co-missingness finding in @sec-co-missingness. Because the four atmospheric variables tend to be absent together at the station level, their cross-variable correlations when observed are strong and reliable signals for imputation. Restricting each variable's predictor set to physically motivated covariates exploits this structure while reducing the risk of imputing on spurious correlations introduced by including variables that carry no physical relationship to the target.</span>
<span id="cb13-183"><a href="#cb13-183"></a></span>
<span id="cb13-184"><a href="#cb13-184"></a><span class="fu">### Ghost Sensor Flagging</span></span>
<span id="cb13-185"><a href="#cb13-185"></a></span>
<span id="cb13-186"><a href="#cb13-186"></a>Before Stage 2 runs, all station-variable pairs identified in @sec-ghost-sensor as ghost sensors (more than 90% missing across the full observation window) are catalogued and binary missingness flags are attached to the data (<span class="in">`sunshine_imp_flagged`</span>, <span class="in">`evap_imp_flagged`</span>, <span class="in">`cloud3pm_imp_flagged`</span>, <span class="in">`cloud9am_imp_flagged`</span>). These flags serve two purposes: they are excluded from the MICE predictor matrix so they cannot contaminate the imputation model, and they remain in the final dataset as explicit markers of which values are extrapolated with no empirical anchor at the station level. The raw date column is also excluded from the predictor matrix to prevent temporal data leakage. Neither PMM nor Random Forest has empirical support for predicting values at a station where an instrument was never present; the flags make this provenance transparent for any downstream analysis that needs to account for it.</span>
<span id="cb13-187"><a href="#cb13-187"></a></span>
<span id="cb13-190"><a href="#cb13-190"></a><span class="in">```{r}</span></span>
<span id="cb13-191"><a href="#cb13-191"></a><span class="co">#| label: imputation-strategy</span></span>
<span id="cb13-192"><a href="#cb13-192"></a><span class="co">#| echo: true</span></span>
<span id="cb13-193"><a href="#cb13-193"></a><span class="co">#| eval: false</span></span>
<span id="cb13-194"><a href="#cb13-194"></a></span>
<span id="cb13-195"><a href="#cb13-195"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter2"</span>, <span class="st">"imputation.R"</span>))</span>
<span id="cb13-196"><a href="#cb13-196"></a><span class="in">```</span></span>
<span id="cb13-197"><a href="#cb13-197"></a></span>
<span id="cb13-200"><a href="#cb13-200"></a><span class="in">```{r}</span></span>
<span id="cb13-201"><a href="#cb13-201"></a><span class="co">#| label: clean-and-save-imputed</span></span>
<span id="cb13-202"><a href="#cb13-202"></a><span class="co">#| message: false</span></span>
<span id="cb13-203"><a href="#cb13-203"></a><span class="co">#| warning: false</span></span>
<span id="cb13-204"><a href="#cb13-204"></a><span class="co">#| eval: false</span></span>
<span id="cb13-205"><a href="#cb13-205"></a></span>
<span id="cb13-206"><a href="#cb13-206"></a>imp_mids <span class="ot">&lt;-</span> <span class="fu">clean_and_impute_weather</span>(df)</span>
<span id="cb13-207"><a href="#cb13-207"></a>df_final <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp_mids, <span class="at">action =</span> <span class="dv">1</span>)</span>
<span id="cb13-208"><a href="#cb13-208"></a><span class="fu">write_csv</span>(df_final, here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"df_final.csv"</span>))</span>
<span id="cb13-209"><a href="#cb13-209"></a></span>
<span id="cb13-210"><a href="#cb13-210"></a><span class="in">```</span></span>
<span id="cb13-211"><a href="#cb13-211"></a></span>
<span id="cb13-214"><a href="#cb13-214"></a><span class="in">```{r}</span></span>
<span id="cb13-215"><a href="#cb13-215"></a><span class="co">#| label: load-imputed-data</span></span>
<span id="cb13-216"><a href="#cb13-216"></a><span class="co">#| echo: false</span></span>
<span id="cb13-217"><a href="#cb13-217"></a><span class="co">#| message: false</span></span>
<span id="cb13-218"><a href="#cb13-218"></a><span class="co">#| warning: false</span></span>
<span id="cb13-219"><a href="#cb13-219"></a></span>
<span id="cb13-220"><a href="#cb13-220"></a>df_final <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"df_final.csv"</span>))</span>
<span id="cb13-221"><a href="#cb13-221"></a><span class="in">```</span></span>
<span id="cb13-222"><a href="#cb13-222"></a></span>
<span id="cb13-223"><a href="#cb13-223"></a>---</span>
<span id="cb13-224"><a href="#cb13-224"></a></span>
<span id="cb13-225"><a href="#cb13-225"></a><span class="fu">## Post-Imputation Dataset Properties</span></span>
<span id="cb13-226"><a href="#cb13-226"></a></span>
<span id="cb13-227"><a href="#cb13-227"></a>The two-stage pipeline produces a dataset whose properties are each traceable to a specific finding from the diagnostic analysis in @sec-missingness-diagnostics.</span>
<span id="cb13-228"><a href="#cb13-228"></a></span>
<span id="cb13-229"><a href="#cb13-229"></a>**Retention without fabrication.** No observations are discarded on the basis of partial missingness. The 27.9% of observations with all four target variables simultaneously absent are retained with those variables still missing, consistent with the ghost sensor finding that no empirically supportable imputation is possible for them.</span>
<span id="cb13-230"><a href="#cb13-230"></a></span>
<span id="cb13-231"><a href="#cb13-231"></a>**Temporal coherence.** The interpolated variables maintain their within-location autocorrelation structure. The five-day cap, set in response to the temporal structural break analysis in @sec-temporal-structure, prevents the interpolation from extending across genuine data voids. The use of <span class="in">`rule = 1`</span> in <span class="in">`na.approx`</span> ensures that boundary gaps return <span class="in">`NA`</span> rather than extrapolated values, which would fall outside the physically credible range of the variable and corrupt the donor pool used by PMM in Stage 2.</span>
<span id="cb13-232"><a href="#cb13-232"></a></span>
<span id="cb13-233"><a href="#cb13-233"></a>**Distributional fidelity.** PMM draws imputed values directly from the pool of observed donor observations rather than using a model prediction. This constrains imputed values to the observed empirical range of each variable and preserves the marginal distribution, including multi-modal structure and skew, without requiring distributional assumptions.</span>
<span id="cb13-234"><a href="#cb13-234"></a></span>
<span id="cb13-235"><a href="#cb13-235"></a>**Physical bounds enforcement.** Because PMM can only return values that exist in the observed data, imputed values for all continuous variables are guaranteed to fall within the range of the observed training set. This property eliminated the out-of-range predictions that arose when <span class="in">`rule = 2`</span> extrapolation in Stage 1 produced boundary values below zero for sunshine, which then contaminated the PMM donor matching step.</span>
<span id="cb13-236"><a href="#cb13-236"></a></span>
<span id="cb13-237"><a href="#cb13-237"></a>**Outcome independence.** The weather-conditionality test in @sec-weather-conditionality confirmed that sunshine missingness does not covary with rainfall amounts. Imputed sunshine values therefore do not introduce a directional bias into the training labels for the hurdle or intensity components of the downstream model.</span>
<span id="cb13-238"><a href="#cb13-238"></a></span>
<span id="cb13-239"><a href="#cb13-239"></a>**Wind direction coherence.** Wind direction variables are imputed as unordered categorical factors using Random Forest, with each direction variable conditioned on its temporally matched speed and pressure readings. This preserves the physical coupling between concurrent wind speed and direction measurements while respecting the non-ordinal structure of compass-point categories, which PMM would handle incorrectly.</span>
<span id="cb13-240"><a href="#cb13-240"></a></span>
<span id="cb13-241"><a href="#cb13-241"></a>**Provenance transparency.** Binary imputation flags for the four ghost-prone variables are retained in the final dataset. These flags enable downstream models or diagnostics to condition on or exclude observations where imputed values carry no empirical anchor at the station level, and they are used directly in the sensitivity analysis documented in @sec-sensitivity.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/02-data-prep.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>