<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An in-depth statistical analysis of rainfall patterns across 49 Australian cities using Zero-Inflated Gamma GLMMs.">

<title>7&nbsp; Model Evaluation – Australian Rainfall Dynamics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/08-model-selection.html" rel="next">
<link href="../chapters/06-modeling.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-e66b50aa4120364bfa72329fe8653b98.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-463e05341c278a50bd9d8b9e5c352418.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="../site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="../site_libs/datatables-binding-0.34.0/datatables.js"></script>
<script src="../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-modeling.html">Modelling</a></li><li class="breadcrumb-item"><a href="../chapters/07-evaluation.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Australian Rainfall Dynamics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting Australian Rainfall: A Hierarchical Zero-Inflated Gamma Framework</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-data-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputation Sensitivity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature Engineering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-evaluation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-classification" id="toc-sec-classification" class="nav-link active" data-scroll-target="#sec-classification"><span class="header-section-number">7.1</span> Classification Performance of the Occurrence Submodel</a></li>
  <li><a href="#sec-random-effects" id="toc-sec-random-effects" class="nav-link" data-scroll-target="#sec-random-effects"><span class="header-section-number">7.2</span> Spatial Heterogeneity and Random Effects</a></li>
  <li><a href="#sec-dharma" id="toc-sec-dharma" class="nav-link" data-scroll-target="#sec-dharma"><span class="header-section-number">7.3</span> Residual Diagnostics via DHARMa Simulation</a></li>
  <li><a href="#sec-autocorrelation" id="toc-sec-autocorrelation" class="nav-link" data-scroll-target="#sec-autocorrelation"><span class="header-section-number">7.4</span> Temporal Autocorrelation in Residuals</a></li>
  <li><a href="#sec-eval-summary" id="toc-sec-eval-summary" class="nav-link" data-scroll-target="#sec-eval-summary"><span class="header-section-number">7.5</span> Summary of Validation Results</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/07-evaluation.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-modeling.html">Modelling</a></li><li class="breadcrumb-item"><a href="../chapters/07-evaluation.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-evaluation" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<blockquote class="blockquote">
<p><strong>Chapter Context.</strong> A model that fits training data well is not necessarily a model that is correct. This chapter subjects the final mixed-effects ZIG model (M6) to four distinct validation procedures, each targeting a different potential failure mode: poor discriminative ability in the occurrence submodel, spatially inappropriate parameter homogeneity, distributional misspecification in the residuals, and unabsorbed temporal autocorrelation. Together, these tests form a coherent audit of the model’s assumptions and capabilities.</p>
</blockquote>
<hr>
<section id="sec-classification" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-classification"><span class="header-section-number">7.1</span> Classification Performance of the Occurrence Submodel</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">plot_roc</span>(preds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-roc-curve" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-roc-curve-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roc-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: ROC curve for rainfall occurrence prediction. AUC = 0.813 indicates strong discriminative ability in separating dry days from wet days.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">plot_confusion_matrix</span>(preds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-confusion-matrix" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-confusion-matrix-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Confusion matrix at the Youden-optimal threshold (0.6246)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">render_brier_scores</span>(preds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; Brier Score:  0.1654 
#&gt; Brier Skill Score: 0.2819</code></pre>
</div>
</div>
<p>Although the ZIG model is primarily a framework for predicting rainfall amount, its zero-inflation component constitutes a binary classifier at each observation: it assigns a probability that the day is structurally dry. Evaluating this component as a classifier allows direct assessment of how well the model separates the two fundamentally different weather states identified in <a href="04-eda.html" class="quarto-xref"><span>Chapter 4</span></a>.</p>
<p><strong>Discriminative ability.</strong> The area under the ROC curve is 0.813 (<a href="#fig-roc-curve" class="quarto-xref">Figure&nbsp;<span>7.1</span></a>), meaning that in 81.3% of randomly drawn pairs consisting of one genuinely dry day and one genuinely wet day, the model correctly assigns the higher dryness probability to the dry day. This threshold-free measure of separation indicates strong discriminative performance for a meteorological classification problem of this complexity.</p>
<p><strong>Threshold selection.</strong> The raw zero-inflation probability must be converted to a binary prediction through a threshold. Youden’s J statistic, which maximises the sum of sensitivity and specificity simultaneously, selects an optimal threshold of 0.6246. This is notably higher than the naive 0.5 default because dry days constitute 64% of the sample: the model’s calibrated prior assigns moderate dryness probability to many observations by default, and a higher threshold requires more decisive evidence before predicting “No Rain.”</p>
<p><strong>Confusion matrix.</strong> At this threshold, the model produces 68,074 correct dry-day predictions (true negatives), 36,662 correct rain predictions (true positives), 22,764 false alarms (predicted dry, actually wet), and 14,356 missed rain events (predicted wet, actually dry) (<a href="#fig-confusion-matrix" class="quarto-xref">Figure&nbsp;<span>7.2</span></a>). The model generates false alarms at roughly twice the rate at which it misses rain events. In a meteorological context this asymmetry is operationally desirable: the consequence of carrying an umbrella on a dry day is trivial compared to the consequence of being unprepared for a significant rainfall event.</p>
<p>The Brier Score is 0.1654 and the Brier Skill Score is 0.2819, indicating meaningful improvement over a climatological reference forecast.</p>
<hr>
</section>
<section id="sec-random-effects" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-random-effects"><span class="header-section-number">7.2</span> Spatial Heterogeneity and Random Effects</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_random_effects.R"</span>))</span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">plot_location_effects</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-location-effects" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-location-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-location-effects-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-location-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.3: Location-specific baseline rainfall adjustments (random intercepts). Cities to the right of the dashed line produce systematically more rainfall than the national average when all dynamic weather variables are held constant; cities to the left produce systematically less.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The random intercepts represent the location-specific baseline deviations in rainfall intensity after removing the contribution of all dynamic weather variables humidity, pressure, wind, seasonality, and persistence (<a href="#fig-location-effects" class="quarto-xref">Figure&nbsp;<span>7.3</span></a>). What remains is the component of rainfall attributable to geographic and climatic factors that do not vary day-to-day: proximity to moisture sources, orographic effects, predominant circulation patterns, and regional climate regime.</p>
<p><strong>The wetter locations.</strong> Katherine (<span class="math inline">\(\hat{b} = 0.59\)</span>, <span class="math inline">\(e^{0.59} \approx 1.80\)</span>) and Tuggeranong (<span class="math inline">\(\hat{b} = 0.52\)</span>, <span class="math inline">\(e^{0.52} \approx 1.68\)</span>) sit at the high end of the distribution, producing roughly 68% and 80% more rainfall respectively than a hypothetical average Australian location experiencing identical instantaneous weather conditions. Katherine’s elevated baseline is geographically coherent: it sits in the tropical Top End of the Northern Territory, where monsoonal systems deliver sustained and intense rainfall with no structural analogue in the temperate south. Tuggeranong is located in the Australian Capital Territory near Canberra, where its elevated baseline reflects orographic enhancement from the surrounding Brindabella Ranges and exposure to moisture-bearing easterly flows that the dynamic predictors do not fully represent on a day-to-day basis.</p>
<p><strong>The drier locations.</strong> Nhil (<span class="math inline">\(\hat{b} = -0.69\)</span>, <span class="math inline">\(e^{-0.69} \approx 0.50\)</span>) and Norfolk Island (<span class="math inline">\(\hat{b} = -0.76\)</span>, <span class="math inline">\(e^{-0.76} \approx 0.47\)</span>) show the strongest negative adjustments. Nhil produces roughly half the rainfall of an average location given identical weather conditions, reflecting its position in the semi-arid Wimmera region of inland Victoria where even moisture-laden air masses tend to deliver less precipitation than they would at the coast.</p>
<p><strong>Justification for the mixed-effects structure.</strong> The magnitude and geographic coherence of these deviations confirm the necessity of the random effects component. A pooled fixed-effects model would suppress this spatial variation, producing coefficients that systematically over-predict rainfall in arid interior stations and under-predict it in high-rainfall locations. The mixed-effects structure allows the global physical relationships humidity drives intensity, southerly winds bring moisture to remain stable as fixed effects while accommodating the geographically variable baseline against which they operate.</p>
<hr>
</section>
<section id="sec-dharma" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-dharma"><span class="header-section-number">7.3</span> Residual Diagnostics via DHARMa Simulation</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_diagnostics.R"</span>))</span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">run_dharma_diagnostics</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-dharma-diagnostics-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dharma-diagnostics-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-dharma-diagnostics-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dharma-diagnostics-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.4: DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs.&nbsp;predicted values.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-dharma-diagnostics-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dharma-diagnostics-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-dharma-diagnostics-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dharma-diagnostics-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.5: DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs.&nbsp;predicted values.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-dharma-diagnostics-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dharma-diagnostics-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-evaluation_files/figure-html/fig-dharma-diagnostics-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dharma-diagnostics-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.6: DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs.&nbsp;predicted values.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Standard residual diagnostics are not directly applicable to Zero-Inflated Gamma models: the mixture of a point mass at zero and a continuous positive distribution means that conventional Pearson or deviance residuals do not have a tractable reference distribution. DHARMa addresses this by generating a large number of simulated datasets from the fitted model and computing, for each observation, where the actual value falls in the empirical distribution of simulated values. Under a correctly specified model, these scaled residuals follow a uniform distribution on <span class="math inline">\([0, 1]\)</span> regardless of the model family. Deviations from uniformity indicate misspecification.</p>
<p><strong>Q-Q plot.</strong> The empirical quantiles of the scaled residuals align closely with the theoretical diagonal across the full range of the distribution. The Kolmogorov-Smirnov test registers <span class="math inline">\(p &lt; 0.05\)</span>, but this outcome is expected and should not be interpreted as evidence of meaningful misfit: with <span class="math inline">\(N &gt; 140{,}000\)</span> observations, the test has sufficient power to detect deviations of negligible practical magnitude. The visual alignment of the Q-Q plot, the appropriate diagnostic at this sample size shows no systematic departure from the uniform reference.</p>
<p><strong>Residuals versus predicted.</strong> The three quantile lines (25th, 50th, and 75th percentiles of the scaled residuals at each fitted value) are horizontal and evenly spaced across the range of predictions. This indicates the absence of systematic non-linearity and the absence of heteroscedasticity. The model performs with equivalent fidelity across the full range of rainfall intensities, from light drizzle to extreme events.</p>
<hr>
</section>
<section id="sec-autocorrelation" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-autocorrelation"><span class="header-section-number">7.4</span> Temporal Autocorrelation in Residuals</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_autocorrelation.R"</span>))</span>
<span id="cb7-2"><a href="#cb7-2"></a>full_data <span class="ot">&lt;-</span> <span class="fu">build_autocorrelation_data</span>()</span>
<span id="cb7-3"><a href="#cb7-3"></a>dw_results <span class="ot">&lt;-</span> <span class="fu">run_dw_tests</span>(full_data, m_full, res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-dw-results" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dw-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Durbin-Watson test results across all 49 locations, sorted by p-value.
</figcaption>
<div aria-describedby="tbl-dw-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-1c98edccfed3ba5bdd0e" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-1c98edccfed3ba5bdd0e">{"x":{"filter":"none","vertical":false,"caption":"<caption>Durbin-Watson test results across all 49 locations, sorted by p-value.<\/caption>","data":[["Ballarat","Watsonia","Cairns","MelbourneAirport","Walpole","Portland","GoldCoast","Newcastle","Melbourne","Sale","Canberra","Dartmoor","CoffsHarbour","Albany","Launceston","Hobart","PearceRAAF","NorfolkIsland","NorahHead","MountGinini","Nhil","MountGambier","Mildura","Townsville","WaggaWagga","Bendigo","Wollongong","SalmonGums","Nuriootpa","Sydney","Albury","PerthAirport","Penrith","Tuggeranong","Williamtown","Witchcliffe","Adelaide","BadgerysCreek","Katherine","Darwin","Richmond","Moree","SydneyAirport","Uluru","Cobar","AliceSprings","Perth","Brisbane","Woomera"],[2.2527,2.2,1.8149,2.1613,2.1521,2.1246,1.8754,1.8754,2.1367,2.1196,2.1041,2.1089,1.8933,1.9026,2.0962,2.0925,2.0993,2.0933,1.9073,1.908,2.1247,2.0893,2.0864,1.9148,2.0821,2.0806,1.9194,2.0803,2.0786,1.9287,2.0654,2.0629,2.0588,2.0516,2.0523,2.0432,2.042,2.0426,1.9439,2.0373,2.0381,2.0309,2.0222,1.975,2.017,2.0139,2.0109,2.0083,2.0021],[0,0,0,0,0.0001,0.0007,0.0007,0.0007,0.0008,0.0011,0.0024,0.0032,0.0038,0.0075,0.008200000000000001,0.0091,0.0091,0.0111,0.0122,0.0132,0.0137,0.0141,0.0179,0.0191,0.0252,0.0266,0.0278,0.0293,0.0314,0.0395,0.0732,0.0848,0.1097,0.158,0.1867,0.2407,0.2439,0.25,0.2683,0.2923,0.3012,0.4093,0.543,0.627,0.642,0.7028,0.7594,0.8159999999999999,0.9546]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>Location<\/th>\n      <th>DW Statistic<\/th>\n      <th>p-value<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":15,"dom":"tip","columnDefs":[{"className":"dt-right","targets":[1,2]},{"name":"location","targets":0},{"name":"dw_stat","targets":1},{"name":"p_value","targets":2}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[10,15,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</figure>
</div>
</div>
<p>The most consequential assumption to verify in a time-series regression is whether the residuals are serially independent. If the model has failed to capture all temporal structure in the data, residuals from consecutive days will be correlated, violating the assumption of independent errors and producing standard errors that are too small, confidence intervals that are too narrow, and significance tests that are anti-conservative.</p>
<p>This risk is particularly salient here. The raw data shows strong temporal autocorrelation: yesterday’s rain state, the weekly wetness trend, and the dry spell dynamics all create day-to-day dependencies that, if unmodelled, would produce heavily autocorrelated residuals. The model addresses this through multiple temporal mechanisms: the Markov persistence feature <code>rain_yesterday</code>, the 7-day moving average features, the natural spline of <code>days_since_rain</code>, and the cyclical seasonal encoding.</p>
<p><strong>Results across all locations.</strong> The Durbin-Watson test was applied to residuals from all 49 stations and results are reported in <a href="#tbl-dw-results" class="quarto-xref">Table&nbsp;<span>7.1</span></a>, sorted by p-value. The theoretical value under perfect serial independence is 2.0; values below 2 indicate positive autocorrelation and values above 2 indicate negative autocorrelation. The distribution of test statistics across stations reveals a consistent pattern: nearly all values fall in the range 1.81 to 2.25, indicating that the residuals are close to independence everywhere, though the degree of remaining structure varies by location.</p>
<p><strong>Stations with the least residual autocorrelation.</strong> Woomera (DW = 2.0021, <span class="math inline">\(p\)</span> = 0.955), Brisbane (DW = 2.0083, <span class="math inline">\(p\)</span> = 0.816), Perth (DW = 2.0109, <span class="math inline">\(p\)</span> = 0.759), and Alice Springs (DW = 2.0139, <span class="math inline">\(p\)</span> = 0.703) show statistics that are essentially indistinguishable from the ideal value of 2.0. These are predominantly arid or subtropical interior locations where rainfall is episodic and driven by synoptic-scale events well-captured by the dynamic predictors. The temporal engineering has absorbed virtually all day-to-day dependence for these stations.</p>
<p><strong>Stations with the strongest residual autocorrelation.</strong> Ballarat (DW = 2.2527, <span class="math inline">\(p\)</span> &lt; 0.001), Watsonia (DW = 2.2000, <span class="math inline">\(p\)</span> &lt; 0.001), Cairns (DW = 1.8149, <span class="math inline">\(p\)</span> &lt; 0.001), and Melbourne Airport (DW = 2.1613, <span class="math inline">\(p\)</span> &lt; 0.001) sit at the extremes of the distribution. Ballarat and Watsonia, both in the Victorian highlands, show mild negative autocorrelation (DW &gt; 2), suggesting a slight tendency for above-average residuals to follow below-average ones a pattern consistent with orographic rainfall variability that the current predictor set does not fully resolve. Cairns shows mild positive autocorrelation (DW &lt; 2), consistent with multi-day monsoon persistence in tropical North Queensland that the 7-day moving average partially but not entirely captures.</p>
<p><strong>Overall assessment.</strong> The majority of stations cluster near DW = 2.0 with <span class="math inline">\(p\)</span>-values well above conventional thresholds, indicating that the temporal feature engineering was effective across the network as a whole. The residual autocorrelation at a handful of high-rainfall or orographically complex locations is modest in magnitude and does not undermine the validity of the model’s inference; it does, however, identify locations where richer temporal or topographic predictors could yield further improvement.</p>
<hr>
</section>
<section id="sec-eval-summary" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sec-eval-summary"><span class="header-section-number">7.5</span> Summary of Validation Results</h2>
<p>The four validation procedures converge on a consistent picture of a well-specified model. The occurrence submodel achieves strong discriminative separation between dry and wet days, with a conservative error asymmetry appropriate for meteorological risk communication. The random effects structure captures geographically coherent spatial heterogeneity that a pooled model would suppress, with tropical and orographically exposed locations producing substantially more rainfall than the national average and semi-arid interior locations substantially less. The DHARMa diagnostics show close alignment to the uniform reference distribution with no systematic non-linearity or heteroscedasticity across the range of fitted values. The Durbin-Watson tests across all 49 stations confirm that the model’s persistence and dry spell features have successfully eliminated serial dependence from the residuals at the large majority of locations, with modest residual autocorrelation confined to a small number of orographically complex or strongly monsoonal sites. Together, these results support the conclusion that M6 is both statistically valid and physically well-grounded.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/06-modeling.html" class="pagination-link" aria-label="Modelling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/08-model-selection.html" class="pagination-link" aria-label="Model Selection">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu"># Model Evaluation {#sec-evaluation}</span></span>
<span id="cb8-2"><a href="#cb8-2"></a></span>
<span id="cb8-3"><a href="#cb8-3"></a>---</span>
<span id="cb8-4"><a href="#cb8-4"></a></span>
<span id="cb8-5"><a href="#cb8-5"></a><span class="at">&gt; **Chapter Context.** A model that fits training data well is not necessarily a model that is correct. This chapter subjects the final mixed-effects ZIG model (M6) to four distinct validation procedures, each targeting a different potential failure mode: poor discriminative ability in the occurrence submodel, spatially inappropriate parameter homogeneity, distributional misspecification in the residuals, and unabsorbed temporal autocorrelation. Together, these tests form a coherent audit of the model's assumptions and capabilities.</span></span>
<span id="cb8-6"><a href="#cb8-6"></a></span>
<span id="cb8-7"><a href="#cb8-7"></a>---</span>
<span id="cb8-8"><a href="#cb8-8"></a></span>
<span id="cb8-11"><a href="#cb8-11"></a><span class="in">```{r}</span></span>
<span id="cb8-12"><a href="#cb8-12"></a><span class="co">#| label: setup-evaluation</span></span>
<span id="cb8-13"><a href="#cb8-13"></a><span class="co">#| include: false</span></span>
<span id="cb8-14"><a href="#cb8-14"></a></span>
<span id="cb8-15"><a href="#cb8-15"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"config.R"</span>))</span>
<span id="cb8-16"><a href="#cb8-16"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"utils.R"</span>))</span>
<span id="cb8-17"><a href="#cb8-17"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter5"</span>, <span class="st">"feature_engineering.R"</span>))</span>
<span id="cb8-18"><a href="#cb8-18"></a></span>
<span id="cb8-19"><a href="#cb8-19"></a>pred_rainfall <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"models"</span>, <span class="st">"rainfall_preds.rds"</span>))</span>
<span id="cb8-20"><a href="#cb8-20"></a>engineered_list <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp_mids, <span class="at">action =</span> <span class="st">"all"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-21"><a href="#cb8-21"></a>  <span class="fu">map</span>(engineer_features)</span>
<span id="cb8-22"><a href="#cb8-22"></a></span>
<span id="cb8-23"><a href="#cb8-23"></a>m6_mixed <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m6_mixed"</span>)</span>
<span id="cb8-24"><a href="#cb8-24"></a><span class="in">```</span></span>
<span id="cb8-25"><a href="#cb8-25"></a></span>
<span id="cb8-28"><a href="#cb8-28"></a><span class="in">```{r}</span></span>
<span id="cb8-29"><a href="#cb8-29"></a><span class="co">#| label: eval-build-predictions</span></span>
<span id="cb8-30"><a href="#cb8-30"></a><span class="co">#| include: false</span></span>
<span id="cb8-31"><a href="#cb8-31"></a><span class="co">#| cache: true</span></span>
<span id="cb8-32"><a href="#cb8-32"></a></span>
<span id="cb8-33"><a href="#cb8-33"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_classification.R"</span>))</span>
<span id="cb8-34"><a href="#cb8-34"></a>preds <span class="ot">&lt;-</span> <span class="fu">build_predictions</span>()</span>
<span id="cb8-35"><a href="#cb8-35"></a><span class="in">```</span></span>
<span id="cb8-36"><a href="#cb8-36"></a></span>
<span id="cb8-37"><a href="#cb8-37"></a><span class="fu">## Classification Performance of the Occurrence Submodel {#sec-classification}</span></span>
<span id="cb8-38"><a href="#cb8-38"></a></span>
<span id="cb8-41"><a href="#cb8-41"></a><span class="in">```{r}</span></span>
<span id="cb8-42"><a href="#cb8-42"></a><span class="co">#| label: fig-roc-curve</span></span>
<span id="cb8-43"><a href="#cb8-43"></a><span class="co">#| fig-cap: "ROC curve for rainfall occurrence prediction. AUC = 0.813 indicates strong discriminative ability in separating dry days from wet days."</span></span>
<span id="cb8-44"><a href="#cb8-44"></a><span class="co">#| echo: true</span></span>
<span id="cb8-45"><a href="#cb8-45"></a><span class="co">#| message: false</span></span>
<span id="cb8-46"><a href="#cb8-46"></a><span class="co">#| warning: false</span></span>
<span id="cb8-47"><a href="#cb8-47"></a></span>
<span id="cb8-48"><a href="#cb8-48"></a><span class="fu">plot_roc</span>(preds)</span>
<span id="cb8-49"><a href="#cb8-49"></a><span class="in">```</span></span>
<span id="cb8-50"><a href="#cb8-50"></a></span>
<span id="cb8-53"><a href="#cb8-53"></a><span class="in">```{r}</span></span>
<span id="cb8-54"><a href="#cb8-54"></a><span class="co">#| label: fig-confusion-matrix</span></span>
<span id="cb8-55"><a href="#cb8-55"></a><span class="co">#| fig-cap: "Confusion matrix at the Youden-optimal threshold (0.6246)"</span></span>
<span id="cb8-56"><a href="#cb8-56"></a><span class="co">#| echo: true</span></span>
<span id="cb8-57"><a href="#cb8-57"></a><span class="co">#| message: false</span></span>
<span id="cb8-58"><a href="#cb8-58"></a><span class="co">#| warning: false</span></span>
<span id="cb8-59"><a href="#cb8-59"></a></span>
<span id="cb8-60"><a href="#cb8-60"></a><span class="fu">plot_confusion_matrix</span>(preds)</span>
<span id="cb8-61"><a href="#cb8-61"></a><span class="in">```</span></span>
<span id="cb8-62"><a href="#cb8-62"></a></span>
<span id="cb8-65"><a href="#cb8-65"></a><span class="in">```{r}</span></span>
<span id="cb8-66"><a href="#cb8-66"></a><span class="co">#| label: brier-score</span></span>
<span id="cb8-67"><a href="#cb8-67"></a><span class="co">#| echo: true</span></span>
<span id="cb8-68"><a href="#cb8-68"></a></span>
<span id="cb8-69"><a href="#cb8-69"></a><span class="fu">render_brier_scores</span>(preds)</span>
<span id="cb8-70"><a href="#cb8-70"></a><span class="in">```</span></span>
<span id="cb8-71"><a href="#cb8-71"></a></span>
<span id="cb8-72"><a href="#cb8-72"></a>Although the ZIG model is primarily a framework for predicting rainfall amount, its zero-inflation component constitutes a binary classifier at each observation: it assigns a probability that the day is structurally dry. Evaluating this component as a classifier allows direct assessment of how well the model separates the two fundamentally different weather states identified in @sec-eda.</span>
<span id="cb8-73"><a href="#cb8-73"></a></span>
<span id="cb8-74"><a href="#cb8-74"></a>**Discriminative ability.** The area under the ROC curve is 0.813 (@fig-roc-curve), meaning that in 81.3% of randomly drawn pairs consisting of one genuinely dry day and one genuinely wet day, the model correctly assigns the higher dryness probability to the dry day. This threshold-free measure of separation indicates strong discriminative performance for a meteorological classification problem of this complexity.</span>
<span id="cb8-75"><a href="#cb8-75"></a></span>
<span id="cb8-76"><a href="#cb8-76"></a>**Threshold selection.** The raw zero-inflation probability must be converted to a binary prediction through a threshold. Youden's J statistic, which maximises the sum of sensitivity and specificity simultaneously, selects an optimal threshold of 0.6246. This is notably higher than the naive 0.5 default because dry days constitute 64% of the sample: the model's calibrated prior assigns moderate dryness probability to many observations by default, and a higher threshold requires more decisive evidence before predicting "No Rain."</span>
<span id="cb8-77"><a href="#cb8-77"></a></span>
<span id="cb8-78"><a href="#cb8-78"></a>**Confusion matrix.** At this threshold, the model produces 68,074 correct dry-day predictions (true negatives), 36,662 correct rain predictions (true positives), 22,764 false alarms (predicted dry, actually wet), and 14,356 missed rain events (predicted wet, actually dry) (@fig-confusion-matrix). The model generates false alarms at roughly twice the rate at which it misses rain events. In a meteorological context this asymmetry is operationally desirable: the consequence of carrying an umbrella on a dry day is trivial compared to the consequence of being unprepared for a significant rainfall event.</span>
<span id="cb8-79"><a href="#cb8-79"></a></span>
<span id="cb8-80"><a href="#cb8-80"></a>The Brier Score is 0.1654 and the Brier Skill Score is 0.2819, indicating meaningful improvement over a climatological reference forecast.</span>
<span id="cb8-81"><a href="#cb8-81"></a></span>
<span id="cb8-82"><a href="#cb8-82"></a>---</span>
<span id="cb8-83"><a href="#cb8-83"></a></span>
<span id="cb8-84"><a href="#cb8-84"></a><span class="fu">## Spatial Heterogeneity and Random Effects {#sec-random-effects}</span></span>
<span id="cb8-85"><a href="#cb8-85"></a></span>
<span id="cb8-88"><a href="#cb8-88"></a><span class="in">```{r}</span></span>
<span id="cb8-89"><a href="#cb8-89"></a><span class="co">#| label: fig-location-effects</span></span>
<span id="cb8-90"><a href="#cb8-90"></a><span class="co">#| fig-cap: "Location-specific baseline rainfall adjustments (random intercepts). Cities to the right of the dashed line produce systematically more rainfall than the national average when all dynamic weather variables are held constant; cities to the left produce systematically less."</span></span>
<span id="cb8-91"><a href="#cb8-91"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb8-92"><a href="#cb8-92"></a><span class="co">#| fig-height: 12</span></span>
<span id="cb8-93"><a href="#cb8-93"></a><span class="co">#| echo: true</span></span>
<span id="cb8-94"><a href="#cb8-94"></a><span class="co">#| warning: false</span></span>
<span id="cb8-95"><a href="#cb8-95"></a></span>
<span id="cb8-96"><a href="#cb8-96"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_random_effects.R"</span>))</span>
<span id="cb8-97"><a href="#cb8-97"></a><span class="fu">plot_location_effects</span>()</span>
<span id="cb8-98"><a href="#cb8-98"></a><span class="in">```</span></span>
<span id="cb8-99"><a href="#cb8-99"></a></span>
<span id="cb8-100"><a href="#cb8-100"></a>The random intercepts represent the location-specific baseline deviations in rainfall intensity after removing the contribution of all dynamic weather variables humidity, pressure, wind, seasonality, and persistence (@fig-location-effects). What remains is the component of rainfall attributable to geographic and climatic factors that do not vary day-to-day: proximity to moisture sources, orographic effects, predominant circulation patterns, and regional climate regime.</span>
<span id="cb8-101"><a href="#cb8-101"></a></span>
<span id="cb8-102"><a href="#cb8-102"></a></span>
<span id="cb8-103"><a href="#cb8-103"></a>**The wetter locations.** Katherine ($\hat{b} = 0.59$, $e^{0.59} \approx 1.80$) and Tuggeranong ($\hat{b} = 0.52$, $e^{0.52} \approx 1.68$) sit at the high end of the distribution, producing roughly 68% and 80% more rainfall respectively than a hypothetical average Australian location experiencing identical instantaneous weather conditions. Katherine's elevated baseline is geographically coherent: it sits in the tropical Top End of the Northern Territory, where monsoonal systems deliver sustained and intense rainfall with no structural analogue in the temperate south. Tuggeranong is located in the Australian Capital Territory near Canberra, where its elevated baseline reflects orographic enhancement from the surrounding Brindabella Ranges and exposure to moisture-bearing easterly flows that the dynamic predictors do not fully represent on a day-to-day basis.</span>
<span id="cb8-104"><a href="#cb8-104"></a></span>
<span id="cb8-105"><a href="#cb8-105"></a>**The drier locations.** Nhil ($\hat{b} = -0.69$, $e^{-0.69} \approx 0.50$) and Norfolk Island ($\hat{b} = -0.76$, $e^{-0.76} \approx 0.47$) show the strongest negative adjustments. Nhil produces roughly half the rainfall of an average location given identical weather conditions, reflecting its position in the semi-arid Wimmera region of inland Victoria where even moisture-laden air masses tend to deliver less precipitation than they would at the coast.</span>
<span id="cb8-106"><a href="#cb8-106"></a></span>
<span id="cb8-107"><a href="#cb8-107"></a>**Justification for the mixed-effects structure.** The magnitude and geographic coherence of these deviations confirm the necessity of the random effects component. A pooled fixed-effects model would suppress this spatial variation, producing coefficients that systematically over-predict rainfall in arid interior stations and under-predict it in high-rainfall locations. The mixed-effects structure allows the global physical relationships humidity drives intensity, southerly winds bring moisture to remain stable as fixed effects while accommodating the geographically variable baseline against which they operate.</span>
<span id="cb8-108"><a href="#cb8-108"></a></span>
<span id="cb8-109"><a href="#cb8-109"></a>---</span>
<span id="cb8-110"><a href="#cb8-110"></a></span>
<span id="cb8-111"><a href="#cb8-111"></a><span class="fu">## Residual Diagnostics via DHARMa Simulation {#sec-dharma}</span></span>
<span id="cb8-112"><a href="#cb8-112"></a></span>
<span id="cb8-115"><a href="#cb8-115"></a><span class="in">```{r}</span></span>
<span id="cb8-116"><a href="#cb8-116"></a><span class="co">#| label: fig-dharma-diagnostics</span></span>
<span id="cb8-117"><a href="#cb8-117"></a><span class="co">#| fig-cap: "DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs. predicted values."</span></span>
<span id="cb8-118"><a href="#cb8-118"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb8-119"><a href="#cb8-119"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb8-120"><a href="#cb8-120"></a><span class="co">#| echo: true</span></span>
<span id="cb8-121"><a href="#cb8-121"></a><span class="co">#| message: false</span></span>
<span id="cb8-122"><a href="#cb8-122"></a><span class="co">#| warning: false</span></span>
<span id="cb8-123"><a href="#cb8-123"></a></span>
<span id="cb8-124"><a href="#cb8-124"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_diagnostics.R"</span>))</span>
<span id="cb8-125"><a href="#cb8-125"></a><span class="fu">run_dharma_diagnostics</span>()</span>
<span id="cb8-126"><a href="#cb8-126"></a><span class="in">```</span></span>
<span id="cb8-127"><a href="#cb8-127"></a></span>
<span id="cb8-128"><a href="#cb8-128"></a>Standard residual diagnostics are not directly applicable to Zero-Inflated Gamma models: the mixture of a point mass at zero and a continuous positive distribution means that conventional Pearson or deviance residuals do not have a tractable reference distribution. DHARMa addresses this by generating a large number of simulated datasets from the fitted model and computing, for each observation, where the actual value falls in the empirical distribution of simulated values. Under a correctly specified model, these scaled residuals follow a uniform distribution on $<span class="co">[</span><span class="ot">0, 1</span><span class="co">]</span>$ regardless of the model family. Deviations from uniformity indicate misspecification.</span>
<span id="cb8-129"><a href="#cb8-129"></a></span>
<span id="cb8-130"><a href="#cb8-130"></a>**Q-Q plot.** The empirical quantiles of the scaled residuals align closely with the theoretical diagonal across the full range of the distribution. The Kolmogorov-Smirnov test registers $p &lt; 0.05$, but this outcome is expected and should not be interpreted as evidence of meaningful misfit: with $N &gt; 140{,}000$ observations, the test has sufficient power to detect deviations of negligible practical magnitude. The visual alignment of the Q-Q plot, the appropriate diagnostic at this sample size shows no systematic departure from the uniform reference.</span>
<span id="cb8-131"><a href="#cb8-131"></a></span>
<span id="cb8-132"><a href="#cb8-132"></a>**Residuals versus predicted.** The three quantile lines (25th, 50th, and 75th percentiles of the scaled residuals at each fitted value) are horizontal and evenly spaced across the range of predictions. This indicates the absence of systematic non-linearity and the absence of heteroscedasticity. The model performs with equivalent fidelity across the full range of rainfall intensities, from light drizzle to extreme events.</span>
<span id="cb8-133"><a href="#cb8-133"></a></span>
<span id="cb8-134"><a href="#cb8-134"></a>---</span>
<span id="cb8-135"><a href="#cb8-135"></a></span>
<span id="cb8-136"><a href="#cb8-136"></a><span class="fu">## Temporal Autocorrelation in Residuals {#sec-autocorrelation}</span></span>
<span id="cb8-137"><a href="#cb8-137"></a></span>
<span id="cb8-140"><a href="#cb8-140"></a><span class="in">```{r}</span></span>
<span id="cb8-141"><a href="#cb8-141"></a><span class="co">#| label: run-autocorrelation</span></span>
<span id="cb8-142"><a href="#cb8-142"></a><span class="co">#| echo: true</span></span>
<span id="cb8-143"><a href="#cb8-143"></a><span class="co">#| eval: false</span></span>
<span id="cb8-144"><a href="#cb8-144"></a><span class="co">#| message: false</span></span>
<span id="cb8-145"><a href="#cb8-145"></a><span class="co">#| warning: false</span></span>
<span id="cb8-146"><a href="#cb8-146"></a></span>
<span id="cb8-147"><a href="#cb8-147"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter7"</span>, <span class="st">"eval_autocorrelation.R"</span>))</span>
<span id="cb8-148"><a href="#cb8-148"></a>full_data <span class="ot">&lt;-</span> <span class="fu">build_autocorrelation_data</span>()</span>
<span id="cb8-149"><a href="#cb8-149"></a>dw_results <span class="ot">&lt;-</span> <span class="fu">run_dw_tests</span>(full_data, m_full, res)</span>
<span id="cb8-150"><a href="#cb8-150"></a><span class="in">```</span></span>
<span id="cb8-151"><a href="#cb8-151"></a></span>
<span id="cb8-154"><a href="#cb8-154"></a><span class="in">```{r}</span></span>
<span id="cb8-155"><a href="#cb8-155"></a><span class="co">#| label: tbl-dw-results</span></span>
<span id="cb8-156"><a href="#cb8-156"></a><span class="co">#| tbl-cap: "Durbin-Watson test results across all 49 locations, sorted by p-value."</span></span>
<span id="cb8-157"><a href="#cb8-157"></a><span class="co">#| echo: false</span></span>
<span id="cb8-158"><a href="#cb8-158"></a></span>
<span id="cb8-159"><a href="#cb8-159"></a>dw_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"dw_results.csv"</span>))</span>
<span id="cb8-160"><a href="#cb8-160"></a></span>
<span id="cb8-161"><a href="#cb8-161"></a>dw_data <span class="sc">%&gt;%</span></span>
<span id="cb8-162"><a href="#cb8-162"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">round</span>(., <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb8-163"><a href="#cb8-163"></a>  <span class="fu">datatable</span>(</span>
<span id="cb8-164"><a href="#cb8-164"></a>    <span class="at">colnames =</span> <span class="fu">c</span>(<span class="st">"Location"</span>, <span class="st">"DW Statistic"</span>, <span class="st">"p-value"</span>),</span>
<span id="cb8-165"><a href="#cb8-165"></a>    <span class="at">caption =</span> <span class="st">"Durbin-Watson test results across all 49 locations, sorted by p-value."</span>,</span>
<span id="cb8-166"><a href="#cb8-166"></a>    <span class="at">options =</span> <span class="fu">list</span>(<span class="at">pageLength =</span> <span class="dv">15</span>, <span class="at">dom =</span> <span class="st">"tip"</span>),</span>
<span id="cb8-167"><a href="#cb8-167"></a>    <span class="at">rownames =</span> <span class="cn">FALSE</span></span>
<span id="cb8-168"><a href="#cb8-168"></a>  )</span>
<span id="cb8-169"><a href="#cb8-169"></a><span class="in">```</span></span>
<span id="cb8-170"><a href="#cb8-170"></a></span>
<span id="cb8-171"><a href="#cb8-171"></a>The most consequential assumption to verify in a time-series regression is whether the residuals are serially independent. If the model has failed to capture all temporal structure in the data, residuals from consecutive days will be correlated, violating the assumption of independent errors and producing standard errors that are too small, confidence intervals that are too narrow, and significance tests that are anti-conservative.</span>
<span id="cb8-172"><a href="#cb8-172"></a></span>
<span id="cb8-173"><a href="#cb8-173"></a>This risk is particularly salient here. The raw data shows strong temporal autocorrelation: yesterday's rain state, the weekly wetness trend, and the dry spell dynamics all create day-to-day dependencies that, if unmodelled, would produce heavily autocorrelated residuals. The model addresses this through multiple temporal mechanisms: the Markov persistence feature <span class="in">`rain_yesterday`</span>, the 7-day moving average features, the natural spline of <span class="in">`days_since_rain`</span>, and the cyclical seasonal encoding.</span>
<span id="cb8-174"><a href="#cb8-174"></a></span>
<span id="cb8-175"><a href="#cb8-175"></a>**Results across all locations.** The Durbin-Watson test was applied to residuals from all 49 stations and results are reported in @tbl-dw-results, sorted by p-value. The theoretical value under perfect serial independence is 2.0; values below 2 indicate positive autocorrelation and values above 2 indicate negative autocorrelation. The distribution of test statistics across stations reveals a consistent pattern: nearly all values fall in the range 1.81 to 2.25, indicating that the residuals are close to independence everywhere, though the degree of remaining structure varies by location.</span>
<span id="cb8-176"><a href="#cb8-176"></a></span>
<span id="cb8-177"><a href="#cb8-177"></a>**Stations with the least residual autocorrelation.** Woomera (DW = 2.0021, $p$ = 0.955), Brisbane (DW = 2.0083, $p$ = 0.816), Perth (DW = 2.0109, $p$ = 0.759), and Alice Springs (DW = 2.0139, $p$ = 0.703) show statistics that are essentially indistinguishable from the ideal value of 2.0. These are predominantly arid or subtropical interior locations where rainfall is episodic and driven by synoptic-scale events well-captured by the dynamic predictors. The temporal engineering has absorbed virtually all day-to-day dependence for these stations.</span>
<span id="cb8-178"><a href="#cb8-178"></a></span>
<span id="cb8-179"><a href="#cb8-179"></a>**Stations with the strongest residual autocorrelation.** Ballarat (DW = 2.2527, $p$ &lt; 0.001), Watsonia (DW = 2.2000, $p$ &lt; 0.001), Cairns (DW = 1.8149, $p$ &lt; 0.001), and Melbourne Airport (DW = 2.1613, $p$ &lt; 0.001) sit at the extremes of the distribution. Ballarat and Watsonia, both in the Victorian highlands, show mild negative autocorrelation (DW &gt; 2), suggesting a slight tendency for above-average residuals to follow below-average ones a pattern consistent with orographic rainfall variability that the current predictor set does not fully resolve. Cairns shows mild positive autocorrelation (DW &lt; 2), consistent with multi-day monsoon persistence in tropical North Queensland that the 7-day moving average partially but not entirely captures.</span>
<span id="cb8-180"><a href="#cb8-180"></a></span>
<span id="cb8-181"><a href="#cb8-181"></a>**Overall assessment.** The majority of stations cluster near DW = 2.0 with $p$-values well above conventional thresholds, indicating that the temporal feature engineering was effective across the network as a whole. The residual autocorrelation at a handful of high-rainfall or orographically complex locations is modest in magnitude and does not undermine the validity of the model's inference; it does, however, identify locations where richer temporal or topographic predictors could yield further improvement.</span>
<span id="cb8-182"><a href="#cb8-182"></a></span>
<span id="cb8-183"><a href="#cb8-183"></a>---</span>
<span id="cb8-184"><a href="#cb8-184"></a></span>
<span id="cb8-185"><a href="#cb8-185"></a><span class="fu">## Summary of Validation Results {#sec-eval-summary}</span></span>
<span id="cb8-186"><a href="#cb8-186"></a></span>
<span id="cb8-187"><a href="#cb8-187"></a>The four validation procedures converge on a consistent picture of a well-specified model. The occurrence submodel achieves strong discriminative separation between dry and wet days, with a conservative error asymmetry appropriate for meteorological risk communication. The random effects structure captures geographically coherent spatial heterogeneity that a pooled model would suppress, with tropical and orographically exposed locations producing substantially more rainfall than the national average and semi-arid interior locations substantially less. The DHARMa diagnostics show close alignment to the uniform reference distribution with no systematic non-linearity or heteroscedasticity across the range of fitted values. The Durbin-Watson tests across all 49 stations confirm that the model's persistence and dry spell features have successfully eliminated serial dependence from the residuals at the large majority of locations, with modest residual autocorrelation confined to a small number of orographically complex or strongly monsoonal sites. Together, these results support the conclusion that M6 is both statistically valid and physically well-grounded.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/07-evaluation.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>