<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An in-depth statistical analysis of rainfall patterns across 49 Australian cities using Zero-Inflated Gamma GLMMs.">

<title>8&nbsp; Model Selection – Australian Rainfall Dynamics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/09-conclusion.html" rel="next">
<link href="../chapters/07-evaluation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-e66b50aa4120364bfa72329fe8653b98.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-463e05341c278a50bd9d8b9e5c352418.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-modeling.html">Modelling</a></li><li class="breadcrumb-item"><a href="../chapters/08-model-selection.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Australian Rainfall Dynamics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting Australian Rainfall: A Hierarchical Zero-Inflated Gamma Framework</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-data-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputation Sensitivity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature Engineering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-selection.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-model-selection" id="toc-sec-model-selection" class="nav-link active" data-scroll-target="#sec-model-selection"><span class="header-section-number">8.1</span> Distributional Choice, Model Progression, and Predictive Calibration</a></li>
  <li><a href="#sec-predictive-accuracy" id="toc-sec-predictive-accuracy" class="nav-link" data-scroll-target="#sec-predictive-accuracy"><span class="header-section-number">8.2</span> Predictive Accuracy and Distributional Calibration</a></li>
  <li><a href="#sec-distributional-justification" id="toc-sec-distributional-justification" class="nav-link" data-scroll-target="#sec-distributional-justification"><span class="header-section-number">8.3</span> Justification of the Distributional Family</a></li>
  <li><a href="#sec-progressive-selection" id="toc-sec-progressive-selection" class="nav-link" data-scroll-target="#sec-progressive-selection"><span class="header-section-number">8.4</span> Progressive Model Selection via Pooled <span class="math inline">\(D_1\)</span> Statistics</a></li>
  <li><a href="#sec-conclusion" id="toc-sec-conclusion" class="nav-link" data-scroll-target="#sec-conclusion"><span class="header-section-number">8.5</span> Conclusion</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/08-model-selection.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-modeling.html">Modelling</a></li><li class="breadcrumb-item"><a href="../chapters/08-model-selection.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-model-selection" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-model-selection"><span class="header-section-number">8.1</span> Distributional Choice, Model Progression, and Predictive Calibration</h2>
<hr>
<blockquote class="blockquote">
<p>This chapter provides the statistical foundation for three claims made implicitly throughout the modelling sequence: that the Zero-Inflated Gamma (ZIG) family is the appropriate distributional choice for this data, that each successive model extension was a genuine improvement rather than an over-fit, and that the final model captures a meaningful share of the predictable structure in Australian rainfall. Each claim is addressed through a distinct formal procedure.</p>
</blockquote>
<hr>
<hr>
</section>
<section id="sec-predictive-accuracy" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-predictive-accuracy"><span class="header-section-number">8.2</span> Predictive Accuracy and Distributional Calibration</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter8"</span>, <span class="st">"predictive_accuracy.R"</span>))</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">render_error_metrics</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-global-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-global-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.1: Global predictive error metrics across all observations and locations.
</figcaption>
<div aria-describedby="tbl-global-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: right;">7.567</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAE</td>
<td style="text-align: right;">2.760</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">render_error_metrics</span>(<span class="at">filter_zeros =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-positive-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-positive-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.2: Predictive error metrics restricted to rain-days (positive observations only).
</figcaption>
<div aria-describedby="tbl-positive-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RMSE</td>
<td style="text-align: right;">12.263</td>
</tr>
<tr class="even">
<td style="text-align: left;">MAE</td>
<td style="text-align: right;">5.607</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">plot_ppc</span>(ppc_dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-ppc" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ppc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-model-selection_files/figure-html/fig-ppc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ppc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Posterior Predictive Check. The observed distribution (blue) lies well within the envelope of 50 model-simulated distributions (grey), confirming that the ZIG model replicates the key structural features of the rainfall distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The global error metrics in <a href="#tbl-global-metrics" class="quarto-xref">Table&nbsp;<span>8.1</span></a> provide a compact summary of predictive accuracy across all observations and locations. The mean absolute error (MAE) of 2.760 mm indicates that the model’s point prediction deviates from the recorded value by 2.760 mm on an average observation. The root mean squared error (RMSE) of 7.567 mm is substantially larger, reflecting the asymmetric influence of extreme events: a small number of days on which a major storm was under-predicted exerts a disproportionate upward pull on the squared error average. The gap between MAE and RMSE is therefore informative, confirming that prediction errors are not symmetrically distributed but are concentrated in the right tail.</p>
<p>When the evaluation is restricted to rain-days only (<a href="#tbl-positive-metrics" class="quarto-xref">Table&nbsp;<span>8.2</span></a>), the RMSE rises to 12.263 mm and the MAE to 5.607 mm, as expected: the zero observations, which are trivially predicted, no longer dilute the error distribution, and the remaining errors reflect the model’s performance on the harder problem of quantifying intensity.</p>
<p>Point error metrics measure accuracy at the conditional mean but cannot assess whether the model is correctly reproducing the entire shape of the rainfall distribution. The posterior predictive check (PPC) in <a href="#fig-ppc" class="quarto-xref">Figure&nbsp;<span>8.1</span></a> addresses this more demanding criterion by simulating 50 complete datasets from the fitted model and overlaying their empirical densities against the observed distribution. Close agreement across the full range of the distribution is apparent. The peak at 0 mm is reproduced accurately, confirming that the zero-inflation component is generating the correct proportion of dry-day predictions conditional on all covariates. The decay rate of the right tail follows the observed data closely, a property that a Gaussian model structurally cannot achieve given its symmetric support. The model is not merely fitting conditional means: it replicates the probabilistic structure of the underlying climate system.</p>
<hr>
</section>
<section id="sec-distributional-justification" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-distributional-justification"><span class="header-section-number">8.3</span> Justification of the Distributional Family</h2>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">plot_distribution_comparison</span>(check_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-distribution-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distribution-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-model-selection_files/figure-html/fig-distribution-comparison-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distribution-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Predictive density comparison across four distributional families. The Gaussian model predicts negative rainfall, a physical impossibility. The lognormal model respects the positive support but cannot represent dry days without a separate zero-inflation mechanism. Both the Tweedie and ZI-Gamma families accommodate zero values and approximate the right tail of the observed distribution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Choosing a distributional family determines the support of the predictions, the variance function, and the structure of the likelihood being optimised. Four families were evaluated against the full predictor set, as shown in <a href="#fig-distribution-comparison" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>, to isolate the contribution of distributional choice from the contribution of the predictors themselves.</p>
<p><strong>The Gaussian model.</strong> A linear mixed model with Gaussian errors generates predictions that extend into negative values. Because the Gaussian distribution has support over the entire real line, the model has no mechanism to prevent this, and negative rainfall is a physical impossibility. The Gaussian assumption also implies a symmetric and constant variance structure, which is incompatible with the heavy right skew and variance-mean dependence documented in Chapter 4. Fitting a Gaussian model to these data produces predictions that are fundamentally inconsistent with the properties of the system being modelled.</p>
<p><strong>The zero-inflated lognormal model.</strong> The lognormal hurdle model shares the same two-component structure as the ZIG: a logistic zero-inflation submodel and a lognormal conditional intensity submodel with a log link, fitted via the same predictor sets. It therefore handles the zero mass correctly and does not suffer the structural failure of the Gaussian model. The distinction between the lognormal and Gamma families is instead one of tail behaviour and variance function. The lognormal conditional variance is <span class="math inline">\(\text{Var}(Y \mid Y &gt; 0) = \mu^2(e^{\sigma^2} - 1)\)</span>, where <span class="math inline">\(\sigma^2\)</span> is the log-scale variance and is treated as a fixed parameter. The Gamma conditional variance is <span class="math inline">\(\text{Var}(Y \mid Y &gt; 0) = \mu^2 / \phi\)</span>, implying a constant coefficient of variation across the range of fitted values. When the coefficient of variation is approximately stable as is consistent with a multiplicative meteorological process in which larger rain events scale proportionally with atmospheric forcing the Gamma variance function is the more appropriate specification. The lognormal, by contrast, imposes a heavier parametric tail structure through <span class="math inline">\(e^{\sigma^2}\)</span> that is less well-identified when the dispersion parameter must be estimated from a distribution with kurtosis of 181.146. The visual separation between the two families is apparent in <a href="#fig-distribution-comparison" class="quarto-xref">Figure&nbsp;<span>8.2</span></a>, where the ZIG tail tracks the observed density more closely than the lognormal alternative.</p>
<p><strong>The Tweedie model.</strong> The Tweedie distribution with power parameter <span class="math inline">\(p \in (1, 2)\)</span> is a compound Poisson-Gamma distribution that accommodates zero values alongside a continuous positive component. It respects the zero lower bound and can represent right-skewed positive data. However, it models zeros and positive values through a single unified process governed by a single mean parameter and the power index. The probability of a zero and the expected positive value are both driven by the same linear predictor and cannot respond to different sets of covariates.</p>
<p><strong>The Zero-Inflated Gamma model.</strong> The ZIG framework relaxes this constraint explicitly. The zero-inflation and conditional intensity components have separate linear predictors, so predictors of occurrence and predictors of intensity are estimated independently. The EDA provides direct empirical motivation for this separation: the Markov analysis showed that <code>rain_yesterday</code> operates primarily through the hurdle, while the pressure change analysis identified the diurnal pressure signal as more relevant to intensity. These two physical processes do not share the same covariates, and a model that constrains them to do so sacrifices both interpretability and predictive accuracy. The ZIG framework assigns each process its own parameter vector, making it both more flexible and more physically coherent than any of the three alternatives.</p>
<hr>
</section>
<section id="sec-progressive-selection" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-progressive-selection"><span class="header-section-number">8.4</span> Progressive Model Selection via Pooled <span class="math inline">\(D_1\)</span> Statistics</h2>
<p>Each successive extension was evaluated using the pooled <span class="math inline">\(D_1\)</span> Wald test (Li, Raghunathan &amp; Rubin 1991), which provides a joint <span class="math inline">\(F\)</span>-statistic for the parameters added at each step, pooled across multiply imputed datasets via Rubin’s rules. With <span class="math inline">\(n \approx 142{,}000\)</span> observations, <span class="math inline">\(D_1\)</span> converges in probability to the <span class="math inline">\(D_3\)</span> statistic (van Buuren, FIMD), making it the appropriate pooled test for this sample size. The null hypothesis in each case is that the added parameter vector is jointly zero, i.e., that the smaller model is adequate. Delta AIC and delta BIC reported alongside each comparison are heuristic summaries computed from the imputation-averaged log-likelihoods and serve as a secondary consistency check.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m0_null"</span>)</span>
<span id="cb5-2"><a href="#cb5-2"></a>m1 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m1_moisture"</span>)</span>
<span id="cb5-3"><a href="#cb5-3"></a></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m1, <span class="at">m_small =</span> m0) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>  <span class="fu">render_comparison_table</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Moisture &amp; Pressure"</span>, <span class="st">"Null Baseline"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m1-vs-m0" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m1-vs-m0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.3: Nested Model Comparison: Moisture &amp; Pressure vs.&nbsp;Null Baseline. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m1-vs-m0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Moisture &amp; Pressure vs Null Baseline</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Humidity3pm<br>
Dewpoint 9am<br>
Dewpoint Change<br>
Pressure Change</td>
<td style="text-align: right; width: 5em;">141.806</td>
<td style="text-align: right; width: 5em;">4</td>
<td style="text-align: right; width: 5em;">39.8</td>
<td style="text-align: right; width: 5em;">16.525</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -35938.32, delta BIC = -35899.87 (negative favours + Moisture &amp; Pressure; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The four moisture and pressure parameters (Humidity3pm, Dewpoint 9am, Dewpoint Change, Pressure Change) are jointly significant at <span class="math inline">\(F(4,\ 39.8) = 141.806\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>, with a relative increase in variance (RIV) of 16.525 reflecting substantial between-imputation variability in the moisture predictors (<a href="#tbl-d1-m1-vs-m0" class="quarto-xref">Table&nbsp;<span>8.3</span></a>). The <span class="math inline">\(\Delta\text{AIC} = -35{,}938.32\)</span> relative to the null represents the largest single gain in the model sequence.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m2_temporal"</span>)</span>
<span id="cb6-2"><a href="#cb6-2"></a></span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m2, <span class="at">m_small =</span> m1) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb6-5"><a href="#cb6-5"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Seasonality &amp; Persistence"</span>, <span class="st">"Moisture Only"</span>)</span>
<span id="cb6-6"><a href="#cb6-6"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m2-vs-m1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m2-vs-m1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.4: Nested Model Comparison: Seasonality &amp; Persistence vs.&nbsp;Moisture Only. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m2-vs-m1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Seasonality &amp; Persistence vs Moisture Only</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Day Cos<br>
Day Sin<br>
ZI: Rain Yesterday (Yes)<br>
ZI: Cloud Development</td>
<td style="text-align: right; width: 5em;">802.158</td>
<td style="text-align: right; width: 5em;">4</td>
<td style="text-align: right; width: 5em;">71.3</td>
<td style="text-align: right; width: 5em;">2.098</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -12810.42, delta BIC = -12772.62 (negative favours + Seasonality &amp; Persistence; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The seasonal and persistence parameters (Day Cos, Day Sin, ZI: Rain Yesterday, ZI: Cloud Development) yield <span class="math inline">\(F(4,\ 71.3) = 802.158\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="#tbl-d1-m2-vs-m1" class="quarto-xref">Table&nbsp;<span>8.4</span></a>). The <span class="math inline">\(F\)</span>-statistic is the largest in the sequence, driven by the Markov persistence indicator <code>rain_yesterday</code>, whose effect on the zero-inflation submodel is among the strongest individual signals in the model. The <span class="math inline">\(\Delta\text{AIC} = -12{,}810.42\)</span>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m3_history"</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m3, <span class="at">m_small =</span> m2) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb7-5"><a href="#cb7-5"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Accumulated History"</span>, <span class="st">"Seasonality &amp; Persistence"</span>)</span>
<span id="cb7-6"><a href="#cb7-6"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m3-vs-m2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m3-vs-m2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.5: Nested Model Comparison: Accumulated History vs.&nbsp;Seasonality &amp; Persistence. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m3-vs-m2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Accumulated History vs Seasonality &amp; Persistence</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Rainfall Ma7<br>
Days Since Rain<br>
Humidity Ma7<br>
ZI: Sunshine<br>
ZI: Evaporation</td>
<td style="text-align: right; width: 5em;">275.213</td>
<td style="text-align: right; width: 5em;">5</td>
<td style="text-align: right; width: 5em;">177.8</td>
<td style="text-align: right; width: 5em;">0.902</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -4005.81, delta BIC = -3960.45 (negative favours + Accumulated History; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The five accumulated history parameters (Rainfall Ma7, Days Since Rain, Humidity Ma7, ZI: Sunshine, ZI: Evaporation) are jointly significant at <span class="math inline">\(F(5,\ 177.8) = 275.213\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="#tbl-d1-m3-vs-m2" class="quarto-xref">Table&nbsp;<span>8.5</span></a>). The denominator degrees of freedom of 177.8 are Barnard-Rubin corrected and their relatively large value reflects low between-imputation variability, consistent with the stability of moving-average features across imputed datasets. The <span class="math inline">\(\Delta\text{AIC} = -4{,}005.81\)</span>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m4_energy"</span>)</span>
<span id="cb8-2"><a href="#cb8-2"></a></span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m4, <span class="at">m_small =</span> m3) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb8-5"><a href="#cb8-5"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Thermodynamics &amp; Interaction"</span>, <span class="st">"Accumulated History"</span>)</span>
<span id="cb8-6"><a href="#cb8-6"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m4-vs-m3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m4-vs-m3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.6: Nested Model Comparison: Thermodynamics &amp; Interaction vs.&nbsp;Accumulated History. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m4-vs-m3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Thermodynamics &amp; Interaction vs Accumulated History</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Instability Index<br>
Sun Humid Interaction</td>
<td style="text-align: right; width: 5em;">49.375</td>
<td style="text-align: right; width: 5em;">2</td>
<td style="text-align: right; width: 5em;">24.1</td>
<td style="text-align: right; width: 5em;">4.470</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -1066.31, delta BIC = -1028.51 (negative favours + Thermodynamics &amp; Interaction; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The thermodynamic and interaction parameters (Instability Index, Sun-Humidity Interaction) yield <span class="math inline">\(F(2,\ 24.1) = 49.375\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="#tbl-d1-m4-vs-m3" class="quarto-xref">Table&nbsp;<span>8.6</span></a>). The elevated RIV of 4.470 and the small denominator degrees of freedom indicate that the instability index is sensitive to imputation: the atmospheric instability variable has non-trivial missing data, and its imputed values differ meaningfully across datasets. The point estimate nonetheless clears the significance threshold decisively. The <span class="math inline">\(\Delta\text{AIC} = -1{,}066.31\)</span>.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m5_wind"</span>)</span>
<span id="cb9-2"><a href="#cb9-2"></a></span>
<span id="cb9-3"><a href="#cb9-3"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m5, <span class="at">m_small =</span> m4) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb9-5"><a href="#cb9-5"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Wind Vectors"</span>, <span class="st">"Thermodynamics &amp; Interaction"</span>)</span>
<span id="cb9-6"><a href="#cb9-6"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m5-vs-m4" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m5-vs-m4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.7: Nested Model Comparison: Wind Vectors vs.&nbsp;Thermodynamics &amp; Interaction. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m5-vs-m4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Wind Vectors vs Thermodynamics &amp; Interaction</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Gust U EW<br>
Gust V NS<br>
Wind9am V NS<br>
Wind9am U EW</td>
<td style="text-align: right; width: 5em;">133.422</td>
<td style="text-align: right; width: 5em;">4</td>
<td style="text-align: right; width: 5em;">272.8</td>
<td style="text-align: right; width: 5em;">0.497</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -782.35, delta BIC = -752.11 (negative favours + Wind Vectors; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The four wind vector parameters (Gust U EW, Gust V NS, Wind9am V NS, Wind9am U EW) yield <span class="math inline">\(F(4,\ 272.8) = 133.422\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="#tbl-d1-m5-vs-m4" class="quarto-xref">Table&nbsp;<span>8.7</span></a>). This step produces the smallest absolute AIC reduction in the sequence (<span class="math inline">\(\Delta\text{AIC} = -782.35\)</span>), yet the <span class="math inline">\(F\)</span>-statistic is large and the RIV of 0.497 is the smallest in the sequence, indicating that wind direction is well-identified across imputations. The improvement is genuine rather than artefactual.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>m6 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m6_mixed"</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a></span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m6, <span class="at">m_small =</span> m5) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="fu">render_comparison_table</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Random Effects"</span>, <span class="st">"Wind Vectors"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-d1-m6-vs-m5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-d1-m6-vs-m5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.8: Nested Model Comparison: Mixed Effects (splines + random intercepts) vs.&nbsp;Wind Vectors. D1 pooled Wald test across 10 imputed datasets.
</figcaption>
<div aria-describedby="tbl-d1-m6-vs-m5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small">
<caption>Nested Model Comparison: + Random Effects vs Wind Vectors</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Test</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">Parameters tested</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">F</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df1</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">df2</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">RIV</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: rgba(44, 62, 80, 255) !important;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">D1 pooled Wald</td>
<td style="text-align: left; width: 20em; white-space: pre-wrap; word-break: break-word;">Dewpoint Change (Spline)<br>
Pressure Change (Spline)<br>
Evaporation (Spline)<br>
Instability Index (Spline, Df=3)1<br>
Instability Index (Spline, Df=3)2<br>
Instability Index (Spline, Df=3)3<br>
Gust U EW (Spline, Df=2)1<br>
Gust U EW (Spline, Df=2)2<br>
Wind9am U EW (Spline, Df=2)1<br>
Wind9am U EW (Spline, Df=2)2</td>
<td style="text-align: right; width: 5em;">75.283</td>
<td style="text-align: right; width: 5em;">10</td>
<td style="text-align: right; width: 5em;">138.9</td>
<td style="text-align: right; width: 5em;">3.877</td>
<td style="text-align: right; width: 5em;">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Note: </span></td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> † p&lt;0.1 * p&lt;0.05 ** p&lt;0.01 *** p&lt;0.001</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0;"><sup></sup> delta AIC = -6915.32, delta BIC = -6786.8 (negative favours + Random Effects; heuristic only). Based on 10 common imputations.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0;"><sup></sup> Pooled via Rubin’s rules.</td>
<td style="text-align: left;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>The ten spline and random-effect parameters yield <span class="math inline">\(F(10,\ 138.9) = 75.283\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="#tbl-d1-m6-vs-m5" class="quarto-xref">Table&nbsp;<span>8.8</span></a>). The <span class="math inline">\(\Delta\text{AIC} = -6{,}915.32\)</span> is the second largest gain in the sequence, reflecting the substantial explanatory contribution of geographic heterogeneity. The RIV of 3.877 indicates that the non-linear spline terms, particularly the instability index spline and the eastward wind component splines, show meaningful between-imputation variability.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter8"</span>, <span class="st">"model_progression.R"</span>))</span>
<span id="cb11-2"><a href="#cb11-2"></a>model_stats <span class="ot">&lt;-</span> <span class="fu">build_model_stats</span>()</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="fu">render_model_summary</span>(model_stats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-model-selection-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-selection-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8.9: Model selection summary. AIC and BIC are heuristic quantities averaged across imputed datasets. <span class="math inline">\(\Delta\)</span>AIC is relative to M6, the best model. The Akaike weight of M6 rounds to 1.0 at any practical precision.
</figcaption>
<div aria-describedby="tbl-model-selection-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped do-not-create-environment cell caption-top table-sm small">
<caption>Model Selection Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Δ AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Akaike Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">M6: Mixed Effects</td>
<td style="text-align: right;">400151.2</td>
<td style="text-align: right;">400498.9</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">M5: Wind</td>
<td style="text-align: right;">407066.5</td>
<td style="text-align: right;">407285.7</td>
<td style="text-align: right;">6915.32</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M4: Energy</td>
<td style="text-align: right;">407848.8</td>
<td style="text-align: right;">408037.8</td>
<td style="text-align: right;">7697.66</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">M3: History</td>
<td style="text-align: right;">408915.1</td>
<td style="text-align: right;">409066.3</td>
<td style="text-align: right;">8763.97</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M2: Temporal</td>
<td style="text-align: right;">412920.9</td>
<td style="text-align: right;">413026.8</td>
<td style="text-align: right;">12769.78</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">M1: Moisture</td>
<td style="text-align: right;">425731.4</td>
<td style="text-align: right;">425799.4</td>
<td style="text-align: right;">25580.19</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M0: Null</td>
<td style="text-align: right;">461669.7</td>
<td style="text-align: right;">461699.3</td>
<td style="text-align: right;">61518.51</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Show the code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">plot_aic_trajectory</span>(model_stats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-model-selection" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model-selection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-model-selection_files/figure-html/fig-model-selection-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model-selection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: AIC trajectory across the progressive model sequence. Each extension reduces AIC monotonically, confirming that no step introduced net redundancy. The two largest gains correspond to the initial moisture and pressure predictors (M0 to M1) and the final mixed-effects structure (M5 to M6).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The complete model progression is summarised in <a href="#tbl-model-selection-summary" class="quarto-xref">Table&nbsp;<span>8.9</span></a> and illustrated in <a href="#fig-model-selection" class="quarto-xref">Figure&nbsp;<span>8.3</span></a>. AIC quantifies the information lost when a given model approximates the true data-generating process, penalising complexity to discourage over-fitting. A monotonically decreasing AIC sequence is not guaranteed: a predictor block whose likelihood improvement is smaller than its parameter penalty will produce a net AIC increase. The fact that every extension in <a href="#fig-model-selection" class="quarto-xref">Figure&nbsp;<span>8.3</span></a> produced a net reduction confirms that each added component captures genuine signal rather than noise.</p>
<p>The pooled <span class="math inline">\(D_1\)</span> <span class="math inline">\(F\)</span>-statistics provide the corresponding inferential framework under multiple imputation. For each nested pair, the test evaluates whether the additional parameters are jointly zero, with the <span class="math inline">\(F\)</span>-statistic and degrees of freedom pooled via Rubin’s rules. The numerator degrees of freedom equal the number of parameters added at each step; the denominator degrees of freedom are Barnard-Rubin corrected and therefore appear as non-integers. All six comparisons reject the null at <span class="math inline">\(p &lt; 0.001\)</span>. Even the step with the smallest absolute AIC gain, the addition of wind vectors from M4 to M5 (<span class="math inline">\(\Delta\text{AIC} = -782.35\)</span>), yields <span class="math inline">\(F(4,\ 272.8) = 133.422\)</span>, an improvement overwhelmingly inconsistent with chance.</p>
<p>The Akaike weights provide a final calibration. With <span class="math inline">\(\Delta\text{AIC} = 61{,}518.51\)</span> separating M6 from the null baseline, and a minimum pairwise separation of 782.35 between any two adjacent models, the weight assigned to M6 rounds to 1.0 at any practical decimal precision. There is no information-theoretic basis for preferring any earlier model in the sequence.</p>
<hr>
</section>
<section id="sec-conclusion" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-conclusion"><span class="header-section-number">8.5</span> Conclusion</h2>
<p>The evidence assembled across this chapter supports three conclusions. First, the ZIG distributional family is the appropriate choice for these data: the Gaussian model produces physically impossible negative predictions, and the Tweedie model, while valid, constrains occurrence and intensity to share the same linear predictor in a manner inconsistent with the distinct physical processes identified in the EDA. Second, every step in the progressive model sequence represents a statistically significant improvement, confirmed by pooled <span class="math inline">\(D_1\)</span> Wald tests, each rejecting the null at <span class="math inline">\(p &lt; 0.001\)</span>, and by a monotonically decreasing AIC trajectory. The Akaike weight of M6 is effectively 1.0, leaving no information-theoretic basis for preferring any earlier model. Third, the posterior predictive check confirms that the final model reproduces the distributional shape of Australian rainfall across the full support of the response, not only at the conditional mean. The occurrence and intensity components are separately calibrated and jointly coherent with the physical mechanisms motivating the model structure.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/07-evaluation.html" class="pagination-link" aria-label="Model Evaluation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/09-conclusion.html" class="pagination-link" aria-label="Conclusion">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1"></a><span class="in">```{r}</span></span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="co">#| label: setup-selection</span></span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="co">#| include: false</span></span>
<span id="cb13-4"><a href="#cb13-4"></a></span>
<span id="cb13-5"><a href="#cb13-5"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"config.R"</span>))</span>
<span id="cb13-6"><a href="#cb13-6"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"utils.R"</span>))</span>
<span id="cb13-7"><a href="#cb13-7"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter5"</span>, <span class="st">"feature_engineering.R"</span>))</span>
<span id="cb13-8"><a href="#cb13-8"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter6"</span>, <span class="st">"mitml_wrappers.R"</span>))</span>
<span id="cb13-9"><a href="#cb13-9"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter6"</span>, <span class="st">"Reporting.R"</span>))</span>
<span id="cb13-10"><a href="#cb13-10"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter8"</span>, <span class="st">"distribution_comparison.R"</span>))</span>
<span id="cb13-11"><a href="#cb13-11"></a></span>
<span id="cb13-12"><a href="#cb13-12"></a>m6_mixed <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m6_mixed"</span>)</span>
<span id="cb13-13"><a href="#cb13-13"></a>m_full <span class="ot">&lt;-</span> <span class="fu">get_diagnostic_model</span>(m6_mixed)</span>
<span id="cb13-14"><a href="#cb13-14"></a>pred_rainfall <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"models"</span>, <span class="st">"rainfall_preds.rds"</span>))</span>
<span id="cb13-15"><a href="#cb13-15"></a></span>
<span id="cb13-16"><a href="#cb13-16"></a>engineered_list <span class="ot">&lt;-</span> <span class="fu">complete</span>(imp_mids, <span class="st">"all"</span>) <span class="sc">%&gt;%</span> <span class="fu">map</span>(engineer_features)</span>
<span id="cb13-17"><a href="#cb13-17"></a><span class="in">```</span></span>
<span id="cb13-18"><a href="#cb13-18"></a></span>
<span id="cb13-19"><a href="#cb13-19"></a><span class="fu"># Model Selection</span></span>
<span id="cb13-20"><a href="#cb13-20"></a></span>
<span id="cb13-21"><a href="#cb13-21"></a><span class="fu">## Distributional Choice, Model Progression, and Predictive Calibration {#sec-model-selection}</span></span>
<span id="cb13-22"><a href="#cb13-22"></a></span>
<span id="cb13-23"><a href="#cb13-23"></a>---</span>
<span id="cb13-24"><a href="#cb13-24"></a></span>
<span id="cb13-25"><a href="#cb13-25"></a><span class="at">&gt; This chapter provides the statistical foundation for three claims made implicitly throughout the modelling sequence: that the Zero-Inflated Gamma (ZIG) family is the appropriate distributional choice for this data, that each successive model extension was a genuine improvement rather than an over-fit, and that the final model captures a meaningful share of the predictable structure in Australian rainfall. Each claim is addressed through a distinct formal procedure.</span></span>
<span id="cb13-26"><a href="#cb13-26"></a></span>
<span id="cb13-27"><a href="#cb13-27"></a>---</span>
<span id="cb13-28"><a href="#cb13-28"></a></span>
<span id="cb13-29"><a href="#cb13-29"></a>---</span>
<span id="cb13-30"><a href="#cb13-30"></a></span>
<span id="cb13-31"><a href="#cb13-31"></a><span class="fu">## Predictive Accuracy and Distributional Calibration {#sec-predictive-accuracy}</span></span>
<span id="cb13-32"><a href="#cb13-32"></a></span>
<span id="cb13-35"><a href="#cb13-35"></a><span class="in">```{r}</span></span>
<span id="cb13-36"><a href="#cb13-36"></a><span class="co">#| label: tbl-global-metrics</span></span>
<span id="cb13-37"><a href="#cb13-37"></a><span class="co">#| tbl-cap: "Global predictive error metrics across all observations and locations."</span></span>
<span id="cb13-38"><a href="#cb13-38"></a><span class="co">#| #| echo: true</span></span>
<span id="cb13-39"><a href="#cb13-39"></a><span class="co">#| message: false</span></span>
<span id="cb13-40"><a href="#cb13-40"></a><span class="co">#| cache: true</span></span>
<span id="cb13-41"><a href="#cb13-41"></a><span class="co">#| warning: false</span></span>
<span id="cb13-42"><a href="#cb13-42"></a></span>
<span id="cb13-43"><a href="#cb13-43"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter8"</span>, <span class="st">"predictive_accuracy.R"</span>))</span>
<span id="cb13-44"><a href="#cb13-44"></a><span class="fu">render_error_metrics</span>()</span>
<span id="cb13-45"><a href="#cb13-45"></a><span class="in">```</span></span>
<span id="cb13-46"><a href="#cb13-46"></a></span>
<span id="cb13-49"><a href="#cb13-49"></a><span class="in">```{r}</span></span>
<span id="cb13-50"><a href="#cb13-50"></a><span class="co">#| label: tbl-positive-metrics</span></span>
<span id="cb13-51"><a href="#cb13-51"></a><span class="co">#| tbl-cap: "Predictive error metrics restricted to rain-days (positive observations only)."</span></span>
<span id="cb13-52"><a href="#cb13-52"></a><span class="co">#| echo: true</span></span>
<span id="cb13-53"><a href="#cb13-53"></a></span>
<span id="cb13-54"><a href="#cb13-54"></a><span class="fu">render_error_metrics</span>(<span class="at">filter_zeros =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-55"><a href="#cb13-55"></a><span class="in">```</span></span>
<span id="cb13-56"><a href="#cb13-56"></a></span>
<span id="cb13-59"><a href="#cb13-59"></a><span class="in">```{r}</span></span>
<span id="cb13-60"><a href="#cb13-60"></a><span class="co">#| label: load-ppc-dat</span></span>
<span id="cb13-61"><a href="#cb13-61"></a><span class="co">#| include: false</span></span>
<span id="cb13-62"><a href="#cb13-62"></a></span>
<span id="cb13-63"><a href="#cb13-63"></a>ppc_dat <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"ppc_dat.rds"</span>))</span>
<span id="cb13-64"><a href="#cb13-64"></a><span class="in">```</span></span>
<span id="cb13-65"><a href="#cb13-65"></a></span>
<span id="cb13-68"><a href="#cb13-68"></a><span class="in">```{r}</span></span>
<span id="cb13-69"><a href="#cb13-69"></a><span class="co">#| label: fig-ppc</span></span>
<span id="cb13-70"><a href="#cb13-70"></a><span class="co">#| fig-cap: "Posterior Predictive Check. The observed distribution (blue) lies well within the envelope of 50 model-simulated distributions (grey), confirming that the ZIG model replicates the key structural features of the rainfall distribution."</span></span>
<span id="cb13-71"><a href="#cb13-71"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb13-72"><a href="#cb13-72"></a><span class="co">#| fig-height: 7</span></span>
<span id="cb13-73"><a href="#cb13-73"></a><span class="co">#| warning: false</span></span>
<span id="cb13-74"><a href="#cb13-74"></a><span class="co">#| message: false</span></span>
<span id="cb13-75"><a href="#cb13-75"></a></span>
<span id="cb13-76"><a href="#cb13-76"></a><span class="fu">plot_ppc</span>(ppc_dat)</span>
<span id="cb13-77"><a href="#cb13-77"></a><span class="in">```</span></span>
<span id="cb13-78"><a href="#cb13-78"></a></span>
<span id="cb13-79"><a href="#cb13-79"></a>The global error metrics in @tbl-global-metrics provide a compact summary of predictive accuracy across all observations and locations. The mean absolute error (MAE) of 2.760 mm indicates that the model's point prediction deviates from the recorded value by 2.760 mm on an average observation. The root mean squared error (RMSE) of 7.567 mm is substantially larger, reflecting the asymmetric influence of extreme events: a small number of days on which a major storm was under-predicted exerts a disproportionate upward pull on the squared error average. The gap between MAE and RMSE is therefore informative, confirming that prediction errors are not symmetrically distributed but are concentrated in the right tail.</span>
<span id="cb13-80"><a href="#cb13-80"></a></span>
<span id="cb13-81"><a href="#cb13-81"></a>When the evaluation is restricted to rain-days only (@tbl-positive-metrics), the RMSE rises to 12.263 mm and the MAE to 5.607 mm, as expected: the zero observations, which are trivially predicted, no longer dilute the error distribution, and the remaining errors reflect the model's performance on the harder problem of quantifying intensity.</span>
<span id="cb13-82"><a href="#cb13-82"></a></span>
<span id="cb13-83"><a href="#cb13-83"></a>Point error metrics measure accuracy at the conditional mean but cannot assess whether the model is correctly reproducing the entire shape of the rainfall distribution. The posterior predictive check (PPC) in @fig-ppc addresses this more demanding criterion by simulating 50 complete datasets from the fitted model and overlaying their empirical densities against the observed distribution. Close agreement across the full range of the distribution is apparent. The peak at 0 mm is reproduced accurately, confirming that the zero-inflation component is generating the correct proportion of dry-day predictions conditional on all covariates. The decay rate of the right tail follows the observed data closely, a property that a Gaussian model structurally cannot achieve given its symmetric support. The model is not merely fitting conditional means: it replicates the probabilistic structure of the underlying climate system.</span>
<span id="cb13-84"><a href="#cb13-84"></a></span>
<span id="cb13-85"><a href="#cb13-85"></a>---</span>
<span id="cb13-86"><a href="#cb13-86"></a></span>
<span id="cb13-87"><a href="#cb13-87"></a><span class="fu">## Justification of the Distributional Family {#sec-distributional-justification}</span></span>
<span id="cb13-88"><a href="#cb13-88"></a></span>
<span id="cb13-91"><a href="#cb13-91"></a><span class="in">```{r}</span></span>
<span id="cb13-92"><a href="#cb13-92"></a><span class="co">#| label: load-check-data</span></span>
<span id="cb13-93"><a href="#cb13-93"></a><span class="co">#| include: false</span></span>
<span id="cb13-94"><a href="#cb13-94"></a></span>
<span id="cb13-95"><a href="#cb13-95"></a>check_data <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"models"</span>, <span class="st">"check_data.rds"</span>))</span>
<span id="cb13-96"><a href="#cb13-96"></a><span class="in">```</span></span>
<span id="cb13-97"><a href="#cb13-97"></a></span>
<span id="cb13-100"><a href="#cb13-100"></a><span class="in">```{r}</span></span>
<span id="cb13-101"><a href="#cb13-101"></a><span class="co">#| label: fig-distribution-comparison</span></span>
<span id="cb13-102"><a href="#cb13-102"></a><span class="co">#| fig-cap: "Predictive density comparison across four distributional families. The Gaussian model predicts negative rainfall, a physical impossibility. The lognormal model respects the positive support but cannot represent dry days without a separate zero-inflation mechanism. Both the Tweedie and ZI-Gamma families accommodate zero values and approximate the right tail of the observed distribution."</span></span>
<span id="cb13-103"><a href="#cb13-103"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb13-104"><a href="#cb13-104"></a><span class="co">#| fig-height: 8</span></span>
<span id="cb13-105"><a href="#cb13-105"></a><span class="co">#| echo: true</span></span>
<span id="cb13-106"><a href="#cb13-106"></a><span class="co">#| warning: false</span></span>
<span id="cb13-107"><a href="#cb13-107"></a></span>
<span id="cb13-108"><a href="#cb13-108"></a><span class="fu">plot_distribution_comparison</span>(check_data)</span>
<span id="cb13-109"><a href="#cb13-109"></a><span class="in">```</span></span>
<span id="cb13-110"><a href="#cb13-110"></a></span>
<span id="cb13-111"><a href="#cb13-111"></a>Choosing a distributional family determines the support of the predictions, the variance function, and the structure of the likelihood being optimised. Four families were evaluated against the full predictor set, as shown in @fig-distribution-comparison, to isolate the contribution of distributional choice from the contribution of the predictors themselves.</span>
<span id="cb13-112"><a href="#cb13-112"></a></span>
<span id="cb13-113"><a href="#cb13-113"></a>**The Gaussian model.** A linear mixed model with Gaussian errors generates predictions that extend into negative values. Because the Gaussian distribution has support over the entire real line, the model has no mechanism to prevent this, and negative rainfall is a physical impossibility. The Gaussian assumption also implies a symmetric and constant variance structure, which is incompatible with the heavy right skew and variance-mean dependence documented in Chapter 4. Fitting a Gaussian model to these data produces predictions that are fundamentally inconsistent with the properties of the system being modelled.</span>
<span id="cb13-114"><a href="#cb13-114"></a></span>
<span id="cb13-115"><a href="#cb13-115"></a>**The zero-inflated lognormal model.** The lognormal hurdle model shares the same two-component structure as the ZIG: a logistic zero-inflation submodel and a lognormal conditional intensity submodel with a log link, fitted via the same predictor sets. It therefore handles the zero mass correctly and does not suffer the structural failure of the Gaussian model. The distinction between the lognormal and Gamma families is instead one of tail behaviour and variance function. The lognormal conditional variance is $\text{Var}(Y \mid Y &gt; 0) = \mu^2(e^{\sigma^2} - 1)$, where $\sigma^2$ is the log-scale variance and is treated as a fixed parameter. The Gamma conditional variance is $\text{Var}(Y \mid Y &gt; 0) = \mu^2 / \phi$, implying a constant coefficient of variation across the range of fitted values. When the coefficient of variation is approximately stable as is consistent with a multiplicative meteorological process in which larger rain events scale proportionally with atmospheric forcing the Gamma variance function is the more appropriate specification. The lognormal, by contrast, imposes a heavier parametric tail structure through $e^{\sigma^2}$ that is less well-identified when the dispersion parameter must be estimated from a distribution with kurtosis of 181.146. The visual separation between the two families is apparent in @fig-distribution-comparison, where the ZIG tail tracks the observed density more closely than the lognormal alternative.</span>
<span id="cb13-116"><a href="#cb13-116"></a></span>
<span id="cb13-117"><a href="#cb13-117"></a>**The Tweedie model.** The Tweedie distribution with power parameter $p \in (1, 2)$ is a compound Poisson-Gamma distribution that accommodates zero values alongside a continuous positive component. It respects the zero lower bound and can represent right-skewed positive data. However, it models zeros and positive values through a single unified process governed by a single mean parameter and the power index. The probability of a zero and the expected positive value are both driven by the same linear predictor and cannot respond to different sets of covariates.</span>
<span id="cb13-118"><a href="#cb13-118"></a></span>
<span id="cb13-119"><a href="#cb13-119"></a>**The Zero-Inflated Gamma model.** The ZIG framework relaxes this constraint explicitly. The zero-inflation and conditional intensity components have separate linear predictors, so predictors of occurrence and predictors of intensity are estimated independently. The EDA provides direct empirical motivation for this separation: the Markov analysis showed that <span class="in">`rain_yesterday`</span> operates primarily through the hurdle, while the pressure change analysis identified the diurnal pressure signal as more relevant to intensity. These two physical processes do not share the same covariates, and a model that constrains them to do so sacrifices both interpretability and predictive accuracy. The ZIG framework assigns each process its own parameter vector, making it both more flexible and more physically coherent than any of the three alternatives.</span>
<span id="cb13-120"><a href="#cb13-120"></a></span>
<span id="cb13-121"><a href="#cb13-121"></a>---</span>
<span id="cb13-122"><a href="#cb13-122"></a></span>
<span id="cb13-123"><a href="#cb13-123"></a><span class="fu">## Progressive Model Selection via Pooled $D_1$ Statistics {#sec-progressive-selection}</span></span>
<span id="cb13-124"><a href="#cb13-124"></a></span>
<span id="cb13-125"><a href="#cb13-125"></a>Each successive extension was evaluated using the pooled $D_1$ Wald test (Li, Raghunathan &amp; Rubin 1991), which provides a joint $F$-statistic for the parameters added at each step, pooled across multiply imputed datasets via Rubin's rules. With $n \approx 142{,}000$ observations, $D_1$ converges in probability to the $D_3$ statistic (van Buuren, FIMD), making it the appropriate pooled test for this sample size. The null hypothesis in each case is that the added parameter vector is jointly zero, i.e., that the smaller model is adequate. Delta AIC and delta BIC reported alongside each comparison are heuristic summaries computed from the imputation-averaged log-likelihoods and serve as a secondary consistency check.</span>
<span id="cb13-126"><a href="#cb13-126"></a></span>
<span id="cb13-129"><a href="#cb13-129"></a><span class="in">```{r}</span></span>
<span id="cb13-130"><a href="#cb13-130"></a><span class="co">#| label: tbl-d1-m1-vs-m0</span></span>
<span id="cb13-131"><a href="#cb13-131"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Moisture &amp; Pressure vs. Null Baseline. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-132"><a href="#cb13-132"></a><span class="co">#| message: false</span></span>
<span id="cb13-133"><a href="#cb13-133"></a><span class="co">#| warning: false</span></span>
<span id="cb13-134"><a href="#cb13-134"></a></span>
<span id="cb13-135"><a href="#cb13-135"></a>m0 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m0_null"</span>)</span>
<span id="cb13-136"><a href="#cb13-136"></a>m1 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m1_moisture"</span>)</span>
<span id="cb13-137"><a href="#cb13-137"></a></span>
<span id="cb13-138"><a href="#cb13-138"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m1, <span class="at">m_small =</span> m0) <span class="sc">%&gt;%</span></span>
<span id="cb13-139"><a href="#cb13-139"></a>  <span class="fu">render_comparison_table</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Moisture &amp; Pressure"</span>, <span class="st">"Null Baseline"</span>))</span>
<span id="cb13-140"><a href="#cb13-140"></a><span class="in">```</span></span>
<span id="cb13-141"><a href="#cb13-141"></a></span>
<span id="cb13-144"><a href="#cb13-144"></a><span class="in">```{r}</span></span>
<span id="cb13-145"><a href="#cb13-145"></a><span class="co">#| label: evict-m0</span></span>
<span id="cb13-146"><a href="#cb13-146"></a><span class="co">#| include: false</span></span>
<span id="cb13-147"><a href="#cb13-147"></a></span>
<span id="cb13-148"><a href="#cb13-148"></a><span class="fu">evict_model</span>(<span class="st">"m0_null"</span>)</span>
<span id="cb13-149"><a href="#cb13-149"></a><span class="in">```</span></span>
<span id="cb13-150"><a href="#cb13-150"></a></span>
<span id="cb13-151"><a href="#cb13-151"></a>The four moisture and pressure parameters (Humidity3pm, Dewpoint 9am, Dewpoint Change, Pressure Change) are jointly significant at $F(4,\ 39.8) = 141.806$, $p &lt; 0.001$, with a relative increase in variance (RIV) of 16.525 reflecting substantial between-imputation variability in the moisture predictors (@tbl-d1-m1-vs-m0). The $\Delta\text{AIC} = -35{,}938.32$ relative to the null represents the largest single gain in the model sequence.</span>
<span id="cb13-152"><a href="#cb13-152"></a></span>
<span id="cb13-155"><a href="#cb13-155"></a><span class="in">```{r}</span></span>
<span id="cb13-156"><a href="#cb13-156"></a><span class="co">#| label: tbl-d1-m2-vs-m1</span></span>
<span id="cb13-157"><a href="#cb13-157"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Seasonality &amp; Persistence vs. Moisture Only. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-158"><a href="#cb13-158"></a><span class="co">#| message: false</span></span>
<span id="cb13-159"><a href="#cb13-159"></a><span class="co">#| warning: false</span></span>
<span id="cb13-160"><a href="#cb13-160"></a></span>
<span id="cb13-161"><a href="#cb13-161"></a>m2 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m2_temporal"</span>)</span>
<span id="cb13-162"><a href="#cb13-162"></a></span>
<span id="cb13-163"><a href="#cb13-163"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m2, <span class="at">m_small =</span> m1) <span class="sc">%&gt;%</span></span>
<span id="cb13-164"><a href="#cb13-164"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb13-165"><a href="#cb13-165"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Seasonality &amp; Persistence"</span>, <span class="st">"Moisture Only"</span>)</span>
<span id="cb13-166"><a href="#cb13-166"></a>  )</span>
<span id="cb13-167"><a href="#cb13-167"></a><span class="in">```</span></span>
<span id="cb13-168"><a href="#cb13-168"></a></span>
<span id="cb13-171"><a href="#cb13-171"></a><span class="in">```{r}</span></span>
<span id="cb13-172"><a href="#cb13-172"></a><span class="co">#| label: evict-m1</span></span>
<span id="cb13-173"><a href="#cb13-173"></a><span class="co">#| include: false</span></span>
<span id="cb13-174"><a href="#cb13-174"></a></span>
<span id="cb13-175"><a href="#cb13-175"></a><span class="fu">evict_model</span>(<span class="st">"m1_moisture"</span>)</span>
<span id="cb13-176"><a href="#cb13-176"></a><span class="in">```</span></span>
<span id="cb13-177"><a href="#cb13-177"></a></span>
<span id="cb13-178"><a href="#cb13-178"></a>The seasonal and persistence parameters (Day Cos, Day Sin, ZI: Rain Yesterday, ZI: Cloud Development) yield $F(4,\ 71.3) = 802.158$, $p &lt; 0.001$ (@tbl-d1-m2-vs-m1). The $F$-statistic is the largest in the sequence, driven by the Markov persistence indicator <span class="in">`rain_yesterday`</span>, whose effect on the zero-inflation submodel is among the strongest individual signals in the model. The $\Delta\text{AIC} = -12{,}810.42$.</span>
<span id="cb13-179"><a href="#cb13-179"></a></span>
<span id="cb13-182"><a href="#cb13-182"></a><span class="in">```{r}</span></span>
<span id="cb13-183"><a href="#cb13-183"></a><span class="co">#| label: tbl-d1-m3-vs-m2</span></span>
<span id="cb13-184"><a href="#cb13-184"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Accumulated History vs. Seasonality &amp; Persistence. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-185"><a href="#cb13-185"></a><span class="co">#| message: false</span></span>
<span id="cb13-186"><a href="#cb13-186"></a><span class="co">#| warning: false</span></span>
<span id="cb13-187"><a href="#cb13-187"></a></span>
<span id="cb13-188"><a href="#cb13-188"></a>m3 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m3_history"</span>)</span>
<span id="cb13-189"><a href="#cb13-189"></a></span>
<span id="cb13-190"><a href="#cb13-190"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m3, <span class="at">m_small =</span> m2) <span class="sc">%&gt;%</span></span>
<span id="cb13-191"><a href="#cb13-191"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb13-192"><a href="#cb13-192"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Accumulated History"</span>, <span class="st">"Seasonality &amp; Persistence"</span>)</span>
<span id="cb13-193"><a href="#cb13-193"></a>  )</span>
<span id="cb13-194"><a href="#cb13-194"></a><span class="in">```</span></span>
<span id="cb13-195"><a href="#cb13-195"></a></span>
<span id="cb13-198"><a href="#cb13-198"></a><span class="in">```{r}</span></span>
<span id="cb13-199"><a href="#cb13-199"></a><span class="co">#| label: evict-m2</span></span>
<span id="cb13-200"><a href="#cb13-200"></a><span class="co">#| include: false</span></span>
<span id="cb13-201"><a href="#cb13-201"></a></span>
<span id="cb13-202"><a href="#cb13-202"></a><span class="fu">evict_model</span>(<span class="st">"m2_temporal"</span>)</span>
<span id="cb13-203"><a href="#cb13-203"></a><span class="in">```</span></span>
<span id="cb13-204"><a href="#cb13-204"></a></span>
<span id="cb13-205"><a href="#cb13-205"></a>The five accumulated history parameters (Rainfall Ma7, Days Since Rain, Humidity Ma7, ZI: Sunshine, ZI: Evaporation) are jointly significant at $F(5,\ 177.8) = 275.213$, $p &lt; 0.001$ (@tbl-d1-m3-vs-m2). The denominator degrees of freedom of 177.8 are Barnard-Rubin corrected and their relatively large value reflects low between-imputation variability, consistent with the stability of moving-average features across imputed datasets. The $\Delta\text{AIC} = -4{,}005.81$.</span>
<span id="cb13-206"><a href="#cb13-206"></a></span>
<span id="cb13-209"><a href="#cb13-209"></a><span class="in">```{r}</span></span>
<span id="cb13-210"><a href="#cb13-210"></a><span class="co">#| label: tbl-d1-m4-vs-m3</span></span>
<span id="cb13-211"><a href="#cb13-211"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Thermodynamics &amp; Interaction vs. Accumulated History. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-212"><a href="#cb13-212"></a><span class="co">#| message: false</span></span>
<span id="cb13-213"><a href="#cb13-213"></a><span class="co">#| warning: false</span></span>
<span id="cb13-214"><a href="#cb13-214"></a></span>
<span id="cb13-215"><a href="#cb13-215"></a>m4 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m4_energy"</span>)</span>
<span id="cb13-216"><a href="#cb13-216"></a></span>
<span id="cb13-217"><a href="#cb13-217"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m4, <span class="at">m_small =</span> m3) <span class="sc">%&gt;%</span></span>
<span id="cb13-218"><a href="#cb13-218"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb13-219"><a href="#cb13-219"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Thermodynamics &amp; Interaction"</span>, <span class="st">"Accumulated History"</span>)</span>
<span id="cb13-220"><a href="#cb13-220"></a>  )</span>
<span id="cb13-221"><a href="#cb13-221"></a><span class="in">```</span></span>
<span id="cb13-222"><a href="#cb13-222"></a></span>
<span id="cb13-225"><a href="#cb13-225"></a><span class="in">```{r}</span></span>
<span id="cb13-226"><a href="#cb13-226"></a><span class="co">#| label: evict-m3</span></span>
<span id="cb13-227"><a href="#cb13-227"></a><span class="co">#| include: false</span></span>
<span id="cb13-228"><a href="#cb13-228"></a></span>
<span id="cb13-229"><a href="#cb13-229"></a><span class="fu">evict_model</span>(<span class="st">"m3_history"</span>)</span>
<span id="cb13-230"><a href="#cb13-230"></a><span class="in">```</span></span>
<span id="cb13-231"><a href="#cb13-231"></a></span>
<span id="cb13-232"><a href="#cb13-232"></a>The thermodynamic and interaction parameters (Instability Index, Sun-Humidity Interaction) yield $F(2,\ 24.1) = 49.375$, $p &lt; 0.001$ (@tbl-d1-m4-vs-m3). The elevated RIV of 4.470 and the small denominator degrees of freedom indicate that the instability index is sensitive to imputation: the atmospheric instability variable has non-trivial missing data, and its imputed values differ meaningfully across datasets. The point estimate nonetheless clears the significance threshold decisively. The $\Delta\text{AIC} = -1{,}066.31$.</span>
<span id="cb13-233"><a href="#cb13-233"></a></span>
<span id="cb13-236"><a href="#cb13-236"></a><span class="in">```{r}</span></span>
<span id="cb13-237"><a href="#cb13-237"></a><span class="co">#| label: tbl-d1-m5-vs-m4</span></span>
<span id="cb13-238"><a href="#cb13-238"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Wind Vectors vs. Thermodynamics &amp; Interaction. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-239"><a href="#cb13-239"></a><span class="co">#| message: false</span></span>
<span id="cb13-240"><a href="#cb13-240"></a><span class="co">#| warning: false</span></span>
<span id="cb13-241"><a href="#cb13-241"></a></span>
<span id="cb13-242"><a href="#cb13-242"></a>m5 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m5_wind"</span>)</span>
<span id="cb13-243"><a href="#cb13-243"></a></span>
<span id="cb13-244"><a href="#cb13-244"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m5, <span class="at">m_small =</span> m4) <span class="sc">%&gt;%</span></span>
<span id="cb13-245"><a href="#cb13-245"></a>  <span class="fu">render_comparison_table</span>(</span>
<span id="cb13-246"><a href="#cb13-246"></a>    <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Wind Vectors"</span>, <span class="st">"Thermodynamics &amp; Interaction"</span>)</span>
<span id="cb13-247"><a href="#cb13-247"></a>  )</span>
<span id="cb13-248"><a href="#cb13-248"></a><span class="in">```</span></span>
<span id="cb13-249"><a href="#cb13-249"></a></span>
<span id="cb13-252"><a href="#cb13-252"></a><span class="in">```{r}</span></span>
<span id="cb13-253"><a href="#cb13-253"></a><span class="co">#| label: evict-m4</span></span>
<span id="cb13-254"><a href="#cb13-254"></a><span class="co">#| include: false</span></span>
<span id="cb13-255"><a href="#cb13-255"></a></span>
<span id="cb13-256"><a href="#cb13-256"></a><span class="fu">evict_model</span>(<span class="st">"m4_energy"</span>)</span>
<span id="cb13-257"><a href="#cb13-257"></a><span class="in">```</span></span>
<span id="cb13-258"><a href="#cb13-258"></a></span>
<span id="cb13-259"><a href="#cb13-259"></a>The four wind vector parameters (Gust U EW, Gust V NS, Wind9am V NS, Wind9am U EW) yield $F(4,\ 272.8) = 133.422$, $p &lt; 0.001$ (@tbl-d1-m5-vs-m4). This step produces the smallest absolute AIC reduction in the sequence ($\Delta\text{AIC} = -782.35$), yet the $F$-statistic is large and the RIV of 0.497 is the smallest in the sequence, indicating that wind direction is well-identified across imputations. The improvement is genuine rather than artefactual.</span>
<span id="cb13-260"><a href="#cb13-260"></a></span>
<span id="cb13-263"><a href="#cb13-263"></a><span class="in">```{r}</span></span>
<span id="cb13-264"><a href="#cb13-264"></a><span class="co">#| label: tbl-d1-m6-vs-m5</span></span>
<span id="cb13-265"><a href="#cb13-265"></a><span class="co">#| tbl-cap: "Nested Model Comparison: Mixed Effects (splines + random intercepts) vs. Wind Vectors. D1 pooled Wald test across 10 imputed datasets."</span></span>
<span id="cb13-266"><a href="#cb13-266"></a><span class="co">#| message: false</span></span>
<span id="cb13-267"><a href="#cb13-267"></a><span class="co">#| warning: false</span></span>
<span id="cb13-268"><a href="#cb13-268"></a></span>
<span id="cb13-269"><a href="#cb13-269"></a>m6 <span class="ot">&lt;-</span> <span class="fu">get_model</span>(<span class="st">"m6_mixed"</span>)</span>
<span id="cb13-270"><a href="#cb13-270"></a></span>
<span id="cb13-271"><a href="#cb13-271"></a><span class="fu">compare_models</span>(<span class="at">m_large =</span> m6, <span class="at">m_small =</span> m5) <span class="sc">%&gt;%</span></span>
<span id="cb13-272"><a href="#cb13-272"></a>  <span class="fu">render_comparison_table</span>(<span class="at">names =</span> <span class="fu">c</span>(<span class="st">"+ Random Effects"</span>, <span class="st">"Wind Vectors"</span>))</span>
<span id="cb13-273"><a href="#cb13-273"></a><span class="in">```</span></span>
<span id="cb13-274"><a href="#cb13-274"></a></span>
<span id="cb13-277"><a href="#cb13-277"></a><span class="in">```{r}</span></span>
<span id="cb13-278"><a href="#cb13-278"></a><span class="co">#| label: evict-m5-m6</span></span>
<span id="cb13-279"><a href="#cb13-279"></a><span class="co">#| include: false</span></span>
<span id="cb13-280"><a href="#cb13-280"></a></span>
<span id="cb13-281"><a href="#cb13-281"></a><span class="fu">evict_model</span>(<span class="st">"m5_wind"</span>, <span class="st">"m6_mixed"</span>)</span>
<span id="cb13-282"><a href="#cb13-282"></a><span class="in">```</span></span>
<span id="cb13-283"><a href="#cb13-283"></a></span>
<span id="cb13-284"><a href="#cb13-284"></a>The ten spline and random-effect parameters yield $F(10,\ 138.9) = 75.283$, $p &lt; 0.001$ (@tbl-d1-m6-vs-m5). The $\Delta\text{AIC} = -6{,}915.32$ is the second largest gain in the sequence, reflecting the substantial explanatory contribution of geographic heterogeneity. The RIV of 3.877 indicates that the non-linear spline terms, particularly the instability index spline and the eastward wind component splines, show meaningful between-imputation variability.</span>
<span id="cb13-285"><a href="#cb13-285"></a></span>
<span id="cb13-288"><a href="#cb13-288"></a><span class="in">```{r}</span></span>
<span id="cb13-289"><a href="#cb13-289"></a><span class="co">#| label: tbl-model-selection-summary</span></span>
<span id="cb13-290"><a href="#cb13-290"></a><span class="co">#| tbl-cap: "Model selection summary. AIC and BIC are heuristic quantities averaged across imputed datasets. $\\Delta$AIC is relative to M6, the best model. The Akaike weight of M6 rounds to 1.0 at any practical precision."</span></span>
<span id="cb13-291"><a href="#cb13-291"></a></span>
<span id="cb13-292"><a href="#cb13-292"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"chapter8"</span>, <span class="st">"model_progression.R"</span>))</span>
<span id="cb13-293"><a href="#cb13-293"></a>model_stats <span class="ot">&lt;-</span> <span class="fu">build_model_stats</span>()</span>
<span id="cb13-294"><a href="#cb13-294"></a></span>
<span id="cb13-295"><a href="#cb13-295"></a><span class="fu">render_model_summary</span>(model_stats)</span>
<span id="cb13-296"><a href="#cb13-296"></a><span class="in">```</span></span>
<span id="cb13-297"><a href="#cb13-297"></a></span>
<span id="cb13-300"><a href="#cb13-300"></a><span class="in">```{r}</span></span>
<span id="cb13-301"><a href="#cb13-301"></a><span class="co">#| label: fig-model-selection</span></span>
<span id="cb13-302"><a href="#cb13-302"></a><span class="co">#| fig-cap: "AIC trajectory across the progressive model sequence. Each extension reduces AIC monotonically, confirming that no step introduced net redundancy. The two largest gains correspond to the initial moisture and pressure predictors (M0 to M1) and the final mixed-effects structure (M5 to M6)."</span></span>
<span id="cb13-303"><a href="#cb13-303"></a><span class="co">#| fig-width: 10</span></span>
<span id="cb13-304"><a href="#cb13-304"></a><span class="co">#| fig-height: 8</span></span>
<span id="cb13-305"><a href="#cb13-305"></a></span>
<span id="cb13-306"><a href="#cb13-306"></a><span class="fu">plot_aic_trajectory</span>(model_stats)</span>
<span id="cb13-307"><a href="#cb13-307"></a><span class="in">```</span></span>
<span id="cb13-308"><a href="#cb13-308"></a></span>
<span id="cb13-309"><a href="#cb13-309"></a>The complete model progression is summarised in @tbl-model-selection-summary and illustrated in @fig-model-selection. AIC quantifies the information lost when a given model approximates the true data-generating process, penalising complexity to discourage over-fitting. A monotonically decreasing AIC sequence is not guaranteed: a predictor block whose likelihood improvement is smaller than its parameter penalty will produce a net AIC increase. The fact that every extension in @fig-model-selection produced a net reduction confirms that each added component captures genuine signal rather than noise.</span>
<span id="cb13-310"><a href="#cb13-310"></a></span>
<span id="cb13-311"><a href="#cb13-311"></a>The pooled $D_1$ $F$-statistics provide the corresponding inferential framework under multiple imputation. For each nested pair, the test evaluates whether the additional parameters are jointly zero, with the $F$-statistic and degrees of freedom pooled via Rubin's rules. The numerator degrees of freedom equal the number of parameters added at each step; the denominator degrees of freedom are Barnard-Rubin corrected and therefore appear as non-integers. All six comparisons reject the null at $p &lt; 0.001$. Even the step with the smallest absolute AIC gain, the addition of wind vectors from M4 to M5 ($\Delta\text{AIC} = -782.35$), yields $F(4,\ 272.8) = 133.422$, an improvement overwhelmingly inconsistent with chance.</span>
<span id="cb13-312"><a href="#cb13-312"></a></span>
<span id="cb13-313"><a href="#cb13-313"></a>The Akaike weights provide a final calibration. With $\Delta\text{AIC} = 61{,}518.51$ separating M6 from the null baseline, and a minimum pairwise separation of 782.35 between any two adjacent models, the weight assigned to M6 rounds to 1.0 at any practical decimal precision. There is no information-theoretic basis for preferring any earlier model in the sequence.</span>
<span id="cb13-314"><a href="#cb13-314"></a></span>
<span id="cb13-315"><a href="#cb13-315"></a>---</span>
<span id="cb13-316"><a href="#cb13-316"></a></span>
<span id="cb13-317"><a href="#cb13-317"></a><span class="fu">## Conclusion {#sec-conclusion}</span></span>
<span id="cb13-318"><a href="#cb13-318"></a></span>
<span id="cb13-319"><a href="#cb13-319"></a>The evidence assembled across this chapter supports three conclusions. First, the ZIG distributional family is the appropriate choice for these data: the Gaussian model produces physically impossible negative predictions, and the Tweedie model, while valid, constrains occurrence and intensity to share the same linear predictor in a manner inconsistent with the distinct physical processes identified in the EDA. Second, every step in the progressive model sequence represents a statistically significant improvement, confirmed by pooled $D_1$ Wald tests, each rejecting the null at $p &lt; 0.001$, and by a monotonically decreasing AIC trajectory. The Akaike weight of M6 is effectively 1.0, leaving no information-theoretic basis for preferring any earlier model. Third, the posterior predictive check confirms that the final model reproduces the distributional shape of Australian rainfall across the full support of the response, not only at the conditional mean. The occurrence and intensity components are separately calibrated and jointly coherent with the physical mechanisms motivating the model structure.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/08-model-selection.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>