<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="An in-depth statistical analysis of rainfall patterns across 49 Australian cities using Zero-Inflated Gamma GLMMs.">

<title>9&nbsp; Conclusion – Australian Rainfall Dynamics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/08-model-selection.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-e66b50aa4120364bfa72329fe8653b98.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-9eae319670a971b7aedd265dafd44b4f.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-463e05341c278a50bd9d8b9e5c352418.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0ab7de0d2ef93333524c07e51bfb23fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/09-conclusion.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Australian Rainfall Dynamics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicting Australian Rainfall: A Hierarchical Zero-Inflated Gamma Framework</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Data</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-data-prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Imputation Sensitivity Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Feature Engineering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Modelling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Modelling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Model Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-model-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-conclusion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-findings" id="toc-sec-findings" class="nav-link active" data-scroll-target="#sec-findings"><span class="header-section-number">9.1</span> Summary of Principal Findings</a></li>
  <li><a href="#sec-performance" id="toc-sec-performance" class="nav-link" data-scroll-target="#sec-performance"><span class="header-section-number">9.2</span> Model Performance</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">9.3</span> Limitations</a></li>
  <li><a href="#sec-extensions" id="toc-sec-extensions" class="nav-link" data-scroll-target="#sec-extensions"><span class="header-section-number">9.4</span> Recommended Extensions</a></li>
  <li><a href="#sec-closing" id="toc-sec-closing" class="nav-link" data-scroll-target="#sec-closing"><span class="header-section-number">9.5</span> Closing Statement</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/09-conclusion.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-conclusion" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This analysis demonstrates that Australian daily rainfall is a structured physical phenomenon generated by distinct, identifiable processes operating at different temporal and spatial scales. The final Mixed-Effects Zero-Inflated Gamma (ZIG) model succeeds because its architecture was designed to reflect that structure.</p>
<p>The core argument, supported across seven analytical chapters, is that rainfall requires two qualitatively separate submodels. Occurrence and intensity are governed by different atmospheric mechanisms, respond to different covariates, and show different temporal and spatial patterns. Conflating them, as a standard Gaussian linear model or a Tweedie model does, produces predictions that are physically incoherent, statistically misspecified, and inferior in predictive accuracy. The ZIG framework assigns each process its own linear predictor and parameter vector, making the structural separation explicit.</p>
<hr>
<section id="sec-findings" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-findings"><span class="header-section-number">9.1</span> Summary of Principal Findings</h2>
<p><strong>Distributional properties of the target variable.</strong> The 142,199 daily observations show a zero-inflation rate of 64.05%, a skewness of 9.836, and a kurtosis of 181.146. The maximum recorded value is 371 mm, and 151 events exceed 100 mm. These properties collectively rule out a single-component Gaussian model: any such model would assign positive probability to negative rainfall values and systematically underestimate the probability of the zero outcome. The ZIG family, identified as appropriate by the EDA in <a href="04-eda.html" class="quarto-xref"><span>Chapter 4</span></a>, directly addresses both properties through a mixture of a point mass at zero and a Gamma-distributed positive component.</p>
<p><strong>The Rain Corner interaction.</strong> Rainfall occurrence is not a linear function of humidity or sunshine individually. It concentrates in a specific region of the bivariate feature space where afternoon humidity exceeds approximately 60% and daily sunshine falls below approximately five hours simultaneously. The Sun-Humidity interaction term included in M4 is jointly significant at <span class="math inline">\(F(2,\ 24.1) = 49.375\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (see <a href="08-model-selection.html#tbl-d1-m4-vs-m3" class="quarto-xref">Table&nbsp;<span>8.6</span></a>), and the interaction is physically interpretable: the conjunction of a saturated atmosphere and suppressed solar radiation creates the thermodynamic conditions necessary for precipitation. An additive model cannot represent this conditional structure.</p>
<p><strong>Markovian persistence.</strong> Having rained the previous day is the single strongest predictor in the zero-inflation submodel across the entire model sequence. The Markov Chain analysis in <a href="04-eda.html#sec-markov" class="quarto-xref"><span>Section 4.4.2</span></a> established that dry states have an 85% probability of remaining dry from one day to the next, while wet states have only a 47% probability of continued rain. Encoding this first-order dependency through <code>rain_yesterday</code> and <code>days_since_rain</code> was essential: the temporal features block (Day Cos, Day Sin, <code>rain_yesterday</code>, Cloud Development) produced the largest pooled <span class="math inline">\(D_1\)</span> <span class="math inline">\(F\)</span>-statistic in the model sequence at <span class="math inline">\(F(4,\ 71.3) = 802.158\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="08-model-selection.html#tbl-d1-m2-vs-m1" class="quarto-xref">Table&nbsp;<span>8.4</span></a>).</p>
<p><strong>Wind vector dynamics.</strong> Wind direction is a circular variable whose information is destroyed by naive linear encoding. Decomposing compass bearings into orthogonal east-west and north-south components revealed that southerly and westerly airflows are the dominant directional drivers of rainfall intensity, consistent with the influence of Southern Ocean frontal systems. The four wind vector parameters are jointly significant at <span class="math inline">\(F(4,\ 272.8) = 133.422\)</span>, <span class="math inline">\(p &lt; 0.001\)</span> (<a href="08-model-selection.html#tbl-d1-m5-vs-m4" class="quarto-xref">Table&nbsp;<span>8.7</span></a>), with a relative increase in variance (RIV) of 0.497, the lowest in the sequence, indicating stable identification of wind direction signal across all imputed datasets.</p>
<p><strong>Spatial heterogeneity and random effects.</strong> The random intercepts from the final mixed-effects model (M6) reveal location-specific baseline deviations in rainfall intensity that persist after all dynamic weather predictors are controlled. Tropical Top End stations produce roughly 1.7 to 1.8 times more rainfall than the national average at identical atmospheric conditions, while arid interior stations produce approximately half as much. The addition of splines and random effects over M5 yields <span class="math inline">\(F(10,\ 138.9) = 75.283\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>, with <span class="math inline">\(\Delta\text{AIC} = -6{,}915.32\)</span> (<a href="08-model-selection.html#tbl-d1-m6-vs-m5" class="quarto-xref">Table&nbsp;<span>8.8</span></a>). A pooled fixed-effects model would suppress this spatial variation by averaging across all stations, systematically over-predicting rainfall in inland stations and under-predicting it in tropical ones.</p>
<p><strong>Temporal autocorrelation elimination.</strong> The Durbin-Watson statistic on the residuals of the final model is roughly around 2.0 among most of the locations. The temporal feature engineering documented in <a href="05-features.html" class="quarto-xref"><span>Chapter 5</span></a>, comprising <code>rain_yesterday</code>, <code>rainfall_ma7</code>, <code>humidity_ma7</code>, and the natural spline of <code>days_since_rain</code>, successfully absorbed the temporal dependence present in the raw data. What remains in the residuals is not the signature of an unmodelled temporal component but genuine unpredictability from the available predictors.</p>
<hr>
</section>
<section id="sec-performance" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-performance"><span class="header-section-number">9.2</span> Model Performance</h2>
<p>The final model achieves the performance metrics in <a href="#tbl-performance" class="quarto-xref">Table&nbsp;<span>9.1</span></a>, validated against the full dataset with DHARMa simulation-based diagnostics confirming residual adequacy.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-performance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Summary of performance metrics for the final Mixed-Effects ZIG model (M6), validated on the full dataset.
</figcaption>
<div aria-describedby="tbl-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10cm;">AUC (occurrence submodel)</td>
<td style="text-align: right; width: 4cm;">0.813</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10cm;">Youden-optimal threshold</td>
<td style="text-align: right; width: 4cm;">0.6246</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10cm;">Brier Score</td>
<td style="text-align: right; width: 4cm;">0.1654</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10cm;">Brier Skill Score</td>
<td style="text-align: right; width: 4cm;">0.2819</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10cm;">Mean absolute error (all observations)</td>
<td style="text-align: right; width: 4cm;">2.760 mm</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10cm;">Mean absolute error (rain-days only)</td>
<td style="text-align: right; width: 4cm;">5.607 mm</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10cm;">RMSE (all observations)</td>
<td style="text-align: right; width: 4cm;">7.567 mm</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10cm;">RMSE (rain-days only)</td>
<td style="text-align: right; width: 4cm;">12.263 mm</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10cm;">Zero-inflation calibration ratio</td>
<td style="text-align: right; width: 4cm;">1.00 (p = 0.512)</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10cm;">Dispersion test (p-value)</td>
<td style="text-align: right; width: 4cm;">0.152</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The AUC of 0.813 confirms that the occurrence submodel correctly ranks a randomly drawn dry day above a randomly drawn wet day in 81.3% of cases, a threshold-free measure of discriminative performance that does not depend on any particular operating point. At the Youden-optimal threshold of 0.6246, the Brier Score of 0.1654 and Brier Skill Score of 0.2819 quantify the calibrated probabilistic accuracy of the occurrence submodel relative to a naive climatological baseline. The MAE of 2.760 mm represents the average absolute deviation between the model’s point prediction and the recorded observation across all days; the higher rain-day MAE of 5.607 mm reflects the harder prediction problem on positive observations once dry days are excluded. The zero-inflation calibration ratio of 1.00 (<span class="math inline">\(p = 0.512\)</span>) confirms that the hurdle component reproduces the 64.05% dry-day rate correctly across the full conditional distribution of covariates, not merely at the intercept. The dispersion test yields <span class="math inline">\(p = 0.152\)</span>, giving no evidence that the residual variance deviates from what the fitted ZIG family implies.</p>
<hr>
</section>
<section id="sec-limitations" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">9.3</span> Limitations</h2>
<p><strong>Tail underestimation.</strong> The Gamma distribution accommodates right skew but has exponentially declining tails rather than power-law tails. Rare events exceeding approximately 50 mm per day are systematically under-predicted. The model correctly identifies conditions conducive to extreme rainfall but underestimates the magnitude of such events. This is an inherent property of the Gamma family, not a failure of specification within that family.</p>
<p><strong>Stationarity.</strong> All parameters are estimated from a fixed historical record and are assumed stable over time. The model does not encode non-stationarity arising from shifts in the Southern Oscillation Index, the Indian Ocean Dipole, or long-term anthropogenic forcing. Predictions made under climate trajectories outside the historical parameter space are extrapolations beyond the scope of the model.</p>
<p><strong>Observational confounding.</strong> Coefficient estimates represent conditional associations, not causal effects. Unobserved variables including soil moisture feedback, aerosol loading, and land surface characteristics may confound the estimated meteorological relationships. The model is appropriate for prediction under conditions similar to the training data; causal attribution of rainfall to specific drivers requires experimental or quasi-experimental designs.</p>
<hr>
</section>
<section id="sec-extensions" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-extensions"><span class="header-section-number">9.4</span> Recommended Extensions</h2>
<p><strong>Extreme value tail augmentation.</strong> A natural extension is a composite model that applies the ZIG framework to the body of the distribution and grafts a Generalised Pareto Distribution (GPD) to exceedances above the 95th percentile. This would preserve predictive accuracy on typical days while correcting the systematic tail underestimation that limits the model’s utility for flood risk applications.</p>
<p><strong>Large-scale climate indices.</strong> The Southern Oscillation Index and the Indian Ocean Dipole modulate Australian rainfall at interannual timescales and are absent from the current feature set. Including them as slowly varying covariates in either submodel would allow the model to shift its baseline predictions between El Niño and La Niña years, addressing a known gap in predictive accuracy for anomalous climate regimes.</p>
<p><strong>Dynamic updating.</strong> The current model is static, estimated once from the full historical record. A natural operational extension would implement sequential re-estimation of the random effects as new observations accumulate, allowing location-specific baselines to track gradual shifts in local climate without re-fitting the full fixed-effects structure.</p>
<hr>
</section>
<section id="sec-closing" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-closing"><span class="header-section-number">9.5</span> Closing Statement</h2>
<p>The methodological progression across this report reflects a single guiding principle: statistical modelling should be constrained by the properties of the system under study. Australian rainfall is zero-inflated, spatially heterogeneous, temporally autocorrelated, and driven by non-linear thermodynamic interactions. The Mixed-Effects ZIG model is not a complex model arbitrarily applied to a difficult problem. It is the appropriately structured model for a phenomenon whose properties are well-characterised. Its performance advantage over a linear baseline is a consequence of better alignment between model structure and physical reality, not of added parameters alone. The <span class="math inline">\(\Delta\text{AIC}\)</span> of 61,518.51 between the null baseline and the final model, accumulated across six theoretically motivated extensions each of which individually rejects the null at <span class="math inline">\(p &lt; 0.001\)</span>, quantifies precisely how much that alignment is worth.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/08-model-selection.html" class="pagination-link" aria-label="Model Selection">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Model Selection</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1"></a><span class="in">```{r}</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="co">#| label: setup-conclusion</span></span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="co">#| include: false</span></span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="in">```</span></span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="fu">## Conclusion {#sec-conclusion}</span></span>
<span id="cb1-10"><a href="#cb1-10"></a></span>
<span id="cb1-11"><a href="#cb1-11"></a>This analysis demonstrates that Australian daily rainfall is a structured physical phenomenon generated by distinct, identifiable processes operating at different temporal and spatial scales. The final Mixed-Effects Zero-Inflated Gamma (ZIG) model succeeds because its architecture was designed to reflect that structure.</span>
<span id="cb1-12"><a href="#cb1-12"></a></span>
<span id="cb1-13"><a href="#cb1-13"></a>The core argument, supported across seven analytical chapters, is that rainfall requires two qualitatively separate submodels. Occurrence and intensity are governed by different atmospheric mechanisms, respond to different covariates, and show different temporal and spatial patterns. Conflating them, as a standard Gaussian linear model or a Tweedie model does, produces predictions that are physically incoherent, statistically misspecified, and inferior in predictive accuracy. The ZIG framework assigns each process its own linear predictor and parameter vector, making the structural separation explicit.</span>
<span id="cb1-14"><a href="#cb1-14"></a></span>
<span id="cb1-15"><a href="#cb1-15"></a>---</span>
<span id="cb1-16"><a href="#cb1-16"></a></span>
<span id="cb1-17"><a href="#cb1-17"></a><span class="fu">## Summary of Principal Findings {#sec-findings}</span></span>
<span id="cb1-18"><a href="#cb1-18"></a></span>
<span id="cb1-19"><a href="#cb1-19"></a>**Distributional properties of the target variable.** The 142,199 daily observations show a zero-inflation rate of 64.05%, a skewness of 9.836, and a kurtosis of 181.146. The maximum recorded value is 371 mm, and 151 events exceed 100 mm. These properties collectively rule out a single-component Gaussian model: any such model would assign positive probability to negative rainfall values and systematically underestimate the probability of the zero outcome. The ZIG family, identified as appropriate by the EDA in @sec-eda, directly addresses both properties through a mixture of a point mass at zero and a Gamma-distributed positive component.</span>
<span id="cb1-20"><a href="#cb1-20"></a></span>
<span id="cb1-21"><a href="#cb1-21"></a>**The Rain Corner interaction.** Rainfall occurrence is not a linear function of humidity or sunshine individually. It concentrates in a specific region of the bivariate feature space where afternoon humidity exceeds approximately 60% and daily sunshine falls below approximately five hours simultaneously. The Sun-Humidity interaction term included in M4 is jointly significant at $F(2,\ 24.1) = 49.375$, $p &lt; 0.001$ (see @tbl-d1-m4-vs-m3), and the interaction is physically interpretable: the conjunction of a saturated atmosphere and suppressed solar radiation creates the thermodynamic conditions necessary for precipitation. An additive model cannot represent this conditional structure.</span>
<span id="cb1-22"><a href="#cb1-22"></a></span>
<span id="cb1-23"><a href="#cb1-23"></a>**Markovian persistence.** Having rained the previous day is the single strongest predictor in the zero-inflation submodel across the entire model sequence. The Markov Chain analysis in @sec-markov established that dry states have an 85% probability of remaining dry from one day to the next, while wet states have only a 47% probability of continued rain. Encoding this first-order dependency through <span class="in">`rain_yesterday`</span> and <span class="in">`days_since_rain`</span> was essential: the temporal features block (Day Cos, Day Sin, <span class="in">`rain_yesterday`</span>, Cloud Development) produced the largest pooled $D_1$ $F$-statistic in the model sequence at $F(4,\ 71.3) = 802.158$, $p &lt; 0.001$ (@tbl-d1-m2-vs-m1).</span>
<span id="cb1-24"><a href="#cb1-24"></a></span>
<span id="cb1-25"><a href="#cb1-25"></a>**Wind vector dynamics.** Wind direction is a circular variable whose information is destroyed by naive linear encoding. Decomposing compass bearings into orthogonal east-west and north-south components revealed that southerly and westerly airflows are the dominant directional drivers of rainfall intensity, consistent with the influence of Southern Ocean frontal systems. The four wind vector parameters are jointly significant at $F(4,\ 272.8) = 133.422$, $p &lt; 0.001$ (@tbl-d1-m5-vs-m4), with a relative increase in variance (RIV) of 0.497, the lowest in the sequence, indicating stable identification of wind direction signal across all imputed datasets.</span>
<span id="cb1-26"><a href="#cb1-26"></a></span>
<span id="cb1-27"><a href="#cb1-27"></a>**Spatial heterogeneity and random effects.** The random intercepts from the final mixed-effects model (M6) reveal location-specific baseline deviations in rainfall intensity that persist after all dynamic weather predictors are controlled. Tropical Top End stations produce roughly 1.7 to 1.8 times more rainfall than the national average at identical atmospheric conditions, while arid interior stations produce approximately half as much. The addition of splines and random effects over M5 yields $F(10,\ 138.9) = 75.283$, $p &lt; 0.001$, with $\Delta\text{AIC} = -6{,}915.32$ (@tbl-d1-m6-vs-m5). A pooled fixed-effects model would suppress this spatial variation by averaging across all stations, systematically over-predicting rainfall in inland stations and under-predicting it in tropical ones.</span>
<span id="cb1-28"><a href="#cb1-28"></a></span>
<span id="cb1-29"><a href="#cb1-29"></a>**Temporal autocorrelation elimination.** The Durbin-Watson statistic on the residuals of the final model is roughly around 2.0 among most of the locations. The temporal feature engineering documented in @sec-feature-eng, comprising <span class="in">`rain_yesterday`</span>, <span class="in">`rainfall_ma7`</span>, <span class="in">`humidity_ma7`</span>, and the natural spline of <span class="in">`days_since_rain`</span>, successfully absorbed the temporal dependence present in the raw data. What remains in the residuals is not the signature of an unmodelled temporal component but genuine unpredictability from the available predictors.</span>
<span id="cb1-30"><a href="#cb1-30"></a></span>
<span id="cb1-31"><a href="#cb1-31"></a>---</span>
<span id="cb1-32"><a href="#cb1-32"></a></span>
<span id="cb1-33"><a href="#cb1-33"></a><span class="fu">## Model Performance {#sec-performance}</span></span>
<span id="cb1-34"><a href="#cb1-34"></a></span>
<span id="cb1-35"><a href="#cb1-35"></a>The final model achieves the performance metrics in @tbl-performance, validated against the full dataset with DHARMa simulation-based diagnostics confirming residual adequacy.</span>
<span id="cb1-36"><a href="#cb1-36"></a></span>
<span id="cb1-39"><a href="#cb1-39"></a><span class="in">```{r}</span></span>
<span id="cb1-40"><a href="#cb1-40"></a><span class="co">#| label: tbl-performance</span></span>
<span id="cb1-41"><a href="#cb1-41"></a><span class="co">#| tbl-cap: "Summary of performance metrics for the final Mixed-Effects ZIG model (M6), validated on the full dataset."</span></span>
<span id="cb1-42"><a href="#cb1-42"></a><span class="co">#| echo: false</span></span>
<span id="cb1-43"><a href="#cb1-43"></a><span class="co">#| warning: false</span></span>
<span id="cb1-44"><a href="#cb1-44"></a><span class="co">#| message: false</span></span>
<span id="cb1-45"><a href="#cb1-45"></a></span>
<span id="cb1-46"><a href="#cb1-46"></a><span class="fu">tibble</span>(</span>
<span id="cb1-47"><a href="#cb1-47"></a>  <span class="at">Metric =</span> <span class="fu">c</span>(</span>
<span id="cb1-48"><a href="#cb1-48"></a>    <span class="st">"AUC (occurrence submodel)"</span>,</span>
<span id="cb1-49"><a href="#cb1-49"></a>    <span class="st">"Youden-optimal threshold"</span>,</span>
<span id="cb1-50"><a href="#cb1-50"></a>    <span class="st">"Brier Score"</span>,</span>
<span id="cb1-51"><a href="#cb1-51"></a>    <span class="st">"Brier Skill Score"</span>,</span>
<span id="cb1-52"><a href="#cb1-52"></a>    <span class="st">"Mean absolute error (all observations)"</span>,</span>
<span id="cb1-53"><a href="#cb1-53"></a>    <span class="st">"Mean absolute error (rain-days only)"</span>,</span>
<span id="cb1-54"><a href="#cb1-54"></a>    <span class="st">"RMSE (all observations)"</span>,</span>
<span id="cb1-55"><a href="#cb1-55"></a>    <span class="st">"RMSE (rain-days only)"</span>,</span>
<span id="cb1-56"><a href="#cb1-56"></a>    <span class="st">"Zero-inflation calibration ratio"</span>,</span>
<span id="cb1-57"><a href="#cb1-57"></a>    <span class="st">"Dispersion test (p-value)"</span></span>
<span id="cb1-58"><a href="#cb1-58"></a>  ),</span>
<span id="cb1-59"><a href="#cb1-59"></a>  <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb1-60"><a href="#cb1-60"></a>    <span class="st">"0.813"</span>,</span>
<span id="cb1-61"><a href="#cb1-61"></a>    <span class="st">"0.6246"</span>,</span>
<span id="cb1-62"><a href="#cb1-62"></a>    <span class="st">"0.1654"</span>,</span>
<span id="cb1-63"><a href="#cb1-63"></a>    <span class="st">"0.2819"</span>,</span>
<span id="cb1-64"><a href="#cb1-64"></a>    <span class="st">"2.760 mm"</span>,</span>
<span id="cb1-65"><a href="#cb1-65"></a>    <span class="st">"5.607 mm"</span>,</span>
<span id="cb1-66"><a href="#cb1-66"></a>    <span class="st">"7.567 mm"</span>,</span>
<span id="cb1-67"><a href="#cb1-67"></a>    <span class="st">"12.263 mm"</span>,</span>
<span id="cb1-68"><a href="#cb1-68"></a>    <span class="st">"1.00 (p = 0.512)"</span>,</span>
<span id="cb1-69"><a href="#cb1-69"></a>    <span class="st">"0.152"</span></span>
<span id="cb1-70"><a href="#cb1-70"></a>  )</span>
<span id="cb1-71"><a href="#cb1-71"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb1-72"><a href="#cb1-72"></a>  <span class="fu">kable</span>(</span>
<span id="cb1-73"><a href="#cb1-73"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Metric"</span>, <span class="st">"Value"</span>),</span>
<span id="cb1-74"><a href="#cb1-74"></a>    <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"l"</span>, <span class="st">"r"</span>),</span>
<span id="cb1-75"><a href="#cb1-75"></a>    <span class="at">escape =</span> <span class="cn">FALSE</span>,</span>
<span id="cb1-76"><a href="#cb1-76"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span></span>
<span id="cb1-77"><a href="#cb1-77"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-78"><a href="#cb1-78"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb1-79"><a href="#cb1-79"></a>    <span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hold_position"</span>),</span>
<span id="cb1-80"><a href="#cb1-80"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span></span>
<span id="cb1-81"><a href="#cb1-81"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-82"><a href="#cb1-82"></a>  <span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">"10cm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-83"><a href="#cb1-83"></a>  <span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">width =</span> <span class="st">"4cm"</span>)</span>
<span id="cb1-84"><a href="#cb1-84"></a><span class="in">```</span></span>
<span id="cb1-85"><a href="#cb1-85"></a></span>
<span id="cb1-86"><a href="#cb1-86"></a>The AUC of 0.813 confirms that the occurrence submodel correctly ranks a randomly drawn dry day above a randomly drawn wet day in 81.3% of cases, a threshold-free measure of discriminative performance that does not depend on any particular operating point. At the Youden-optimal threshold of 0.6246, the Brier Score of 0.1654 and Brier Skill Score of 0.2819 quantify the calibrated probabilistic accuracy of the occurrence submodel relative to a naive climatological baseline. The MAE of 2.760 mm represents the average absolute deviation between the model's point prediction and the recorded observation across all days; the higher rain-day MAE of 5.607 mm reflects the harder prediction problem on positive observations once dry days are excluded. The zero-inflation calibration ratio of 1.00 ($p = 0.512$) confirms that the hurdle component reproduces the 64.05% dry-day rate correctly across the full conditional distribution of covariates, not merely at the intercept. The dispersion test yields $p = 0.152$, giving no evidence that the residual variance deviates from what the fitted ZIG family implies. </span>
<span id="cb1-87"><a href="#cb1-87"></a></span>
<span id="cb1-88"><a href="#cb1-88"></a>---</span>
<span id="cb1-89"><a href="#cb1-89"></a></span>
<span id="cb1-90"><a href="#cb1-90"></a><span class="fu">## Limitations {#sec-limitations}</span></span>
<span id="cb1-91"><a href="#cb1-91"></a></span>
<span id="cb1-92"><a href="#cb1-92"></a>**Tail underestimation.** The Gamma distribution accommodates right skew but has exponentially declining tails rather than power-law tails. Rare events exceeding approximately 50 mm per day are systematically under-predicted. The model correctly identifies conditions conducive to extreme rainfall but underestimates the magnitude of such events. This is an inherent property of the Gamma family, not a failure of specification within that family.</span>
<span id="cb1-93"><a href="#cb1-93"></a></span>
<span id="cb1-94"><a href="#cb1-94"></a>**Stationarity.** All parameters are estimated from a fixed historical record and are assumed stable over time. The model does not encode non-stationarity arising from shifts in the Southern Oscillation Index, the Indian Ocean Dipole, or long-term anthropogenic forcing. Predictions made under climate trajectories outside the historical parameter space are extrapolations beyond the scope of the model.</span>
<span id="cb1-95"><a href="#cb1-95"></a></span>
<span id="cb1-96"><a href="#cb1-96"></a>**Observational confounding.** Coefficient estimates represent conditional associations, not causal effects. Unobserved variables including soil moisture feedback, aerosol loading, and land surface characteristics may confound the estimated meteorological relationships. The model is appropriate for prediction under conditions similar to the training data; causal attribution of rainfall to specific drivers requires experimental or quasi-experimental designs.</span>
<span id="cb1-97"><a href="#cb1-97"></a></span>
<span id="cb1-98"><a href="#cb1-98"></a>---</span>
<span id="cb1-99"><a href="#cb1-99"></a></span>
<span id="cb1-100"><a href="#cb1-100"></a><span class="fu">## Recommended Extensions {#sec-extensions}</span></span>
<span id="cb1-101"><a href="#cb1-101"></a></span>
<span id="cb1-102"><a href="#cb1-102"></a>**Extreme value tail augmentation.** A natural extension is a composite model that applies the ZIG framework to the body of the distribution and grafts a Generalised Pareto Distribution (GPD) to exceedances above the 95th percentile. This would preserve predictive accuracy on typical days while correcting the systematic tail underestimation that limits the model's utility for flood risk applications.</span>
<span id="cb1-103"><a href="#cb1-103"></a></span>
<span id="cb1-104"><a href="#cb1-104"></a>**Large-scale climate indices.** The Southern Oscillation Index and the Indian Ocean Dipole modulate Australian rainfall at interannual timescales and are absent from the current feature set. Including them as slowly varying covariates in either submodel would allow the model to shift its baseline predictions between El Niño and La Niña years, addressing a known gap in predictive accuracy for anomalous climate regimes.</span>
<span id="cb1-105"><a href="#cb1-105"></a></span>
<span id="cb1-106"><a href="#cb1-106"></a>**Dynamic updating.** The current model is static, estimated once from the full historical record. A natural operational extension would implement sequential re-estimation of the random effects as new observations accumulate, allowing location-specific baselines to track gradual shifts in local climate without re-fitting the full fixed-effects structure.</span>
<span id="cb1-107"><a href="#cb1-107"></a></span>
<span id="cb1-108"><a href="#cb1-108"></a>---</span>
<span id="cb1-109"><a href="#cb1-109"></a></span>
<span id="cb1-110"><a href="#cb1-110"></a><span class="fu">## Closing Statement {#sec-closing}</span></span>
<span id="cb1-111"><a href="#cb1-111"></a></span>
<span id="cb1-112"><a href="#cb1-112"></a>The methodological progression across this report reflects a single guiding principle: statistical modelling should be constrained by the properties of the system under study. Australian rainfall is zero-inflated, spatially heterogeneous, temporally autocorrelated, and driven by non-linear thermodynamic interactions. The Mixed-Effects ZIG model is not a complex model arbitrarily applied to a difficult problem. It is the appropriately structured model for a phenomenon whose properties are well-characterised. Its performance advantage over a linear baseline is a consequence of better alignment between model structure and physical reality, not of added parameters alone. The $\Delta\text{AIC}$ of 61,518.51 between the null baseline and the final model, accumulated across six theoretically motivated extensions each of which individually rejects the null at $p &lt; 0.001$, quantifies precisely how much that alignment is worth.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/blob/main/chapters/09-conclusion.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/chrisolande/Statistical-Inference-Zero-Inflated-Models/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer><script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>