{
  "hash": "e7329eb5175fd886113a2dc4671a0355",
  "result": {
    "engine": "knitr",
    "markdown": "# Model Evaluation\n## Validating the Final Mixed-Effects Zero-Inflated Gamma Model\n\n---\n\n> **Chapter Context.** A model that fits training data well is not necessarily a model that is correct. This chapter subjects the final mixed-effects ZIG model (M6) to four distinct validation procedures, each targeting a different potential failure mode: poor discriminative ability in the occurrence submodel, spatially inappropriate parameter homogeneity, distributional misspecification in the residuals, and unabsorbed temporal autocorrelation. Together, these tests form a coherent audit of the model's assumptions and capabilities.\n\n---\n\n## Classification Performance of the Occurrence Submodel\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprob_no_rain <- predict(m6_mixed, type = \"zprob\")\nactual_no_rain <- ifelse(re_data$rainfall == 0, 1, 0)\n\nroc_obj <- roc(actual_no_rain, prob_no_rain)\n\nplot(\n  roc_obj,\n  main = \"ROC Curve: Predicting Rainfall Occurrence\",\n  col = \"#0072B2\",\n  lwd = 2,\n  print.auc = TRUE,\n  print.auc.y = 0.4\n)\n```\n\n::: {.cell-output-display}\n![ROC Curve for Rainfall Occurrence Prediction. AUC = 0.827 indicates strong discriminative ability in separating dry days from wet days.](06-evaluation_files/figure-html/model-evaluation-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ncoords_obj <- coords(roc_obj, \"best\", best.method = \"youden\")\noptimal_threshold <- coords_obj$threshold\n\ncat(sprintf(\"\\nOptimal Probability Threshold: %.4f\\n\", optimal_threshold))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Optimal Probability Threshold: 0.6314\n```\n\n\n:::\n\n```{.r .cell-code}\npredicted_class <- ifelse(prob_no_rain > optimal_threshold, \"No Rain\", \"Rain\")\nactual_class <- ifelse(re_data$rainfall == 0, \"No Rain\", \"Rain\")\n\nconf_matrix <- table(Predicted = predicted_class, Actual = actual_class)\n\nconf_matrix %>%\n  kable(caption = \"Confusion Matrix at the Youden-Optimal Threshold\") %>%\n  kable_styling(bootstrap_options = \"striped\", full_width = FALSE)\n```\n\n::: {.cell-output-display}\n<table class=\"table table-striped\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Confusion Matrix at the Youden-Optimal Threshold</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">  </th>\n   <th style=\"text-align:right;\"> No Rain </th>\n   <th style=\"text-align:right;\"> Rain </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> No Rain </td>\n   <td style=\"text-align:right;\"> 69365 </td>\n   <td style=\"text-align:right;\"> 13596 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Rain </td>\n   <td style=\"text-align:right;\"> 21473 </td>\n   <td style=\"text-align:right;\"> 37422 </td>\n  </tr>\n</tbody>\n</table>\n\n\n\nROC Curve for Rainfall Occurrence Prediction. AUC = 0.827 indicates strong discriminative ability in separating dry days from wet days.\n:::\n\n```{.r .cell-code}\naccuracy <- sum(diag(conf_matrix)) / sum(conf_matrix)\ncat(sprintf(\"\\nOverall Accuracy: %.2f%%\\n\", accuracy * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Overall Accuracy: 75.28%\n```\n\n\n:::\n:::\n\n\nAlthough the ZIG model is primarily a framework for predicting rainfall amount, its zero-inflation component constitutes a binary classifier at each observation: it assigns a probability that the day is structurally dry, irrespective of other atmospheric conditions. Evaluating this component as a classifier allows us to assess how well the model separates the two fundamentally different weather states identified in the @sec-eda.\n\n**Discriminative ability.** The area under the ROC curve is 0.827, meaning that in 82.7% of randomly drawn pairs consisting of one genuinely dry day and one genuinely wet day, the model correctly assigns the higher dryness probability to the dry day. This is a threshold-free measure of separation that does not depend on any particular operating point, and it indicates strong discriminative performance for a meteorological classification problem of this complexity.\n\n**Threshold selection.** The raw zero-inflation probability must be converted to a binary prediction through a threshold. Youden's J statistic which maximises the sum of sensitivity and specificity simultaneously selects an optimal threshold of 0.6314. This is notably higher than the naive 0.5 default, and the reason is structural: because dry days constitute 64% of the sample, the model's calibrated prior assigns moderate dryness probability to many observations by default. A higher threshold requires more decisive evidence of a dry signal before predicting \"No Rain,\" which appropriately reflects the prior imbalance in class frequencies.\n\n**Confusion matrix.** At this threshold, overall accuracy is 75.28%, decomposing into 69,365 correct dry-day predictions (true negatives), 37,422 correct rain predictions (true positives), 21,473 false alarms (predicted dry, actually wet), and 13,596 missed rain events (predicted wet, actually dry). The model generates false alarms at roughly twice the rate at which it misses rain events. In a meteorological context this asymmetry is operationally desirable: the consequence of carrying an umbrella on a dry day is trivial compared to the consequence of being unprepared for a significant rainfall event. A model biased toward caution is appropriate for this domain.\n\n---\n\n## Spatial Heterogeneity and Random Effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nranef_data <- ranef(m6_mixed)\n\nloc_effects <- as.data.frame(ranef_data$cond$location) %>%\n  rownames_to_column(\"Location\") %>%\n  rename(Effect = `(Intercept)`) %>%\n  arrange(Effect) %>%\n  mutate(\n    Location = factor(Location, levels = Location),\n    CI_lower = Effect - 1.96 * sd(Effect) / sqrt(n()),\n    CI_upper = Effect + 1.96 * sd(Effect) / sqrt(n()),\n    Category = case_when(\n      Effect > sd(Effect) ~ \"Significantly Wetter\",\n      Effect < -sd(Effect) ~ \"Significantly Drier\",\n      TRUE ~ \"Near Average\"\n    ),\n    Category = factor(\n      Category,\n      levels = c(\"Significantly Drier\", \"Near Average\", \"Significantly Wetter\")\n    )\n  )\n\nggplot(loc_effects, aes(x = Effect, y = Location)) +\n  annotate(\n    \"rect\",\n    xmin = -Inf,\n    xmax = -sd(loc_effects$Effect),\n    ymin = -Inf,\n    ymax = Inf,\n    fill = \"#c0392b\",\n    alpha = 0.05\n  ) +\n  annotate(\n    \"rect\",\n    xmin = sd(loc_effects$Effect),\n    xmax = Inf,\n    ymin = -Inf,\n    ymax = Inf,\n    fill = \"#2980b9\",\n    alpha = 0.05\n  ) +\n  geom_vline(\n    xintercept = 0,\n    linetype = \"dashed\",\n    color = \"grey30\",\n    linewidth = 0.8\n  ) +\n  geom_vline(\n    xintercept = c(-sd(loc_effects$Effect), sd(loc_effects$Effect)),\n    linetype = \"dotted\",\n    color = \"grey50\",\n    linewidth = 0.5\n  ) +\n  geom_segment(\n    aes(\n      x = CI_lower,\n      xend = CI_upper,\n      y = Location,\n      yend = Location,\n      color = Category\n    ),\n    linewidth = 1.5,\n    alpha = 0.4\n  ) +\n  geom_point(aes(color = Category), size = 4, alpha = 0.9) +\n  geom_text(\n    data = filter(loc_effects, abs(Effect) > sd(Effect)),\n    aes(\n      label = sprintf(\"%.2f\", Effect),\n      x = Effect,\n      hjust = ifelse(Effect > 0, -0.3, 1.3)\n    ),\n    size = 3,\n    fontface = \"bold\",\n    color = \"grey20\"\n  ) +\n  scale_color_manual(\n    values = c(\n      \"Significantly Drier\" = \"#c0392b\",\n      \"Near Average\" = \"#7f8c8d\",\n      \"Significantly Wetter\" = \"#2980b9\"\n    ),\n    name = \"Effect Size\"\n  ) +\n  labs(\n    title = \"The Geography of Rain: Location-Specific Baselines\",\n    subtitle = \"Random intercepts show how much wetter or drier each city is, holding all weather variables constant.\\nBars show 95% confidence intervals; points beyond ±1 SD are labeled.\",\n    x = \"Baseline Rainfall Adjustment (Log mm)\",\n    y = NULL,\n    caption = \"Interpretation: A value of +0.5 means approximately 65% more rain than an average location with identical conditions [exp(0.5) ≈ 1.65]\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.major.y = element_line(color = \"grey90\", linewidth = 0.3),\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_line(color = \"grey90\", linewidth = 0.3),\n    plot.title = element_text(face = \"bold\", size = 16, margin = margin(b = 5)),\n    plot.subtitle = element_text(\n      color = \"grey30\",\n      size = 11,\n      margin = margin(b = 15)\n    ),\n    plot.caption = element_text(\n      color = \"grey50\",\n      size = 9,\n      hjust = 0,\n      margin = margin(t = 10)\n    ),\n    axis.text.y = element_text(size = 10, face = \"bold\"),\n    axis.text.x = element_text(size = 10),\n    axis.title.x = element_text(\n      size = 11,\n      face = \"bold\",\n      margin = margin(t = 10)\n    ),\n    legend.position = \"top\",\n    legend.justification = \"left\",\n    legend.title = element_text(face = \"bold\", size = 10),\n    legend.text = element_text(size = 9),\n    plot.margin = margin(15, 15, 15, 15)\n  )\n```\n\n::: {.cell-output-display}\n![Location-specific baseline rainfall adjustments (random intercepts). Cities to the right of the dashed line produce systematically more rainfall than the national average when all dynamic weather variables are held constant; cities to the left produce systematically less.](06-evaluation_files/figure-html/fig-location-effects-1.png){#fig-location-effects fig-align='center' width=100%}\n:::\n:::\n\n\nThe random intercepts from the mixed-effects model represent the location-specific baseline deviations in rainfall intensity after removing the contribution of all dynamic weather variables, humidity, pressure, wind, seasonality, and persistence. What remains is the component of rainfall that is attributable to geographic and climatic factors that do not vary day-to-day: proximity to moisture sources, orographic effects, predominant circulation patterns, and regional climate regime.\n\n**The wetter locations.** Katherine ($\\hat{b} = 0.54$) and Tuggeranong ($\\hat{b} = 0.57$) sit at the high end of the distribution. Exponentiating these values: $e^{0.54} \\approx 1.72$ and $e^{0.57} \\approx 1.77$, meaning that these stations produce roughly 72% and 77% more rainfall respectively than a hypothetical average Australian location experiencing identical instantaneous weather conditions. This is geographically coherent: both stations sit in the tropical Top End of the Northern Territory, where monsoonal systems deliver sustained and intense rainfall that has no structural analogue in the temperate south, and which the fixed-effects predictors measured on individual days cannot fully capture.\n\n**The drier locations.** Nhil ($\\hat{b} = -0.66$) and Norfolk Island ($\\hat{b} = -0.72$) show the strongest negative adjustments. $e^{-0.66} \\approx 0.52$, indicating that Nhil produces roughly half the rainfall of an average location given identical weather conditions. This reflects its position in the semi-arid Wimmera region of inland Victoria, where even moisture-laden air masses tend to deliver less precipitation than they would on the coast.\n\n**Justification for the mixed-effects structure.** The magnitude and geographic coherence of these deviations confirm the necessity of the random effects component. A pooled fixed-effects model would have suppressed this spatial variation by averaging across all locations, producing a single set of coefficients that systematically over-predicts rainfall in arid interior stations and under-predicts it in tropical ones. The mixed-effects structure allows the global physical relationships humidity drives intensity, southerly winds bring moisture, to remain stable as fixed effects while accommodating the fact that those relationships operate against a geographically variable baseline.\n\n---\n\n## Residual Diagnostics via DHARMa Simulation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nres <- simulateResiduals(m6_mixed)\nplot(res)\n```\n\n::: {.cell-output-display}\n![DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs. predicted values.](06-evaluation_files/figure-html/model-diagnostics-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\ntestDispersion(res)\n```\n\n::: {.cell-output-display}\n![DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs. predicted values.](06-evaluation_files/figure-html/model-diagnostics-2.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tDHARMa nonparametric dispersion test via sd of residuals fitted vs.\n#> \tsimulated\n#> \n#> data:  simulationOutput\n#> dispersion = 0.76846, p-value = 0.36\n#> alternative hypothesis: two.sided\n```\n\n\n:::\n\n```{.r .cell-code}\ntestZeroInflation(res)\n```\n\n::: {.cell-output-display}\n![DHARMa simulated residual diagnostics for M6. Left: Q-Q plot of scaled residuals against the expected uniform distribution. Right: Residuals vs. predicted values.](06-evaluation_files/figure-html/model-diagnostics-3.png){fig-align='center' width=100%}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tDHARMa zero-inflation test via comparison to expected zeros with\n#> \tsimulation under H0 = fitted model\n#> \n#> data:  simulationOutput\n#> ratioObsSim = 1.0001, p-value = 0.976\n#> alternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nStandard residual diagnostics are not directly applicable to Zero-Inflated Gamma models: the mixture of a point mass at zero and a continuous positive distribution means that conventional Pearson or deviance residuals do not have a tractable reference distribution. DHARMa addresses this by generating a large number of simulated datasets from the fitted model and computing, for each observation, where the actual value falls in the empirical distribution of simulated values. Under a correctly specified model, these *scaled residuals* follow a uniform distribution on $[0, 1]$ regardless of the model family. Deviations from uniformity indicate misspecification.\n\n**Q-Q plot.** The empirical quantiles of the scaled residuals align closely with the theoretical diagonal across the full range of the distribution. The Kolmogorov-Smirnov test registers $p < 0.05$, but this outcome is expected and should not be interpreted as evidence of meaningful misfit: with $N > 140,000$ observations, the test has sufficient power to detect deviations of negligible practical magnitude. The visual alignment of the Q-Q plot the appropriate diagnostic at this sample size shows no systematic departure from the uniform reference.\n\n**Residuals versus predicted.** The three quantile lines (25th, 50th, and 75th percentiles of the scaled residuals at each fitted value) are horizontal and evenly spaced across the range of predictions. This indicates the absence of systematic non-linearity (which would manifest as curvature in the 50th percentile line) and the absence of heteroscedasticity (which would manifest as convergence or divergence of the outer quantile lines). The model performs with equivalent fidelity across the full range of rainfall intensities, from light drizzle to extreme events.\n\n**Formal test results.** The dispersion test yields $p = 0.36$, giving no evidence that the variance of the residuals deviates from what the fitted ZIG family implies. The zero-inflation test produces a ratio of observed to simulated zero counts of exactly 1.00 ($p = 0.976$), confirming that the model's hurdle component is correctly calibrated and is neither over nor under-predicting the number of dry days in the sample. This last result is particularly notable: it means the 64% zero-inflation rate is not merely matched at the intercept level (as confirmed in the null model calibration check) but is correctly reproduced across the full conditional distribution of covariates.\n\n---\n\n## Temporal Autocorrelation in Residuals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrows_used <- as.numeric(rownames(m6_mixed$frame))\n\nCanberra_data <- df_final[rows_used, ] %>%\n  mutate(dharma_resid = residuals(res)) %>%\n  filter(location == \"Canberra\") %>%\n  arrange(date)\n\ndw_result <- testTemporalAutocorrelation(\n  simulationOutput = Canberra_data$dharma_resid,\n  time = Canberra_data$date\n)\n```\n\n::: {.cell-output-display}\n![Temporal residual diagnostics for Canberra. Random scatter across time and ACF values within the confidence bounds at all lags indicate the absence of residual autocorrelation.](06-evaluation_files/figure-html/temporal-autocorrelation-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\nprint(dw_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tDurbin-Watson test\n#> \n#> data:  simulationOutput$scaledResiduals ~ 1\n#> DW = 2.0533, p-value = 0.1197\n#> alternative hypothesis: true autocorrelation is not 0\n```\n\n\n:::\n:::\n\n\nThe most consequential assumption to verify in a time-series regression is whether the residuals are serially independent, that is, whether the unexplained portion of each observation is unrelated to the unexplained portion of observations that preceded it. If the model has failed to capture all temporal structure in the data, residuals from consecutive days will be correlated, violating the assumption of independent errors and producing standard errors that are too small, confidence intervals that are too narrow, and significance tests that are anti-conservative.\n\nThis risk is particularly salient here. The raw data shows strong temporal autocorrelation: yesterday's rain state, the weekly wetness trend, and the dry spell dynamics all create day-to-day dependencies that, if unmodelled, would produce heavily autocorrelated residuals. The model addresses this through multiple temporal mechanisms: the Markov persistence feature `rain_yesterday`, the 7-day moving average features, the natural spline of `days_since_rain`, and the cyclical seasonal encoding. The question is whether these collectively absorb the temporal signal or whether residual autocorrelation persists.\n\nThe Durbin-Watson test statistic is 2.0533. The theoretical value under perfect independence is exactly 2.0; values below 2 indicate positive autocorrelation and values above 2 indicate negative autocorrelation. A value of 2.04 is essentially indistinguishable from the ideal, and the associated p-value of 0.1197 gives no grounds to reject the null hypothesis of independence.\n\nThe ACF plot corroborates this: autocorrelation coefficients at all examined lags fall within the 95% confidence bounds, confirming the absence of any systematic periodic or decay structure in the residuals.\n\nThe interpretation is that the temporal engineering performed in the feature construction chapter was effective. By explicitly representing the day-to-day Markov structure, the medium-horizon wetness regime, and the non-linear dry spell decay, the model has absorbed the temporal dependence in the data and reduced its residuals to exchangeable noise. What remains unexplained is genuinely unpredictable from the available predictors, not the signature of an omitted temporal component.\n\n---\n\n## Summary of Validation Results\n\nThe four validation procedures converge on a consistent picture of a well-specified model.\n\nThe occurrence submodel discriminates between dry and wet days with an AUC of 0.827, achieves 75.28% classification accuracy, and shows a conservative error profile appropriate for meteorological risk communication. The random effects structure captures geographically coherent spatial heterogeneity that a pooled model would suppress, with the tropical north and arid interior deviating from the national average by factors of approximately 1.8 and 0.5 respectively. The DHARMa diagnostics find no evidence of distributional misspecification, heteroscedasticity, over-dispersion, or miscalibrated zero-inflation. And the temporal autocorrelation test confirms that the model's persistence and dry spell features have successfully eliminated serial dependence from the residuals.\n\nTaken together, these results support the conclusion that the final ZIG mixed-effects model is both statistically valid and physically well-grounded, a model whose structure reflects the actual mechanisms generating Australian rainfall rather than artefacts of the fitting procedure.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}